export const activityClient = String.raw`
let activityFilters={query:'',origin:'',window:'all'};
let playbookState={query:'',filter:'all',selectedId:''};
function renderActivityLoading(root){
 root.innerHTML='<section class="activity-workspace activity-loading" aria-busy="true" aria-live="polite"><div class="project-hero"><div><div class="goal-kicker">A clear record of what happened</div><h1>Your workspace, in motion.</h1><p>Checking the local record of actions and evidence.</p></div><i class="activity-action-skeleton"></i></div><div class="activity-controls-skeleton"><i></i><i></i><i></i></div><div class="activity-timeline-skeleton"><article><i></i><div><strong></strong><span></span></div></article><article><i></i><div><strong></strong><span></span></div></article><article><i></i><div><strong></strong><span></span></div></article></div></section>';
}
function renderPlaybookLoading(root){
 root.innerHTML='<section class="playbook-library playbook-loading" aria-busy="true" aria-live="polite"><div class="project-hero"><div><div class="goal-kicker">Repeatable work starts here</div><h1>Turn know-how into playbooks.</h1><p>Checking saved procedures and their review state.</p></div><i class="activity-action-skeleton"></i></div><div class="activity-controls-skeleton"><i></i><i></i></div><div class="playbook-layout"><div class="playbook-list-skeleton"><i></i><i></i><i></i></div><div class="playbook-reader-skeleton"><strong></strong><span></span><span></span><span></span></div></div></section>';
}
async function showActivityTimeline(){
  const root=document.getElementById('view-content');renderActivityLoading(root);let records;try{records=await conversationRequest('/api/audit');}catch(error){if(currentView!=='activity'||!root.isConnected)return;root.replaceChildren();const notice=document.createElement('section');notice.className='goal-empty';const heading=document.createElement('h2');heading.textContent='Activity could not be checked';const copy=document.createElement('p');copy.textContent=error.message||'No records were changed.';const retry=document.createElement('button');retry.className='btn';retry.textContent='Try again';retry.onclick=showActivityTimeline;notice.append(heading,copy,retry);root.append(notice);return;}if(currentView!=='activity')return;
  root.innerHTML='<section class="activity-workspace"><div class="project-hero"><div><div class="goal-kicker">A clear record of what happened</div><h1>Your workspace, in motion.</h1><p>Recorded actions, their source, and the evidence behind them.</p></div><button class="btn btn-secondary" id="audit-verify">Verify audit chain</button></div><p id="audit-result" class="conversation-feedback" aria-live="polite"></p><div class="project-controls activity-controls"><input class="form-control" id="audit-search" aria-label="Search activity" placeholder="Find an action, record, or actor…"><select class="form-control" id="audit-origin" aria-label="Filter source"><option value="">All sources</option></select><select class="form-control" id="audit-window" aria-label="Filter activity time"><option value="all">All recorded time</option><option value="24h">Last 24 hours</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option></select></div><p class="activity-result-count" role="status"></p><div class="activity-timeline"></div></section>';
  const search=document.getElementById('audit-search'),origins=document.getElementById('audit-origin'),windowSelect=document.getElementById('audit-window');search.value=activityFilters.query;for(const origin of [...new Set(records.map(r=>r.origin))]){const option=document.createElement('option');option.value=origin;option.textContent=origin;origins.appendChild(option);}origins.value=activityFilters.origin;windowSelect.value=activityFilters.window;
  const render=()=>{const query=search.value.toLowerCase();const source=origins.value;const period=windowSelect.value;activityFilters={query:search.value,origin:source,window:period};const now=Date.now();const since=period==='24h'?now-86400000:period==='7d'?now-604800000:period==='30d'?now-2592000000:0;const list=root.querySelector('.activity-timeline');list.replaceChildren();let previousDate='';
    const filtered=records.filter(r=>Date.parse(r.timestamp)>=since&&(!source||r.origin===source)&&[r.action,r.actorId,r.targetId].join(' ').toLowerCase().includes(query));
    root.querySelector('.activity-result-count').textContent=filtered.length+' of '+records.length+' recorded events'+(period==='all'?'':' in '+windowSelect.options[windowSelect.selectedIndex].text.toLowerCase());
    for(const record of filtered){const day=new Date(record.timestamp).toLocaleDateString([],{weekday:'long',month:'long',day:'numeric'});if(day!==previousDate){const heading=document.createElement('h2');heading.className='activity-day';heading.textContent=day;list.appendChild(heading);previousDate=day;}const row=document.createElement('details');row.className='activity-event';const summary=document.createElement('summary');const time=document.createElement('time');time.textContent=new Date(record.timestamp).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});const title=document.createElement('strong');title.textContent=record.action.replaceAll('_',' ');const meta=document.createElement('span');meta.textContent=record.origin+' · '+(record.actorType==='human'?'You':record.actorType==='agent'?'Teammate':'System');summary.append(time,title,meta);const detail=document.createElement('div');const target=document.createElement('p');target.textContent='Recorded against '+record.targetType;const raw=document.createElement('pre');raw.textContent=JSON.stringify(record.details,null,2);detail.append(target,raw);row.append(summary,detail);list.appendChild(row);}
    if(!filtered.length){const empty=document.createElement('div');empty.className='goal-empty';empty.textContent='No recorded activity matches this view.';list.appendChild(empty);}
  };
  search.oninput=render;origins.onchange=render;windowSelect.onchange=render;
  document.getElementById('audit-verify').onclick=async()=>{const feedback=document.getElementById('audit-result');try{const result=await conversationRequest('/api/audit/verify');feedback.textContent=result.valid ? 'Audit chain verified: '+result.totalEntries+' recorded entries checked.' : 'Audit verification failed. Inspect the saved audit records.';}catch(error){feedback.textContent=error.message;}};render();
}
async function showPlaybookLibrary(){
  const root=document.getElementById('view-content');renderPlaybookLoading(root);let processes;try{processes=await conversationRequest('/api/processes');}catch(error){if(currentView!=='processes'||!root.isConnected)return;root.replaceChildren();const notice=document.createElement('section');notice.className='goal-empty';const heading=document.createElement('h2');heading.textContent='Playbooks could not be checked';const copy=document.createElement('p');copy.textContent=error.message||'No procedure was changed.';const retry=document.createElement('button');retry.className='btn';retry.textContent='Try again';retry.onclick=showPlaybookLibrary;notice.append(heading,copy,retry);root.append(notice);return;}if(currentView!=='processes')return;
  root.innerHTML='<section class="playbook-library"><div class="project-hero"><div><div class="goal-kicker">Repeatable work starts here</div><h1>Turn know-how into playbooks.</h1><p>Keep procedures, review their changes, and resolve open questions before agents use them.</p></div><button class="btn" id="library-import">+ Import playbook</button></div><div class="project-controls"><input id="playbook-search" class="form-control" aria-label="Search playbooks" placeholder="Find a procedure…"><select class="form-control" id="playbook-filter" aria-label="Filter playbooks"><option value="all">All playbooks</option><option value="review">Questions to resolve</option><option value="clear">No unresolved questions</option></select></div><div class="playbook-layout"><div class="playbook-list"></div><div class="playbook-reader"><div class="goal-empty">Choose a playbook to read its steps, review open questions, or propose an updated version. A playbook is guidance; it does not grant execution permission.</div></div></div></section>';
  const search=document.getElementById('playbook-search'),filterSelect=document.getElementById('playbook-filter');search.value=playbookState.query;filterSelect.value=playbookState.filter;document.getElementById('library-import').onclick=openProcessImportModal;
  const renderReader=(process,button)=>{const list=root.querySelector('.playbook-list');playbookState.selectedId=process.id;list.querySelectorAll('button').forEach(entry=>entry.setAttribute('aria-pressed',String(entry===button||entry.dataset.processId===process.id)));const reader=root.querySelector('.playbook-reader');reader.innerHTML=renderProcessCard(process);const steps=document.createElement('ol');steps.className='playbook-steps';for(const step of process.steps){const item=document.createElement('li');const heading=document.createElement('h3');heading.textContent=step.title;const instruction=document.createElement('p');instruction.textContent=step.instruction;item.append(heading,instruction);steps.appendChild(item);}const guide=document.createElement('section');guide.className='playbook-outline';const heading=document.createElement('h2');heading.textContent=process.title;const caption=document.createElement('p');caption.textContent=process.steps.length+' procedure steps · Select a step to read its instructions. This is a procedure, not a live run.';guide.append(heading,caption);const navigation=document.createElement('nav');navigation.setAttribute('aria-label','Procedure steps');
for(const [index,step] of process.steps.entries()){const jump=document.createElement('button');jump.className='playbook-step-link';const number=document.createElement('span');number.textContent=String(index+1);const label=document.createElement('strong');label.textContent=step.title;jump.append(number,label);jump.onclick=()=>{const target=steps.children[index];target.tabIndex=-1;target.scrollIntoView({block:'center'});target.focus({preventScroll:true});};navigation.append(jump);}guide.append(navigation);reader.prepend(guide,steps);};
  const render=()=>{const list=root.querySelector('.playbook-list');list.replaceChildren();const query=search.value.toLowerCase();const filter=filterSelect.value;playbookState.query=search.value;playbookState.filter=filter;
    const records=processes.filter(p=>p.title.toLowerCase().includes(query)&&(filter==='all'||(filter==='review')===p.unresolvedRules.some(r=>!r.resolved)));
    for(const process of records){const button=document.createElement('button');button.className='playbook-list-item';button.dataset.processId=process.id;const title=document.createElement('strong');title.textContent=process.title;const meta=document.createElement('span');meta.textContent='v'+process.version+' · '+process.steps.length+' steps · '+process.unresolvedRules.filter(r=>!r.resolved).length+' open questions';button.append(title,meta);button.onclick=()=>renderReader(process,button);list.appendChild(button);}
    const selected=records.find(process=>process.id===playbookState.selectedId);if(selected)renderReader(selected,list.querySelector('[data-process-id="'+CSS.escape(selected.id)+'"]'));else if(playbookState.selectedId){root.querySelector('.playbook-reader').innerHTML='<div class="goal-empty">The selected playbook is outside this filter. Clear or change the filter to return to it.</div>';}
    if(!records.length){const empty=document.createElement('div');empty.className='goal-empty';empty.textContent=processes.length?'No matching playbooks.':'No playbooks saved yet. Import a procedure when you are ready to turn repeatable work into a reviewed playbook.';list.appendChild(empty);}
  };search.oninput=render;filterSelect.onchange=render;render();
}
`;
