/** Browse existing package manifests without implying a live marketplace. */
export const catalogClient = String.raw`
function renderCatalogLoading(root){
 root.innerHTML='<main class="catalog-workspace catalog-loading" aria-busy="true" aria-live="polite"><header class="project-hero"><div><span class="forge-topline">EXTEND YOUR WORKSPACE</span><h1>Package library</h1><p>Checking local manifests and the permissions they request.</p></div><div class="catalog-art" aria-hidden="true"><span>◇</span><span>✳</span><span>+</span><span>↗</span></div></header><div class="catalog-controls-skeleton"><i></i><i></i><span></span></div><div class="catalog-grid-skeleton"><article><i></i><strong></strong><span></span><span></span><b></b></article><article><i></i><strong></strong><span></span><span></span><b></b></article><article><i></i><strong></strong><span></span><span></span><b></b></article></div></main>';
}
async function showPackageLibrary(){
 const root=document.getElementById('view-content');renderCatalogLoading(root);let data;try{data=await conversationRequest('/api/packages');}catch(error){if(currentView!=='marketplace'||!root.isConnected)return;root.replaceChildren();const notice=document.createElement('section');notice.className='goal-empty';const heading=document.createElement('h2');heading.textContent='Package library could not be checked';const copy=document.createElement('p');copy.textContent=error.message||'No package was changed.';const retry=document.createElement('button');retry.className='btn';retry.textContent='Try again';retry.onclick=showPackageLibrary;notice.append(heading,copy,retry);root.append(notice);return;}if(currentView!=='marketplace')return;
 root.innerHTML='<main class="catalog-workspace"><header class="project-hero"><div><span class="forge-topline">EXTEND YOUR WORKSPACE</span><h1>Package library</h1><p>Explore saved capabilities and review exactly what they request.</p></div><div class="catalog-art" aria-hidden="true"><span>◇</span><span>✳</span><span>+</span><span>↗</span></div></header><p class="memory-disclosure">Local manifest catalog. Publisher and license claims are unverified. Adding a package records permissions; package code does not run in this build.</p><div class="catalog-controls"><input class="form-control" aria-label="Search packages" placeholder="Search packages or capabilities"><select class="form-control" aria-label="Package filter"><option value="all">All packages</option><option value="installed">Added to workspace</option><option value="available">Not added</option></select><span role="status"></span></div><div class="catalog-grid"></div></main>';
 const search=root.querySelector('input'),filter=root.querySelector('select'),grid=root.querySelector('.catalog-grid');
 function render(){grid.replaceChildren();const query=search.value.toLowerCase().trim();const packages=data.available.filter(pkg=>{const added=data.installed.some(item=>item.packageId===pkg.name&&item.status==='active');return(filter.value==='all'||(filter.value==='installed'?added:!added))&&[pkg.name,pkg.description,...(pkg.capabilities||[]).map(item=>item.name)].join(' ').toLowerCase().includes(query);});root.querySelector('[role=status]').textContent=packages.length+' packages';for(const pkg of packages){const added=data.installed.some(item=>item.packageId===pkg.name&&item.status==='active');const card=document.createElement('article');card.className='catalog-card';card.innerHTML='<div class="catalog-card-head"><span class="catalog-icon" aria-hidden="true">◇</span><span class="catalog-version"></span></div><h2></h2><p></p><div class="memory-tags"></div><footer><span></span><button class="btn btn-secondary">Review package</button></footer>';card.querySelector('h2').textContent=pkg.name;card.querySelector('p').textContent=pkg.description;card.querySelector('.catalog-version').textContent='v'+pkg.version;card.querySelector('footer span').textContent=added?'Added · execution off':'Not added';for(const type of [...new Set((pkg.capabilities||[]).map(item=>item.type))]){const tag=document.createElement('span');tag.textContent=type;card.querySelector('.memory-tags').append(tag);}card.querySelector('button').onclick=()=>reviewWorkspacePackage(pkg,added);grid.append(card);}if(!packages.length){const empty=document.createElement('p');empty.className='goal-empty';empty.textContent='No packages match this view.';grid.append(empty);}}
 search.oninput=render;filter.onchange=render;render();
}
function reviewWorkspacePackage(pkg,added){
 const dialog=document.createElement('dialog');dialog.className='conversation-dialog package-dialog';dialog.innerHTML='<form method="dialog"><header><div><span class="forge-topline">PACKAGE MANIFEST</span><h2></h2></div><button class="btn btn-secondary">Close</button></header><p class="package-description"></p><p class="memory-disclosure"></p><h3>Capabilities</h3><div class="package-capabilities"></div><h3>Requested permissions</h3><div class="package-permissions"></div><details><summary>View complete manifest</summary><pre></pre></details><footer><span>Records only. No package code will execute.</span><button class="btn" type="button"></button></footer></form>';
 dialog.querySelector('h2').textContent=pkg.name;dialog.querySelector('.package-description').textContent=pkg.description;dialog.querySelector('.memory-disclosure').textContent='Publisher: '+(pkg.publisher?.name||'Unknown')+' · License: '+(pkg.license||'Not supplied')+' · These manifest claims are not verified.';dialog.querySelector('pre').textContent=JSON.stringify(pkg,null,2);
 for(const item of pkg.capabilities||[]){const row=document.createElement('section');const title=document.createElement('strong');title.textContent=item.name;const description=document.createElement('p');description.textContent=item.description;row.append(title,description);dialog.querySelector('.package-capabilities').append(row);}
 const permissions=dialog.querySelector('.package-permissions');for(const [name,value] of Object.entries(pkg.permissions||{})){const group=document.createElement('details');const title=document.createElement('summary');title.textContent=name;const pre=document.createElement('pre');pre.textContent=JSON.stringify(value,null,2);group.append(title,pre);permissions.append(group);}if(!permissions.children.length)permissions.textContent='No permissions requested in this manifest.';
 const action=dialog.querySelector('button[type=button]');action.textContent=added?'Already added':'Review & add';action.disabled=added;action.onclick=async()=>{dialog.close();await installPackage(pkg.name);};dialog.onclose=()=>dialog.remove();document.body.append(dialog);dialog.showModal();
}
`;
