/** Connection surfaces report live configuration separately from adapter implementation. */
export const connectionsClient = String.raw`
function connectionElement(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;}
function providerReadinessLabel(value){return ({REAL_INTEGRATION:'Integration implemented',PARTIAL_INTEGRATION:'Partially implemented',TEST_IMPLEMENTATION:'Test implementation',NOT_CONFIGURED:'Not configured',IMPLEMENTED_NOT_CONNECTED:'Implemented · not connected',AVAILABLE_NOT_CONNECTED:'Available · not connected',UNAVAILABLE:'Unavailable',SKELETON:'Interface only',MOCK:'Test simulator',UNIMPLEMENTED:'Planned'})[value]||String(value).replaceAll('_',' ').toLowerCase();}
function renderConnectionLoading(mode){
  const names={models:['Models & responses','Checking the saved conversation route and supported model records.'],harnesses:['AgentForge Harness','Checking the saved boundaries, review controls, and execution readiness.'],compute:['Compute & environments','Checking the local host and isolated environment records.'],tools:['Tools & capabilities','Checking the workspace capabilities and their connection state.']};
  const [title,description]=names[mode]||['Connections','Checking saved connection records.'];
  const root=connectionElement('main','connections-workspace connection-loading');root.setAttribute('aria-busy','true');root.setAttribute('aria-live','polite');
  root.innerHTML='<header class="project-hero"><div><span class="forge-topline">CONNECTIONS</span><h1>'+title+'</h1><p>'+description+'</p></div><div class="connection-illustration" aria-hidden="true"><i></i><span>✳</span><i></i></div></header><div class="connection-tabs connection-tabs-skeleton" aria-hidden="true"><span></span><span></span><span></span><span></span></div><section class="connection-skeleton-grid" aria-label="Loading connection details"><article><span></span><strong></strong><p></p><p></p></article><article><span></span><strong></strong><p></p><p></p></article><article><span></span><strong></strong><p></p><p></p></article></section><p class="connection-loading-copy">'+description+'</p>';
  return root;
}
let connectionLoadVersion=0;
async function readConnectionStatus(url){
 const controller=new AbortController();const deadline=setTimeout(()=>controller.abort(),10000);
 try{const response=await fetch(url,{signal:controller.signal});const result=await response.json();if(!response.ok)throw new Error(result.error||'Connection status request failed.');return result;}
 catch(error){if(error.name==='AbortError')throw new Error('The connection check timed out. Try again when the local service responds.');throw error;}
 finally{clearTimeout(deadline);}
}
async function showConnectionWorkspace(mode){
  const root=document.getElementById('view-content');
  const version=++connectionLoadVersion;
  const loading=renderConnectionLoading(mode);root.replaceChildren(loading);
  let chat,harness,compute,registry;
  try{
    // A compute outage must not hide the independent model setup screen.
    [chat,harness,compute,registry]=await Promise.all([
      ['models','tools'].includes(mode)?readConnectionStatus('/api/chat/status'):null,
      ['harnesses','tools'].includes(mode)?readConnectionStatus('/api/harnesses'):null,
      mode==='compute'?readConnectionStatus('/api/compute'):null,
      mode==='models'?readConnectionStatus('/api/readiness'):null
    ]);
  }catch(error){
    if(currentView!==mode||version!==connectionLoadVersion)return;
    const panel=connectionElement('section','connection-panel');panel.setAttribute('role','alert');
    panel.append(connectionElement('h1','','Connection status unavailable'),connectionElement('p','','We could not check your current setup. No configuration was changed.'),connectionElement('p','connection-limit',error instanceof Error?error.message:'The status request failed.'));
    const retry=connectionElement('button','btn btn-primary','Try again');retry.onclick=()=>showConnectionWorkspace(mode);panel.appendChild(retry);root.replaceChildren(panel);return;
  }
  if(currentView!==mode||version!==connectionLoadVersion)return;
  root.innerHTML='<main class="connections-workspace"><header class="project-hero"><div><span class="forge-topline">WORKSPACE CONTROLS</span><h1></h1><p></p></div><div class="connection-illustration" aria-hidden="true"><i></i><span>✳</span><i></i></div></header><nav class="connection-tabs" aria-label="Connection categories"></nav><section class="connection-primary"></section><section class="connection-secondary"></section></main>';
  const names={tools:['Tools & capabilities','See what this workspace can do, and which actions require a separate connection.'],models:['Models & responses','Choose how conversations receive answers. Chat configuration and autonomous execution are separate.'],harnesses:['AgentForge Harness','See what must be in place before work can run, and where to review each result.'],compute:['Compute & environments','A current snapshot of the host, with isolated environments listed separately.']};
  root.querySelector('h1').textContent=names[mode][0];root.querySelector('.project-hero p').textContent=names[mode][1];if(mode==='harnesses')root.querySelector('.forge-topline').textContent='EXECUTION CONTROLS';
  const nav=root.querySelector('.connection-tabs');for(const [view,label] of [['models','Models'],['harnesses','Harness'],['compute','Compute'],['tools','Tools']]){const button=connectionElement('button','',label);button.setAttribute('aria-current',view===mode?'page':'false');button.onclick=()=>switchView(view);nav.appendChild(button);}
  const primary=root.querySelector('.connection-primary');const secondary=root.querySelector('.connection-secondary');
  if(mode==='models'){
    const illustration=root.querySelector('.connection-illustration');
    if(illustration){
      illustration.classList.add('model-route-art');
      illustration.innerHTML='<svg viewBox="0 0 360 132" aria-hidden="true" focusable="false"><defs><linearGradient id="model-route-line" x1="0" x2="1"><stop stop-color="#c4b5fd" stop-opacity=".35"/><stop offset=".52" stop-color="#c4b5fd" stop-opacity=".75"/><stop offset="1" stop-color="#7cd4af" stop-opacity=".45"/></linearGradient><linearGradient id="model-route-input-fill" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#c4b5fd" stop-opacity=".12"/><stop offset="1" stop-color="#c4b5fd" stop-opacity="0"/></linearGradient><filter id="model-route-glow" x="-80%" y="-80%" width="260%" height="260%"><feGaussianBlur stdDeviation="5" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><path class="model-route-wire" d="M94 58h61m50 0h65"/><rect class="model-route-node model-route-input" x="8" y="34" width="86" height="48" rx="12"/><path class="model-route-copy" d="M23 49h42M23 57h54M23 66h34"/><circle class="model-route-hub" cx="180" cy="58" r="25"/><path class="model-route-spark" d="M180 43v30M165 58h30M169.4 47.4l21.2 21.2m0-21.2-21.2 21.2"/><rect class="model-route-node model-route-output" x="260" y="34" width="92" height="48" rx="12"/><circle class="model-route-endpoint" cx="277" cy="50" r="4"/><path class="model-route-copy" d="M289 50h48M276 65h61"/><text class="model-route-label" x="51" y="99" text-anchor="middle">CONVERSATION</text><text class="model-route-label" x="180" y="99" text-anchor="middle">ROUTE</text><text class="model-route-label" x="306" y="99" text-anchor="middle">MODEL</text><text class="model-route-caption" x="180" y="121" text-anchor="middle">Configure a route before conversation text is sent</text></svg>';
    }
  }
  if(mode==='tools'){
    const grid=connectionElement('div','provider-grid');
    const capabilities=[
      ['Text responses',chat.configured?'Configured':'Not configured',chat.configured?'A model route is configured. Availability is verified per response.':'Save conversations locally or configure a model route to receive replies.','models','Configure models'],
      ['Project files','Read-only browsing','Connect a folder inside a project to browse text files. Chat does not automatically receive file contents.','projects','Open projects'],
      ['Task execution',harness.runtime.canExecuteTasks?'Available':'Offline',harness.runtime.explanation,'harnesses','Inspect runtime'],
      ['Checks & evidence','Attached to tasks','Inspect saved checks and file changes. Evidence records must be reviewed; their presence alone is not success.','tasks','Review work'],
      ['Image & document analysis','Not connected','Attachments can be saved and previewed. The conversation route currently supplies text only.','messages','Open conversations'],
      ['Permissions','Managed per agent','Inspect agent policies and approvals. A saved permission does not connect an execution tool.','agents','Review agents']
    ];
    for(const [label,status,description,view,action] of capabilities){const card=connectionElement('article','provider-card');card.append(connectionElement('h2','',label),connectionElement('span','badge',status),connectionElement('p','',description));const button=connectionElement('button','btn btn-secondary',action);button.onclick=()=>switchView(view);card.append(button);grid.append(card);}primary.append(grid);
    secondary.append(connectionElement('p','connection-section-copy','Status checked '+new Date().toLocaleTimeString()+'. This view reports the current workspace; it does not grant access or start work.'));
  }else if(mode==='models'){
    const panel=connectionElement('article','connection-panel');const header=connectionElement('div','connection-panel-heading');header.append(connectionElement('h2','','Conversation route'),connectionElement('span','badge '+(chat.configured?'badge-blue':'badge-amber'),chat.configured?'Configured · not live verified':'Not configured'));panel.appendChild(header);
    panel.appendChild(connectionElement('p','',chat.configured?chat.provider+' is configured for text responses. A successful response verifies that specific request; configuration alone does not prove availability.':'Messages can be saved locally. No model receives conversation text until a route is explicitly configured and selected.'));
    const models=connectionElement('div','configured-models');for(const model of chat.models)models.appendChild(connectionElement('span','',model));if(chat.models.length)panel.appendChild(models);
    const facts=connectionElement('div','connection-facts');facts.append(connectionElement('span','','Text conversations'),connectionElement('span','','Project instructions'),connectionElement('span','','Streaming & Stop'));panel.appendChild(facts);
    panel.appendChild(connectionElement('p','connection-limit','This route has no tool or repository access. Image and document analysis are not connected.'));
    const guide=connectionElement('details','connection-guide');guide.appendChild(connectionElement('summary','','Set up a conversation provider'));guide.appendChild(connectionElement('p','','Set these server environment variables through your secret manager, then restart AgentForge. Choose the configured model in the conversation composer.'));
    const fields=connectionElement('dl','');for(const [key,description] of [['AGENTFORGE_CHAT_API_KEY','Dedicated endpoint credential; never put it in workspace records.'],['AGENTFORGE_CHAT_MODELS','Comma-separated model IDs supported by your endpoint.'],['AGENTFORGE_CHAT_BASE_URL','Optional compatible endpoint. HTTPS required except localhost.']]){fields.append(connectionElement('dt','',key),connectionElement('dd','',description));}guide.appendChild(fields);panel.appendChild(guide);
    const action=connectionElement('button','btn btn-secondary','Open conversations');action.onclick=()=>switchView('messages');panel.appendChild(action);primary.appendChild(panel);
    const modelDeveloperDetails=connectionElement('details','connection-guide model-developer-details');
    modelDeveloperDetails.append(connectionElement('summary','','Developer reference · model integrations'),connectionElement('p','connection-section-copy','Implementation maturity is for development planning. It does not mean a provider is connected or ready to run.'));
    renderProviderLibrary(modelDeveloperDetails,registry.filter(provider=>provider.category==='generative_model'));
    secondary.appendChild(modelDeveloperDetails);
    const routing=connectionElement('details','connection-panel route-inspector');routing.appendChild(connectionElement('summary','','Inspect a routing decision'));routing.appendChild(connectionElement('p','','Evaluate the routing policy using your inputs. This does not execute a model or create a task.'));
    const form=document.createElement('form');form.innerHTML='<div class="routing-fields"><label>Task type<select name="taskType" class="form-control"><option value="general_qa">Question & answer</option><option value="code_generation">Code generation</option><option value="bug_fix">Bug fix</option><option value="refactor">Refactor</option><option value="sop_compilation">Playbook compilation</option></select></label><label>Risk<select name="risk" class="form-control"><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><label>Complexity (1–10)<input class="form-control" name="complexityScore" type="number" min="1" max="10" value="5" required></label><label>Context tokens<input class="form-control" name="contextTokens" type="number" min="0" value="3000" required></label></div><button class="btn btn-secondary" type="submit">Evaluate route</button><div class="route-decision" role="status"></div>';
    form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('button');button.disabled=true;const output=form.querySelector('.route-decision');output.textContent='Evaluating…';try{const fields=new FormData(form);const result=await conversationRequest('/api/route','POST',{taskType:fields.get('taskType'),risk:fields.get('risk'),complexityScore:Number(fields.get('complexityScore')),contextTokens:Number(fields.get('contextTokens'))});output.replaceChildren();output.append(connectionElement('strong','',result.selectedTargetId?'Selected: '+result.selectedTargetId:'No route selected'),connectionElement('p','',result.rationale||'No explanation returned.'),connectionElement('small','',result.estimatedCostUsd===undefined||result.estimatedCostUsd===null?'Cost not established.':'Policy estimate: $'+result.estimatedCostUsd+'; not a measured invoice.'));}catch(error){output.textContent=error.message;}finally{button.disabled=false;}};routing.appendChild(form);secondary.appendChild(routing);
  }else if(mode==='harnesses'){
    const capabilities=harness.runtime.readiness?.capabilities||{};const gates=[['modelPlanning','Plan'],['isolatedCompute','Isolate'],['realVerification','Verify'],['evidenceCollection','Retain proof']];const readyCount=gates.filter(([key])=>capabilities[key]).length;
    const setupSteps=[
      ['modelPlanning','Plan','Check execution setup','compute','Task planning uses the execution backend; conversation model settings are separate.','Check environments'],
      ['isolatedCompute','Isolate','Check environment availability','compute','Check whether an isolated environment is available.','View status'],
      ['realVerification','Verify','Review task checks','tasks','Check the verification steps saved with a task.','View checks'],
      ['evidenceCollection','Keep proof','Review saved evidence','tasks','Inspect results attached to a task.','Review evidence']
    ];
    const nextSetup=setupSteps.find(([key])=>!capabilities[key]);
    const illustration=root.querySelector('.connection-illustration');
    if(illustration){
      const activeIndex=setupSteps.findIndex(([key])=>!capabilities[key]);
      illustration.classList.add('harness-hero-art');
      illustration.setAttribute('role','img');
      illustration.setAttribute('aria-label','Harness path: plan, isolate, verify, and keep proof. '+readyCount+' of four safeguards are ready.');
      const nodeGlyph=(key,index,shape)=>capabilities[key]?'<path class="harness-art-state" d="m-5 0 3 4 8-9"/>':activeIndex===index?shape:'<circle class="harness-art-pending" r="2.5"/>';
      const node=(key,index,x,shape)=>'<g class="harness-art-node '+(capabilities[key]?'is-ready':activeIndex===index?'is-current':'')+'" transform="translate('+x+' 35)"><circle r="17"/>'+nodeGlyph(key,index,shape)+'</g>';
      const nodes=[
        node('modelPlanning',0,40,'<path d="M0-7 7-3 0 1-7-3Z M-7 1 0 5 7 1"/>'),
        node('isolatedCompute',1,120,'<path d="M-6-5h12v10h-12z M-3-8v3m6-3v3m-6 10v3m6-3v3"/>'),
        node('realVerification',2,200,'<circle cx="-1" cy="-1" r="5"/><path d="m3 3 5 5"/>'),
        node('evidenceCollection',3,280,'<path d="M-5-7h8l4 4v10h-12z M3-7v4h4 M-2 1h6M-2 5h6"/>')
      ].join('');
      illustration.innerHTML='<svg viewBox="0 0 320 118" aria-hidden="true" focusable="false"><defs><linearGradient id="harness-line" x1="0" x2="1"><stop stop-color="#c4b5fd" stop-opacity=".8"/><stop offset="1" stop-color="#c4b5fd" stop-opacity=".2"/></linearGradient><filter id="harness-glow" x="-80%" y="-80%" width="260%" height="260%"><feGaussianBlur stdDeviation="5" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><path class="harness-art-track" d="M40 35H280"/><path class="harness-art-progress" d="M40 35H'+(activeIndex<0?280:40+activeIndex*80)+'"/>'+nodes+'<g class="harness-art-labels"><text x="40" y="76">PLAN</text><text x="120" y="76">ISOLATE</text><text x="200" y="76">VERIFY</text><text x="280" y="76">PROOF</text></g><text class="harness-art-caption" x="160" y="103" text-anchor="middle">A visible, reviewable path from intent to evidence</text></svg>';
    }
    const runtimeAvailable=Boolean(harness.runtime.canExecuteTasks);const backendConnected=Boolean(harness.runtime.status)&&harness.runtime.status!=='NOT_CONNECTED';const backendDisconnected=!backendConnected&&!runtimeAvailable;const readiness=connectionElement('section','harness-readiness'+(backendDisconnected?' is-blocked':''));const ring=connectionElement('div','harness-readiness-ring');ring.setAttribute('role','img');ring.setAttribute('aria-label',readyCount+' of '+gates.length+' execution safeguards ready');ring.style.background='conic-gradient(var(--accent) '+(readyCount/gates.length*100)+'%, var(--border) 0)';const center=connectionElement('div','');center.append(connectionElement('strong','',readyCount+'/'+gates.length),connectionElement('span','','ready'));ring.append(center);const copy=connectionElement('div','');const readinessTitle=runtimeAvailable?'Ready for a reviewed run':backendDisconnected?'Execution backend not connected':readyCount===gates.length?'Safeguards configured · runtime unavailable':readyCount===0?'Set up your execution safeguards':'Continue harness setup';const readinessMessage=backendDisconnected?(harness.runtime.explanation||'No task execution backend is connected.'):nextSetup?nextSetup[4]:runtimeAvailable?'Safeguards are available. A person still reviews each plan before it runs.':harness.runtime.explanation||'Safeguards are set up, but the execution runtime is unavailable.';copy.append(connectionElement('span','goal-kicker','Execution readiness'),connectionElement('h2','',readinessTitle),connectionElement('p','',readinessMessage),connectionElement('span','harness-next-label',backendDisconnected?'Next · Check available environments':nextSetup?'Next · '+nextSetup[2]:runtimeAvailable?'All safeguards ready · review a task':'Runtime unavailable · review the blocker'));
    const nextAction=connectionElement('button','btn btn-sm btn-primary harness-next-action',backendDisconnected?'Check environments':nextSetup?nextSetup[5]:'Review a task');nextAction.type='button';nextAction.setAttribute('aria-label',backendDisconnected?'Check available execution environments':nextSetup?'Open next step: '+nextSetup[2]:'Review a task');nextAction.onclick=()=>switchView(backendDisconnected?'compute':nextSetup?nextSetup[3]:'tasks');copy.appendChild(nextAction);
    readiness.append(ring,copy);
    const flow=connectionElement('section','harness-flow-panel');const flowHeading=connectionElement('div','harness-flow-heading');flowHeading.append(connectionElement('div','',''),connectionElement('h2','','The work path'));flowHeading.firstElementChild.append(connectionElement('span','goal-kicker','Four safeguards'),connectionElement('p','','Every run moves through the same visible checkpoints.'));const runtimeLabel=runtimeAvailable?'Ready for review':backendDisconnected?'Backend disconnected':readyCount===gates.length?'Runtime unavailable':'Setup needed';flowHeading.appendChild(connectionElement('span','badge '+(runtimeAvailable?'badge-green':'badge-amber'),runtimeLabel));flow.appendChild(flowHeading);
    const diagram=connectionElement('ol','runtime-path');diagram.setAttribute('aria-label','Execution readiness');
    const nextStep=setupSteps.findIndex(([key])=>!capabilities[key]);
    for(const [index,[key,label,action,view,description,cta]] of setupSteps.entries()){
      const ready=Boolean(capabilities[key]);const current=index===nextStep;const item=connectionElement('li',(ready?'ready ':'')+(current?'next ':'')+(backendDisconnected&&!ready?'blocked':''));
      if(current)item.setAttribute('aria-current','step');
      item.append(connectionElement('span','runtime-node',String(index+1).padStart(2,'0')),connectionElement('strong','',label),connectionElement('p','',description),connectionElement('small','',ready?'Ready':backendDisconnected?'Blocked':current?'Next step':'Not ready'));
      const actionButton=connectionElement('button','btn btn-sm '+(current?'btn-primary':'btn-secondary'),ready?'Review':cta);actionButton.setAttribute('aria-label',(ready?'Review: ':current?'Open next step: ':'Open status: ')+action);actionButton.onclick=()=>switchView(view);item.appendChild(actionButton);diagram.appendChild(item);
    }
    flow.appendChild(diagram);
    const flowNote=runtimeAvailable?'Safeguards are available. A person still reviews each plan before it runs.':backendDisconnected?'Execution is disabled until a task backend is connected. Checking these status pages does not change setup.':nextSetup?'Execution stays off until all four safeguards are ready. Next: '+nextSetup[2]+'.':harness.runtime.explanation||'All safeguards are set up, but the execution runtime is unavailable.';flow.appendChild(connectionElement('p','harness-flow-note',flowNote));
    const guide=connectionElement('details','connection-guide');guide.append(connectionElement('summary','','Technical runtime details'),connectionElement('p','','Execution is currently off until a supported environment is deliberately configured. AgentForge keeps execution disabled by default and will not run a task automatically.'));
    guide.append(connectionElement('p','connection-limit','Production gate: live container acceptance has not passed for this environment. Execution stays disabled until the selected environment and its verification path are connected and tested.'));flow.append(guide);primary.append(flow,readiness);
    
  }else{
    const environments=connectionElement('section','compute-environments');environments.appendChild(connectionElement('h2','connection-section-title','Isolated environments'));const grid=connectionElement('div','provider-grid');for(const [key,name] of [['local','Local sandbox'],['docker','Docker'],['e2b','Cloud sandbox']]){const card=connectionElement('article','provider-card');card.append(connectionElement('span','provider-glyph','□'),connectionElement('h3','',name),connectionElement('span','badge badge-amber',providerReadinessLabel(compute.sandboxes[key])),connectionElement('p','',compute.sandboxDetails?.[key]||'Availability has not been checked.'));grid.appendChild(card);}environments.append(grid,connectionElement('p','connection-section-copy',compute.worktrees.strategy));primary.appendChild(environments);
    const host=compute.hostTelemetry;secondary.appendChild(connectionElement('h2','connection-section-title','Host resources'));const stats=connectionElement('div','compute-stat-grid');
    for(const [label,value,detail] of [['Host memory',host?((host.usedMemoryBytes/1073741824).toFixed(1)+' / '+(host.totalMemoryBytes/1073741824).toFixed(1)+' GB'):'Unavailable','Whole host usage; not an agent allocation'],['Logical CPUs',host?String(host.cpuCount):'Unavailable',host?host.platform+' · '+host.architecture:'Host telemetry unavailable'],['Tracked worktrees',String(compute.worktrees.trackedCount),compute.worktrees.runtimeVerified?'Runtime verified':'Record count only'],['Active sandboxes',host?String(host.activeSandboxesCount):'Unavailable','Reported by the local control plane']]){const card=connectionElement('article','compute-stat');card.append(connectionElement('h2','',label),connectionElement('strong','',value),connectionElement('p','',detail));stats.appendChild(card);}secondary.appendChild(stats);
    if(host){const memory=connectionElement('div','host-memory-bar');memory.setAttribute('role','meter');memory.setAttribute('aria-label','Host memory used');memory.setAttribute('aria-valuemin','0');memory.setAttribute('aria-valuemax','100');memory.setAttribute('aria-valuenow',String(host.memoryUsagePercent));const used=connectionElement('span','');used.style.width=Math.max(0,Math.min(100,host.memoryUsagePercent))+'%';memory.appendChild(used);secondary.appendChild(memory);secondary.appendChild(connectionElement('p','connection-section-copy','Host memory sampled when this page loaded · '+host.memoryUsagePercent+'% used.'));}
  }
  const refresh=connectionElement('button','btn btn-sm btn-secondary connection-refresh','Refresh status');refresh.onclick=()=>showConnectionWorkspace(mode).catch(error=>showToast(error.message));root.querySelector('.connection-tabs').appendChild(refresh);
}
function renderProviderLibrary(root,providers){
  const grid=connectionElement('div','provider-grid');
  for(const provider of providers){const card=connectionElement('article','provider-card');card.append(connectionElement('span','provider-glyph',provider.category==='harness'?'⌘':'✳'),connectionElement('h3','',provider.name),connectionElement('span','badge badge-blue',providerReadinessLabel(provider.readiness)),connectionElement('p','',provider.summary));const details=connectionElement('details','');details.append(connectionElement('summary','','Implementation details'),connectionElement('p','',provider.notes||'No additional notes.'));if(provider.capabilities){for(const capability of provider.capabilities)details.appendChild(connectionElement('p','',capability.capability.replaceAll('_',' ')+': '+providerReadinessLabel(capability.readiness)));}card.appendChild(details);grid.appendChild(card);}root.appendChild(grid);
}
`;
