/** Conversation workspace uses canonical threads; never invents model responses. */
export const conversationClient = String.raw`
let conversationState = { threads: [], channels: [], projects: [], agents: [], selected: null, archived: false, query: '', projectId: null };
try{conversationState.selected=localStorage.getItem('agentforge-active-conversation');}catch{}
let conversationLoad = 0;
let conversationSelectionLoad = 0;
const conversationReadingPositions = new Map();
let conversationSearchResults=null, conversationSearchVersion=0, conversationSearchTimer;
const conversationDraftMedia = new Map();
const pendingConversationSends = new Set();
const conversationDraftReplies = new Map();
let conversationSendShortcut='enter';
try{if(localStorage.getItem('agentforge-send-shortcut')==='modifier-enter')conversationSendShortcut='modifier-enter';}catch{}
function conversationShortcutHint(){return conversationSendShortcut==='modifier-enter'?'Ctrl / ⌘ + Enter to send · Enter for a new line':'Enter to send · Shift + Enter for a new line';}
async function conversationRequest(url, method, body) {
  const response = await fetch(url, { method: method || 'GET', headers: {'Content-Type':'application/json'}, ...(body ? {body:JSON.stringify(body)} : {}) });
  const result = await response.json();
  if (!response.ok) throw new Error(result.error || 'Request failed');
  return result;
}
function renderConversationLoading(root){
 root.innerHTML='<section class="conversation-workspace conversation-workspace-loading" aria-busy="true" aria-live="polite"><aside class="conversation-list"><div class="conversation-list-head"><h2>Conversations</h2><i></i></div><span></span><span></span><span></span><div class="conversation-list-skeleton"><article><i></i><strong></strong><small></small></article><article><i></i><strong></strong><small></small></article><article><i></i><strong></strong><small></small></article></div></aside><section class="conversation-stage"><div class="conversation-stage-skeleton"><span class="goal-kicker">YOUR WORKSPACE, LOADING</span><strong></strong><p></p><p></p><div><i></i><i></i><i></i></div></div></section></section>';
}
function renderConversationStageLoading(stage){
 stage.innerHTML='<div class="conversation-thread-skeleton" aria-busy="true" aria-live="polite"><header><i></i><div><strong></strong><span></span></div></header><section><article><i></i><div><strong></strong><span></span><span></span></div></article><article><i></i><div><strong></strong><span></span></div></article></section><footer><span></span><i></i></footer></div>';
}
function renderConversationStageError(stage,message,retry){
 stage.replaceChildren();const panel=document.createElement('section');panel.className='conversation-stage-notice';panel.setAttribute('role','alert');const heading=document.createElement('h2');heading.textContent='This conversation could not be opened';const copy=document.createElement('p');copy.textContent=message||'Your saved conversation has not changed.';const button=document.createElement('button');button.type='button';button.className='btn btn-secondary';button.textContent='Try again';button.onclick=retry;panel.append(heading,copy,button);stage.append(panel);
}
async function showConversations() {
  const generation = ++conversationLoad;
  const content=document.getElementById('view-content');const existing=content.querySelector('.conversation-workspace');if(existing)existing.setAttribute('aria-busy','true');else renderConversationLoading(content);
  let threads,channels,projects,agents;
  try{[threads,channels,projects,agents]=await Promise.all([conversationRequest('/api/threads'),conversationRequest('/api/channels'),conversationRequest('/api/projects'),conversationRequest('/api/agents').catch(()=>[])]);}
  catch(error){
    if(generation!==conversationLoad||currentView!=='messages')return;
    // Preserve an open composer and its unsent files if a refresh fails.
    if(existing)existing.removeAttribute('aria-busy');
    const panel=document.createElement('section');panel.className='conversation-load-error';panel.setAttribute('role','alert');
    const description=document.createElement('p');description.textContent=existing?'Could not refresh conversations. Your open conversation and draft are preserved.':'Could not load conversations. Your saved messages have not been changed.';
    const retry=document.createElement('button');retry.className='btn btn-secondary';retry.textContent='Try again';retry.onclick=()=>{retry.disabled=true;showConversations();};panel.append(description,retry);
    content.querySelector('.conversation-load-error')?.remove();if(existing)content.prepend(panel);else content.replaceChildren(panel);return;
  }
  if(generation !== conversationLoad || currentView !== 'messages') return;
  conversationState.threads = threads; conversationState.channels = channels; conversationState.projects = projects; conversationState.agents = agents;
  const hasConversationDestination=channels.some(channel=>!channel.archived);
  const emptyStage=hasConversationDestination
    ? '<div class="conversation-empty"><div class="conversation-empty-art" aria-hidden="true"><svg viewBox="0 0 460 170"><defs><linearGradient id="conversation-stroke" x1="0" x2="1"><stop stop-color="#7cd4af"/><stop offset=".52" stop-color="#c4b5fd"/><stop offset="1" stop-color="#e9bc77"/></linearGradient><radialGradient id="conversation-halo"><stop stop-color="#c4b5fd" stop-opacity=".17"/><stop offset="1" stop-color="#c4b5fd" stop-opacity="0"/></radialGradient></defs><ellipse cx="230" cy="92" rx="207" ry="77" fill="url(#conversation-halo)"/><path d="M117 93h94m38 0h94" stroke="url(#conversation-stroke)" stroke-width="2" stroke-dasharray="4 7"/><rect x="44" y="46" width="130" height="91" rx="15" fill="#202126" stroke="#7cd4af" stroke-opacity=".55"/><path d="M61 66h71M61 80h96M61 94h78" stroke="#7cd4af" stroke-opacity=".72" stroke-width="3" stroke-linecap="round"/><circle cx="63" cy="116" r="5" fill="#7cd4af"/><path d="M77 116h48" stroke="#7cd4af" stroke-opacity=".45" stroke-width="3" stroke-linecap="round"/><rect x="165" y="25" width="130" height="112" rx="18" fill="#23232a" stroke="#c4b5fd" stroke-opacity=".7"/><circle cx="191" cy="51" r="9" fill="#c4b5fd" fill-opacity=".22" stroke="#c4b5fd"/><path d="M210 48h60M184 75h92M184 89h79" stroke="#c4b5fd" stroke-opacity=".72" stroke-width="3" stroke-linecap="round"/><rect x="286" y="48" width="130" height="89" rx="15" fill="#25231f" stroke="#e9bc77" stroke-opacity=".58"/><path d="M304 69h78M304 83h95M304 97h56" stroke="#e9bc77" stroke-opacity=".68" stroke-width="3" stroke-linecap="round"/><circle cx="397" cy="117" r="4" fill="#e9bc77"/></svg></div><h1>A place to think. A space to build.</h1><p>Keep each project’s conversations, decisions, and context together.</p><button class="btn" id="start-conversation">Start a conversation</button><div class="conversation-starters" aria-label="Conversation starters"><button type="button" data-title="Plan a project"><svg viewBox="0 0 28 28" aria-hidden="true"><path d="M6 7h16M6 14h10M6 21h7"/><circle cx="20" cy="19" r="4"/></svg><span class="conversation-starter-copy"><b>Plan a project</b><small>Turn an outcome into a clear working conversation.</small></span><i aria-hidden="true">→</i></button><button type="button" data-title="Review a change"><svg viewBox="0 0 28 28" aria-hidden="true"><path d="m5 14 6 6L23 7"/><path d="M21 16v6H5V6h12"/></svg><span class="conversation-starter-copy"><b>Review a change</b><small>Capture the question, evidence, and decision together.</small></span><i aria-hidden="true">→</i></button><button type="button" data-title="Research an idea"><svg viewBox="0 0 28 28" aria-hidden="true"><circle cx="12" cy="12" r="7"/><path d="m17 17 6 6M9 12h6M12 9v6"/></svg><span class="conversation-starter-copy"><b>Research an idea</b><small>Collect context before you decide what to build.</small></span><i aria-hidden="true">→</i></button></div><small>Messages save locally. Connect a model route when you want AI replies.</small></div>'
    : '<div class="conversation-empty conversation-empty-first-run"><div class="conversation-empty-art conversation-project-art" aria-hidden="true"><svg viewBox="0 0 300 166"><defs><linearGradient id="project-stroke" x1="0" x2="1"><stop stop-color="#7cd4af"/><stop offset="1" stop-color="#c4b5fd"/></linearGradient></defs><rect x="38" y="27" width="224" height="119" rx="17" fill="#202126" stroke="#c4b5fd" stroke-opacity=".48"/><path d="M38 59h224" stroke="#c4b5fd" stroke-opacity=".35"/><circle cx="58" cy="43" r="4" fill="#7cd4af"/><circle cx="73" cy="43" r="4" fill="#c4b5fd"/><circle cx="88" cy="43" r="4" fill="#e9bc77"/><rect x="58" y="78" width="92" height="48" rx="9" fill="#7cd4af" fill-opacity=".1" stroke="#7cd4af" stroke-opacity=".44"/><path d="M73 94h52M73 107h36" stroke="#7cd4af" stroke-width="3" stroke-linecap="round"/><rect x="164" y="78" width="78" height="20" rx="7" fill="#c4b5fd" fill-opacity=".1" stroke="#c4b5fd" stroke-opacity=".4"/><path d="M179 88h46" stroke="url(#project-stroke)" stroke-width="3" stroke-linecap="round"/><rect x="164" y="106" width="78" height="20" rx="7" fill="#e9bc77" fill-opacity=".08" stroke="#e9bc77" stroke-opacity=".4"/><path d="M179 116h37" stroke="#e9bc77" stroke-opacity=".72" stroke-width="3" stroke-linecap="round"/></svg></div><span class="goal-kicker">First step</span><h1>Start with a project.</h1><p>Projects keep conversations, files, and decisions together. Create one when you are ready to begin.</p><button class="btn" id="create-first-project">Create your first project</button><small>Nothing is preloaded into this workspace. You choose what to connect and where work lives.</small></div>';
  content.innerHTML = '<div class="conversation-workspace"><aside class="conversation-list" id="conversation-sidebar" aria-label="Conversation browser"><div class="conversation-list-head"><h2>Conversations</h2><button class="btn btn-sm" id="new-conversation">+ New</button></div><select class="form-control" id="conversation-project" aria-label="Project filter"></select><input class="form-control" id="conversation-filter" aria-label="Search conversations" placeholder="Search titles and messages…" maxlength="200"><label class="conversation-archive-filter"><input type="checkbox" id="show-archived"> Show archived</label><div id="conversation-list-items"></div></aside><section class="conversation-stage" id="conversation-stage">'+emptyStage+'</section></div>';
  // Do not pass the click event as the optional starter title.
  document.getElementById('new-conversation').onclick = () => openConversationCreate();
  document.getElementById('start-conversation')?.addEventListener('click', () => openConversationCreate());
  document.getElementById('create-first-project')?.addEventListener('click', () => switchView('projects'));
  content.querySelectorAll('.conversation-starters button').forEach(button=>button.onclick=()=>openConversationCreate(button.dataset.title));
  const filter = document.getElementById('conversation-filter'); filter.value = conversationState.query;
  filter.oninput = () => { conversationState.query = filter.value; searchConversations(); };
  const archived = document.getElementById('show-archived'); archived.checked = conversationState.archived;
  archived.onchange = () => { conversationState.archived = archived.checked; renderConversationList(); };
  const projectSelect=document.getElementById('conversation-project');
  const allOption=document.createElement('option');allOption.value='';allOption.textContent='All projects';projectSelect.appendChild(allOption);
  if(generation!==conversationLoad || !projectSelect.isConnected || currentView!=='messages')return;
  for(const project of projects.filter(p=>!p.archived)){const option=document.createElement('option');option.value=project.id;option.textContent=project.name;projectSelect.appendChild(option);}
  const activeProjectId=typeof projectState!=='undefined'&&projectState.selected?projectState.selected:null;
  if(activeProjectId&&projects.some(project=>project.id===activeProjectId&&!project.archived))conversationState.projectId=activeProjectId;
  if(conversationState.projectId&&!projects.some(project=>project.id===conversationState.projectId&&!project.archived))conversationState.projectId=null;
  projectSelect.value=conversationState.projectId||'';
  projectSelect.onchange=()=>{conversationState.projectId=projectSelect.value||null;conversationState.selected=null;if(typeof projectState!=='undefined'){projectState.selected=conversationState.projectId;projectState.tab='overview';saveProjectNavigation();refreshWorkspaceProjectLabel();}showConversations();};
  if(conversationState.query.trim())searchConversations();else renderConversationList();
  if(conversationState.selected && threads.some(t => t.id === conversationState.selected)) await selectConversation(conversationState.selected);
}
function searchConversations(){
 clearTimeout(conversationSearchTimer);const version=++conversationSearchVersion,query=conversationState.query.trim();conversationSearchResults=null;
 if(!query){renderConversationList();return;}
 const root=document.getElementById('conversation-list-items');if(root)root.textContent='Searching conversations…';
 conversationSearchTimer=setTimeout(async()=>{try{const results=await conversationRequest('/api/threads?q='+encodeURIComponent(query));if(version!==conversationSearchVersion||currentView!=='messages')return;conversationSearchResults=results;renderConversationList();}catch(error){if(version===conversationSearchVersion&&root?.isConnected)root.textContent='Search unavailable: '+error.message;}},200);
}
function renderConversationList() {
  const root = document.getElementById('conversation-list-items'); if(!root) return; root.replaceChildren();
  const rows = (conversationState.query.trim()&&conversationSearchResults!==null?conversationSearchResults:conversationState.threads).filter(t => Boolean(t.archived) === conversationState.archived && (!conversationState.projectId || conversationState.channels.find(c=>c.id===t.channelId)?.spaceId===conversationState.projectId) && (conversationSearchResults!==null || (t.title || '').toLowerCase().includes(conversationState.query.toLowerCase())));
  const today=new Date();today.setHours(0,0,0,0);const week=new Date(today);week.setDate(week.getDate()-7);
  const groups=new Map();for(const thread of rows){const updated=new Date(thread.updatedAt);const key=thread.pinned?'Pinned':updated>=today?'Today':updated>=week?'Previous 7 days':'Earlier';if(!groups.has(key))groups.set(key,[]);groups.get(key).push(thread);}
  for(const name of ['Pinned','Today','Previous 7 days','Earlier']){const group=groups.get(name);if(!group)continue;const heading=document.createElement('h3');heading.className='conversation-group-heading';heading.textContent=name;root.append(heading);
  for(const thread of group) {
    const button = document.createElement('button'); button.className = 'conversation-row' + (conversationState.selected === thread.id ? ' selected' : '');
    if(conversationState.selected===thread.id)button.setAttribute('aria-current','true');
    const title = document.createElement('strong'); title.textContent = (thread.pinned ? '★ ' : '') + (thread.title || 'Untitled conversation');
    const channel=conversationState.channels.find(c=>c.id===thread.channelId);const project=conversationState.projects.find(p=>p.id===channel?.spaceId);
    const updated=new Date(thread.updatedAt);const updatedLabel=updated.toDateString()===new Date().toDateString()?updated.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):updated.toLocaleDateString([],{month:'short',day:'numeric'});
    const detail = document.createElement('span');detail.className='conversation-context';detail.textContent=(project?.name?project.name+' / ':'')+(channel?.name||'Project')+' · '+updatedLabel;
    button.append(title,detail);
    if(thread.lastMessagePreview){const preview=document.createElement('span');preview.className='conversation-preview';const message=thread.lastMessagePreview;const text=(message.content||'').replace(/\s+/g,' ').trim();const author=message.authorType==='user'?'You':message.authorType==='agent'?'Agent':'Workspace';preview.textContent=text?author+': '+text:(message.attachmentCount?author+' shared '+message.attachmentCount+' attachment'+(message.attachmentCount===1?'':'s'):'Conversation updated');button.append(preview);}
    if(thread.searchHit){const excerpt=document.createElement('span');excerpt.className='conversation-search-excerpt';excerpt.textContent=thread.searchHit.excerpt;button.append(excerpt);} button.onclick = async () => {await selectConversation(thread.id);if(thread.searchHit&&conversationState.selected===thread.id){const node=Array.from(document.querySelectorAll('#conversation-feed [data-message-id]')).find(item=>item.dataset.messageId===thread.searchHit.messageId);if(node){node.classList.add('search-match');node.scrollIntoView({block:'center'});}}}; root.appendChild(button);
  }
  }
  const isInitialEmpty=!rows.length&&!conversationState.query.trim()&&!conversationState.archived;
  root.closest('.conversation-workspace')?.classList.toggle('conversation-empty-list',isInitialEmpty);
  if(!rows.length) {const empty=document.createElement('p');empty.className='conversation-list-empty';empty.textContent=conversationState.query.trim()?'No matching conversations.':'No conversations here yet.';root.appendChild(empty);}
}
function openConversationCreate(initialTitle='') {
  const projects=conversationState.projects.filter(project=>!project.archived);
  if(!projects.length){
    switchView('projects');
    showToast('Create a project first, then start its first conversation.');
    return;
  }
  const dialog = document.createElement('dialog'); dialog.className='conversation-dialog';
  dialog.innerHTML='<form><h2>New conversation</h2><label>Title<input name="title" required maxlength="200" class="form-control" placeholder="What are you working on?"></label><label>Project<select name="project" class="form-control" required></select></label><label>Channel<select name="channel" class="form-control" required disabled></select></label><p class="conversation-feedback" role="status" aria-live="polite"></p><footer><button type="button" class="btn btn-secondary" data-create-channel hidden>Add a General channel</button><button type="button" class="btn btn-secondary">Cancel</button><button type="submit" class="btn">Create conversation</button></footer></form>';
  const projectSelect=dialog.querySelector('[name=project]');
  const channelSelect=dialog.querySelector('[name=channel]');
  const feedback=dialog.querySelector('.conversation-feedback');
  const submit=dialog.querySelector('button[type=submit]');
  const createChannel=dialog.querySelector('[data-create-channel]');
  const chooseProject=document.createElement('option');chooseProject.value='';chooseProject.textContent='Choose a project';projectSelect.append(chooseProject);
  for(const project of projects){const option=document.createElement('option');option.value=project.id;option.textContent=project.name;projectSelect.append(option);}
  const preferredProject=conversationState.projectId||((typeof projectState!=='undefined'&&projectState.selected)?projectState.selected:null);
  projectSelect.value=projects.some(project=>project.id===preferredProject)?preferredProject:(projects.length===1?projects[0].id:'');
  const updateChannels=()=>{
    channelSelect.replaceChildren();
    const available=conversationState.channels.filter(channel=>!channel.archived&&channel.spaceId===projectSelect.value);
    for(const channel of available){const option=document.createElement('option');option.value=channel.id;option.textContent=channel.name;channelSelect.append(option);}
    channelSelect.disabled=available.length===0;
    submit.disabled=available.length===0;
    createChannel.hidden=available.length>0||!projectSelect.value;
    feedback.textContent=available.length?'Choose the channel for this project.':'This project has no active channel yet. Add a General channel to start a conversation here.';
  };
  projectSelect.onchange=updateChannels;
  createChannel.onclick=async()=>{const project=projects.find(item=>item.id===projectSelect.value);if(!project)return;createChannel.disabled=true;createChannel.textContent='Adding channel…';try{const channel=await conversationRequest('/api/channels','POST',{workspaceId:project.workspaceId,spaceId:project.id,name:'General',provider:'agentforge',visibility:'private'});conversationState.channels.push(channel);updateChannels();feedback.textContent='General is ready. Choose it, then create your conversation.';}catch(error){feedback.textContent=error.message||'Could not add a channel to this project.';}finally{createChannel.disabled=false;createChannel.textContent='Add a General channel';}};
  updateChannels();
  dialog.querySelector('input').value=initialTitle;dialog.querySelector('button[type=button]:not([data-create-channel])').onclick=()=>dialog.close();
  dialog.addEventListener('close',()=>dialog.remove(),{once:true});
  dialog.querySelector('form').onsubmit=async event=>{ event.preventDefault(); const button=dialog.querySelector('button[type=submit]');button.disabled=true;
    try {const thread=await conversationRequest('/api/threads','POST',{title:dialog.querySelector('input').value,channelId:channelSelect.value});conversationState.selected=thread.id;conversationState.archived=false;dialog.close();await showConversations();}
    catch(error){feedback.textContent=error.message;button.disabled=false;}
  };
  document.body.appendChild(dialog);dialog.showModal();dialog.querySelector('input').focus();
}
async function selectConversation(id,options={}) {
  const selectionLoad=++conversationSelectionLoad;
  conversationState.selected=id;try{localStorage.setItem('agentforge-active-conversation',id);}catch{} renderConversationList();
  let thread=conversationState.threads.find(t=>t.id===id);
  if(!thread){try{const threads=await conversationRequest('/api/threads');if(selectionLoad!==conversationSelectionLoad||currentView!=='messages')return;conversationState.threads=threads;thread=threads.find(t=>t.id===id);}catch{const stage=document.getElementById('conversation-stage');if(selectionLoad===conversationSelectionLoad&&currentView==='messages'&&stage)renderConversationStageError(stage,'The saved conversation list could not be refreshed.',()=>selectConversation(id));return;}}
  if(!thread)return;
  const projectId=conversationState.channels.find(c=>c.id===thread.channelId)?.spaceId||null;
  if(conversationState.projectId!==projectId){conversationState.projectId=projectId;const projectFilter=document.getElementById('conversation-project');if(projectFilter)projectFilter.value=projectId||'';}
  if(typeof projectState!=='undefined'&&projectState.selected!==projectId){projectState.selected=projectId;projectState.tab='overview';saveProjectNavigation();refreshWorkspaceProjectLabel();}
  conversationState.archived=Boolean(thread.archived);document.getElementById('show-archived').checked=conversationState.archived;renderConversationList();
  const stage=document.getElementById('conversation-stage');renderConversationStageLoading(stage);
  stage.closest('.conversation-workspace').classList.add('has-conversation');
  let messages;try{messages=await conversationRequest('/api/threads/'+encodeURIComponent(id)+'/messages');}catch(error){if(selectionLoad===conversationSelectionLoad&&stage.isConnected)renderConversationStageError(stage,error.message,()=>selectConversation(id));return;}
  let draftStorageFailed=false;
  if(!conversationDraftMedia.has(id)){try{const draft=await loadDraftExtras(id);if(draft){conversationDraftMedia.set(id,Array.isArray(draft.attachments)?draft.attachments:[]);if(draft.replyTo)conversationDraftReplies.set(id,draft.replyTo);}}catch{draftStorageFailed=true;}}
  if(selectionLoad!==conversationSelectionLoad || conversationState.selected!==id || !stage.isConnected)return;
  stage.innerHTML='<header class="conversation-toolbar"><input id="conversation-title" aria-label="Conversation title" maxlength="200"><div class="conversation-header-actions"><details class="conversation-more"><summary class="btn btn-sm btn-secondary" role="button" aria-label="More conversation actions" aria-expanded="false" aria-controls="conversation-more-actions">More</summary><div class="conversation-more-actions" id="conversation-more-actions" role="group" aria-label="Conversation actions"><button class="btn btn-sm btn-secondary" id="conversation-rename" aria-label="Save conversation title">Save title</button><button class="btn btn-sm btn-secondary" id="conversation-pin"></button><button class="btn btn-sm btn-secondary" id="conversation-export" aria-label="Export conversation">Export</button><button class="btn btn-sm btn-secondary" id="conversation-archive"></button></div></details></div></header><details class="conversation-context"><summary>Project context</summary><div id="conversation-context"></div></details><div class="conversation-feed" id="conversation-feed"></div><form class="conversation-composer"><div class="composer-reply" hidden></div><div class="composer-attachments"></div><input type="file" multiple hidden accept="image/png,image/jpeg,image/webp,application/pdf,text/plain,.md,.csv,.json"><textarea aria-label="Message" placeholder="Write a message…" maxlength="40000"></textarea><div><button type="button" data-attach class="btn btn-sm btn-secondary" title="Attach files or drop them here">+ Attach</button><span class="conversation-composer-status">Checking response route…</span><div class="conversation-send-actions"><button type="button" data-send-shortcut class="btn btn-sm btn-secondary conversation-send-shortcut"></button><button type="submit" class="btn">Send ↑</button></div></div><p class="conversation-feedback" aria-live="polite"></p></form>';
  document.getElementById('conversation-title').value=thread.title || '';
  const workspace=stage.closest('.conversation-workspace');
  const inspector=document.createElement('aside');inspector.className='conversation-inspector';inspector.id='conversation-inspector';inspector.hidden=true;inspector.setAttribute('aria-label','Conversation details');inspector.innerHTML='<header><div><span class="goal-kicker">Conversation details</span><h2>Context and provenance</h2></div><button class="btn btn-sm btn-secondary" type="button" data-close aria-label="Close conversation details">×</button></header><div class="conversation-inspector-body"><p class="memory-disclosure">Checking saved conversation context…</p></div>';
  const projectContext=stage.querySelector('.conversation-context');const projectContextSummary=projectContext?.querySelector('summary');if(projectContextSummary)projectContextSummary.textContent='Project instructions';if(projectContext)inspector.querySelector('.conversation-inspector-body').append(projectContext);
  workspace.append(inspector);
  const detailsToggle=document.createElement('button');detailsToggle.type='button';detailsToggle.className='btn btn-sm btn-secondary conversation-details-toggle';detailsToggle.textContent='Details';detailsToggle.setAttribute('aria-controls','conversation-inspector');
  const applyInspector=opened=>{workspace.classList.toggle('conversation-inspector-open',opened);inspector.hidden=!opened;detailsToggle.setAttribute('aria-expanded',String(opened));detailsToggle.textContent=opened?'Hide details':'Details';};applyInspector(false);detailsToggle.onclick=()=>applyInspector(!workspace.classList.contains('conversation-inspector-open'));inspector.querySelector('[data-close]').onclick=()=>{applyInspector(false);detailsToggle.focus();};
  const focusToggle=document.createElement('button');focusToggle.type='button';focusToggle.className='btn btn-sm btn-secondary conversation-focus-toggle';focusToggle.setAttribute('aria-controls','conversation-sidebar');
  const applyFocus=focused=>{workspace.classList.toggle('conversation-focused',focused);focusToggle.textContent=focused?'Show conversations':'Focus chat';focusToggle.setAttribute('aria-expanded',String(!focused));focusToggle.title=focused?'Show conversation navigation':'Give this conversation more room';};
  let focused=false;try{focused=localStorage.getItem('agentforge-focus-chat')==='true';}catch{}applyFocus(focused);
  focusToggle.onclick=()=>{const next=!workspace.classList.contains('conversation-focused');applyFocus(next);try{localStorage.setItem('agentforge-focus-chat',String(next));}catch{}};
  const headerTools=document.createElement('div');headerTools.className='conversation-header-tools';headerTools.setAttribute('aria-label','Conversation view options');headerTools.append(detailsToggle,focusToggle);stage.querySelector('.conversation-toolbar').prepend(headerTools);
  const back=document.createElement('button');back.className='conversation-back';back.textContent='← Conversations';back.type='button';back.onclick=()=>{stage.closest('.conversation-workspace').classList.remove('has-conversation');document.getElementById('conversation-filter').focus();};stage.prepend(back);
  const channel=conversationState.channels.find(c=>c.id===thread.channelId);
  Promise.resolve().then(async()=>{const project=conversationState.projects.find(p=>p.id===channel?.spaceId);const target=inspector.querySelector('#conversation-context');if(!target||!stage.isConnected||conversationState.selected!==id)return;const headerMeta=stage.querySelector('.conversation-title-meta');const channelMeta=headerMeta?.querySelector('.conversation-thread-context');if(channelMeta)channelMeta.textContent=(channel?.name||'Project conversation')+' · '+messages.length+' '+(messages.length===1?'message':'messages');target.textContent=project?((project.name||'Project')+'\n\n'+(project.instructions||'No project instructions saved.')+(project.repositoryPath?'\n\nA local repository reference is saved for this project.':'')):'No project context available.';
    const body=inspector.querySelector('.conversation-inspector-body');if(!body||!inspector.isConnected||conversationState.selected!==id)return;body.replaceChildren();const facts=[['Conversation',thread.title||'Untitled conversation'],['Messages',String(messages.length)+' saved message'+(messages.length===1?'':'s')],['Attachments',String(messages.reduce((count,message)=>count+(message.attachments?.length||0),0))+' saved file'+(messages.reduce((count,message)=>count+(message.attachments?.length||0),0)===1?'':'s')],['Channel',channel?.name||'Not recorded'],['Project',project?.name||'No linked project']];for(const [label,value] of facts){const row=document.createElement('div');row.className='conversation-inspector-fact';const name=document.createElement('span');name.textContent=label;const detail=document.createElement('strong');detail.textContent=value;row.append(name,detail);body.append(row);}if(projectContext)body.append(projectContext);const guidance=document.createElement('p');guidance.className='memory-disclosure';guidance.textContent=project?'Project instructions are provided only when a configured chat route generates a response. Files are not automatically shared with chat.':'This conversation has no linked project context.';body.append(guidance);if(project){const open=document.createElement('button');open.type='button';open.className='btn btn-secondary';open.textContent='Open project';open.onclick=()=>{projectState.selected=project.id;switchView('projects');};body.append(open);}try{const status=await conversationRequest('/api/chat/status');if(!body.isConnected||conversationState.selected!==id)return;const headerRoute=stage.querySelector('.conversation-route-state');if(headerRoute){headerRoute.dataset.state=status.configured?'ready':'local';headerRoute.textContent=status.configured?'Response route ready · '+status.models.length+' model'+(status.models.length===1?'':'s'):'Saved locally · connect a response route';}const route=document.createElement('div');route.className='conversation-inspector-fact';const name=document.createElement('span');name.textContent='Response route';const detail=document.createElement('strong');detail.textContent=status.configured?status.models.length+' configured model'+(status.models.length===1?'':'s'):'Not configured';route.append(name,detail);body.prepend(route);}catch{const headerRoute=stage.querySelector('.conversation-route-state');if(headerRoute){headerRoute.dataset.state='unavailable';headerRoute.textContent='Response-route status unavailable';}const route=document.createElement('p');route.className='memory-disclosure';route.textContent='Response-route status could not be checked. Messages can still be saved locally.';body.prepend(route);}
  }).catch(()=>{const target=inspector.querySelector('#conversation-context');if(target&&stage.isConnected&&conversationState.selected===id&&selectionLoad===conversationSelectionLoad)target.textContent='Project context could not be loaded.';const body=inspector.querySelector('.conversation-inspector-body');if(body&&inspector.isConnected&&conversationState.selected===id)body.textContent='Conversation details could not be loaded. You can continue using the saved transcript.';});
  const update=async changes=>{try{await conversationRequest('/api/threads/'+id,'PATCH',changes);await showConversations();}catch(error){stage.querySelector('.conversation-feedback').textContent=error.message;}};
  const titleInput=document.getElementById('conversation-title');
  // Keep the project and transcript scope visible without implying a live agent is connected.
  const titleStack=document.createElement('div');titleStack.className='conversation-title-stack';
  const threadMark=document.createElement('span');threadMark.className='conversation-thread-mark';threadMark.setAttribute('aria-hidden','true');threadMark.innerHTML='<svg viewBox="0 0 40 40" fill="none"><defs><linearGradient id="thread-mark" x1="6" y1="6" x2="34" y2="34"><stop stop-color="#7cd4af"/><stop offset=".52" stop-color="#c4b5fd"/><stop offset="1" stop-color="#e9bc77"/></linearGradient></defs><path d="M9 13.5A4.5 4.5 0 0 1 13.5 9h13A4.5 4.5 0 0 1 31 13.5v7a4.5 4.5 0 0 1-4.5 4.5H19l-6 5v-5.4a4.5 4.5 0 0 1-4-4.6v-6.5Z" stroke="url(#thread-mark)" stroke-width="1.7" stroke-linejoin="round"/><path d="M15 16h10M15 20h6" stroke="url(#thread-mark)" stroke-width="1.6" stroke-linecap="round"/><circle cx="29" cy="29" r="4" fill="#18191c" stroke="#e9bc77" stroke-width="1.5"/><path d="M29 26.8v4.4M26.8 29h4.4" stroke="#e9bc77" stroke-width="1.2" stroke-linecap="round"/></svg>';
  const titleMeta=document.createElement('div');titleMeta.className='conversation-title-meta';
  const linkedProject=conversationState.projects.find(project=>project.id===channel?.spaceId);
  const projectCrumb=document.createElement('button');projectCrumb.type='button';projectCrumb.className='conversation-project-crumb';projectCrumb.textContent=linkedProject?.name||'No linked project';projectCrumb.disabled=!linkedProject;projectCrumb.setAttribute('aria-label',linkedProject?'Open project '+linkedProject.name:'No linked project');projectCrumb.onclick=()=>{if(!linkedProject)return;projectState.selected=linkedProject.id;projectState.tab='overview';saveProjectNavigation();refreshWorkspaceProjectLabel();switchView('projects');};
  const channelMeta=document.createElement('span');channelMeta.className='conversation-thread-context';channelMeta.textContent=(channel?.name||'Project conversation')+' · '+messages.length+' '+(messages.length===1?'message':'messages');
  titleMeta.append(projectCrumb,channelMeta);
  const routeState=document.createElement('span');routeState.className='conversation-route-state';routeState.dataset.state='checking';routeState.textContent='Checking response route…';routeState.setAttribute('role','status');
  titleInput.parentNode.insertBefore(titleStack,titleInput);titleStack.append(threadMark,titleInput,titleMeta,routeState);
  const titleSave=document.getElementById('conversation-rename');titleSave.disabled=true;
  titleInput.oninput=()=>{titleSave.disabled=titleInput.value.trim()===(thread.title||'')||!titleInput.value.trim();};
  titleInput.onkeydown=event=>{if(event.key==='Enter'&&!titleSave.disabled){event.preventDefault();update({title:titleInput.value.trim()});}if(event.key==='Escape'){titleInput.value=thread.title||'';titleSave.disabled=true;titleInput.blur();}};
  titleSave.onclick=()=>update({title:titleInput.value.trim()});
  const pin=document.getElementById('conversation-pin');pin.textContent=thread.pinned?'Unpin':'Pin';pin.setAttribute('aria-label',thread.pinned?'Unpin conversation':'Pin conversation');pin.onclick=()=>update({pinned:!thread.pinned});
  const archive=document.getElementById('conversation-archive');archive.textContent=thread.archived?'Restore':'Archive';archive.setAttribute('aria-label',thread.archived?'Restore conversation':'Archive conversation');archive.onclick=()=>{conversationState.selected=null;return update({archived:!thread.archived});};
  const move=document.createElement('button');move.className='btn btn-sm btn-secondary';move.textContent='Move';move.setAttribute('aria-label','Move conversation to another project');move.disabled=Boolean(thread.archived);move.onclick=()=>openConversationMove(thread);stage.querySelector('.conversation-more-actions').append(move);const more=stage.querySelector('.conversation-more'),moreTrigger=more.querySelector('summary');more.addEventListener('toggle',()=>moreTrigger.setAttribute('aria-expanded',String(more.open)));stage.querySelector('.conversation-more-actions').addEventListener('click',event=>{if(event.target.closest('button'))more.open=false;});workspace.addEventListener('pointerdown',event=>{if(!more.contains(event.target))more.open=false;});more.addEventListener('keydown',event=>{if(event.key==='Escape'){more.open=false;moreTrigger.focus();}});
  document.getElementById('conversation-export').onclick=()=>openConversationExport(thread,messages);
  const feed=document.getElementById('conversation-feed');
  if(!messages.length){const hint=document.createElement('section');hint.className='conversation-start-hint';hint.setAttribute('role','note');hint.innerHTML='<svg viewBox="0 0 160 112" fill="none" aria-hidden="true"><defs><linearGradient id="thread-path" x1="24" y1="28" x2="132" y2="82"><stop stop-color="#7cd4af"/><stop offset=".55" stop-color="#c4b5fd"/><stop offset="1" stop-color="#e9bc77"/></linearGradient></defs><path d="M36 57h88" stroke="url(#thread-path)" stroke-width="2" stroke-dasharray="3 6"/><rect x="7" y="30" width="48" height="48" rx="14" fill="#7cd4af" fill-opacity=".12" stroke="#7cd4af" stroke-opacity=".55"/><path d="M20 47h22M20 57h15M20 67h18" stroke="#7cd4af" stroke-width="2" stroke-linecap="round"/><rect x="56" y="13" width="48" height="48" rx="14" fill="#c4b5fd" fill-opacity=".11" stroke="#c4b5fd" stroke-opacity=".6"/><circle cx="70" cy="29" r="3" fill="#c4b5fd"/><path d="M79 29h14M69 40h27M69 49h18" stroke="#c4b5fd" stroke-width="2" stroke-linecap="round"/><rect x="105" y="42" width="48" height="48" rx="14" fill="#e9bc77" fill-opacity=".09" stroke="#e9bc77" stroke-opacity=".52"/><path d="m119 66 7 7 14-16" stroke="#e9bc77" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg><div class="conversation-start-copy"><span class="goal-kicker">A fresh conversation</span><strong>What would a useful result look like?</strong><p>Share the outcome, the context that matters, and any limits to respect.</p></div><div class="conversation-start-steps"><span><i>01</i> Outcome</span><span><i>02</i> Context</span><span><i>03</i> Evidence</span></div>';feed.appendChild(hint);}
  let replyTo=conversationDraftReplies.get(id)||null;
  const chooseReply=message=>{replyTo=message.id;conversationDraftReplies.set(id,replyTo);void saveDraftExtras(id);const quote=stage.querySelector('.composer-reply');quote.hidden=false;quote.textContent='Reply to: '+(message.content.slice(0,150)||'Attachment');const cancel=document.createElement('button');cancel.type='button';cancel.textContent='×';cancel.setAttribute('aria-label','Cancel reply');cancel.onclick=()=>{replyTo=null;conversationDraftReplies.delete(id);void saveDraftExtras(id);quote.hidden=true;};quote.appendChild(cancel);stage.querySelector('textarea').focus();};
  const edit=thread.archived?null:message=>openMessageEditor(message,async content=>{await conversationRequest('/api/threads/'+id+'/messages/'+message.id,'PATCH',{content,expectedContent:message.content});await selectConversation(id);});
  const branch=async message=>{try{const created=await conversationRequest('/api/threads/'+id+'/branch','POST',{throughMessageId:message.id});conversationState.selected=created.id;conversationState.archived=false;await showConversations();}catch(error){stage.querySelector('.conversation-feedback').textContent=error.message;}};
  if(thread.parentThreadId){const origin=document.createElement('button');origin.className='conversation-origin';origin.textContent='↳ Branched conversation · Open original';origin.onclick=()=>selectConversation(thread.parentThreadId);feed.appendChild(origin);}
  for(const message of messages){const author=message.authorType==='agent'?conversationState.agents.find(agent=>agent.id===message.authorId)?.name:null;const article=renderConversationMessage(message,messages,chooseReply,edit,branch,thread.archived?null:message=>openResponseAlternative(thread,message),author);article.dataset.messageId=message.id;feed.appendChild(article);}
  setupTranscriptSearch(stage,feed,messages);
  const form=stage.querySelector('form');const input=form.querySelector('textarea');input.disabled=Boolean(thread.archived)||pendingConversationSends.has(id);
  const attachments=conversationDraftMedia.get(id)||[];conversationDraftMedia.set(id,attachments);const sendButton=form.querySelector('button[type=submit]');const updateComposerAvailability=()=>{sendButton.disabled=input.disabled||form.dataset.readingFiles==='true'||form.dataset.responseBusy==='true'||(!input.value.trim()&&!attachments.length);};form.addEventListener('composer-state-change',updateComposerAvailability);setupConversationAttachments(form,attachments,()=>{void saveDraftExtras(id);updateComposerAvailability();});updateComposerAvailability();
  if(replyTo){const replied=messages.find(message=>message.id===replyTo);if(replied)chooseReply(replied);else conversationDraftReplies.delete(id);}
  if(draftStorageFailed)form.querySelector('.conversation-feedback').textContent='Saved draft files could not be restored. Browser storage is unavailable.';
  void setupResponseControls(thread,messages,form);
  if(thread.archived||pendingConversationSends.has(id)){form.querySelector('[data-attach]').disabled=true;form.ondrop=event=>event.preventDefault();}
  const draftKey='agentforge-draft-'+id;try{input.value=localStorage.getItem(draftKey)||'';}catch{}
  // CSS caps the editor against the viewport, leaving the transcript usable on short screens.
  const resizeComposer=()=>{input.style.height='auto';input.style.height=Math.min(200,Math.max(48,input.scrollHeight))+'px';};
  input.oninput=()=>{resizeComposer();try{localStorage.setItem(draftKey,input.value);}catch{}updateComposerAvailability();};resizeComposer();
  const shortcutButton=form.querySelector('[data-send-shortcut]');
  const refreshSendShortcut=()=>{const modifier=conversationSendShortcut==='modifier-enter';shortcutButton.textContent=modifier?'Ctrl / ⌘ + Enter':'Enter sends';shortcutButton.setAttribute('aria-pressed',String(modifier));shortcutButton.setAttribute('aria-label',modifier?'Change send shortcut to Enter':'Change send shortcut to Ctrl or Command plus Enter');shortcutButton.title=modifier?'Enter adds a new line. Click to send with Enter.':'Click to require Ctrl or Command plus Enter; Shift+Enter adds a new line.';sendButton.title=conversationShortcutHint();input.setAttribute('aria-description',conversationShortcutHint());};
  shortcutButton.onclick=()=>{conversationSendShortcut=conversationSendShortcut==='enter'?'modifier-enter':'enter';try{localStorage.setItem('agentforge-send-shortcut',conversationSendShortcut);}catch{}refreshSendShortcut();};refreshSendShortcut();
  input.onkeydown=event=>{if(event.key!=='Enter'||event.shiftKey||event.altKey||event.isComposing)return;const modified=event.ctrlKey||event.metaKey;if(conversationSendShortcut==='enter'||modified){event.preventDefault();form.requestSubmit();}};
  form.onsubmit=async event=>{event.preventDefault();if(form.dataset.readingFiles==='true'){form.querySelector('.conversation-feedback').textContent='Finishing attachment upload. Send when it is ready.';return;}const text=input.value.trim();if(!text&&!attachments.length)return;const button=form.querySelector('button[type=submit]');if(button.disabled||pendingConversationSends.has(id))return;pendingConversationSends.add(id);button.disabled=true;input.disabled=true;
    try{const model=form.querySelector('[aria-label="Response model"]')?.value||'';const saved=await conversationRequest('/api/messages','POST',{channelId:thread.channelId,threadId:id,content:text,attachments,...(replyTo?{replyToMessageId:replyTo}:{})});try{localStorage.removeItem(draftKey);}catch{}conversationDraftMedia.delete(id);conversationDraftReplies.delete(id);await saveDraftExtras(id,true).catch(()=>{});pendingConversationSends.delete(id);conversationReadingPositions.delete(id);if(currentView==='messages'&&conversationState.selected===id)await selectConversation(id,{focusComposer:true});if(model)await generateConversationResponse(id,saved.id,model);}
    catch(error){pendingConversationSends.delete(id);if(currentView==='messages'&&conversationState.selected===id){await selectConversation(id);document.querySelector('.conversation-composer .conversation-feedback').textContent=error.message;}}finally{pendingConversationSends.delete(id);}
  };
  setupConversationReadingPosition(id,feed);
  // Restore typing only if rendering lost focus; never steal it from another control.
  if(options.focusComposer&&document.activeElement===document.body&&!input.disabled)input.focus({preventScroll:true});
}
function setupConversationReadingPosition(id,feed){
 const latest=document.createElement('button');latest.type='button';latest.className='conversation-jump-latest';latest.textContent='↓ Latest';latest.setAttribute('aria-label','Jump to latest messages');latest.title='Jump to latest messages';latest.hidden=true;const headerActions=feed.closest('.conversation-stage')?.querySelector('.conversation-header-actions');if(headerActions)headerActions.append(latest);else feed.after(latest);
 const remember=()=>{const follow=feed.scrollHeight-feed.scrollTop-feed.clientHeight<72;conversationReadingPositions.set(id,{top:feed.scrollTop,follow});latest.hidden=follow;};
 const saved=conversationReadingPositions.get(id);feed.scrollTop=saved&&!saved.follow?saved.top:feed.scrollHeight;remember();
 feed.addEventListener('scroll',remember,{passive:true});latest.onclick=()=>{feed.scrollTop=feed.scrollHeight;remember();};
}
function setupTranscriptSearch(stage,feed,messages){
 const bar=document.createElement('div');bar.className='transcript-search';bar.hidden=true;bar.innerHTML='<input class="form-control" aria-label="Find in conversation" placeholder="Find in this conversation"><span role="status"></span><button type="button" aria-label="Previous match">↑</button><button type="button" aria-label="Next match">↓</button><button type="button" aria-label="Close conversation search">×</button>';
 const toggle=document.createElement('button');toggle.className='btn btn-sm btn-secondary';toggle.textContent='Find';toggle.onclick=()=>{bar.hidden=!bar.hidden;if(!bar.hidden)bar.querySelector('input').focus();};stage.querySelector('.conversation-header-actions').prepend(toggle);feed.before(bar);
 let matches=[],index=-1;const input=bar.querySelector('input'),status=bar.querySelector('[role=status]');
 function show(){feed.querySelectorAll('.search-match').forEach(node=>node.classList.remove('search-match'));status.textContent=matches.length?(index+1)+' / '+matches.length:input.value?'No matches':'';if(index>=0){const node=Array.from(feed.querySelectorAll('[data-message-id]')).find(item=>item.dataset.messageId===matches[index]);if(node){node.classList.add('search-match');node.scrollIntoView({block:'center',behavior:'auto'});}}}
 input.oninput=()=>{const query=input.value.toLowerCase().trim();matches=query?messages.filter(message=>[message.content,...(message.attachments||[]).map(file=>file.filename)].join(' ').toLowerCase().includes(query)).map(message=>message.id):[];index=matches.length?0:-1;show();};
 const move=direction=>{if(matches.length){index=(index+direction+matches.length)%matches.length;show();}};
 bar.querySelector('[aria-label="Previous match"]').onclick=()=>move(-1);bar.querySelector('[aria-label="Next match"]').onclick=()=>move(1);const close=()=>{bar.hidden=true;input.value='';matches=[];index=-1;show();toggle.focus();};bar.querySelector('[aria-label="Close conversation search"]').onclick=close;input.onkeydown=event=>{if(event.key==='Escape'){event.preventDefault();close();}else if(event.key==='Enter'){event.preventDefault();move(event.shiftKey?-1:1);}};
}

function openConversationExport(thread,messages){
 const dialog=document.createElement('dialog');dialog.className='conversation-dialog conversation-export-dialog';dialog.innerHTML='<h2>Take your work with you</h2><p>Export this conversation as readable Markdown or a complete JSON record.</p><label>Format<select class="form-control"><option value="markdown">Markdown · readable transcript</option><option value="json">JSON · full record and attachments</option></select></label><p class="export-scope"></p><textarea class="form-control" aria-label="Export preview" readonly></textarea><p class="conversation-feedback" role="status"></p><footer><button class="btn btn-secondary" data-close>Close</button><button class="btn btn-secondary" data-copy>Copy</button><button class="btn" data-download>Download</button></footer>';
 let content='',extension='md',mime='text/markdown';
 const render=()=>{const json=dialog.querySelector('select').value==='json';extension=json?'json':'md';mime=json?'application/json':'text/markdown';content=json?JSON.stringify({thread,messages},null,2):['# '+(thread.title||'Conversation'),'','Exported from AgentForge · '+new Date().toISOString(),'',...messages.flatMap(message=>['---','','## '+(message.authorType==='user'?'User':message.authorType)+' · '+message.createdAt,'',...(message.replyToMessageId?['Reply to message '+message.replyToMessageId,'']:[]),message.content||'',...(message.generation?['','Response: '+message.generation.model+' · '+message.generation.status]:[]),...(message.attachments?.length?['','Attachments (file content included in JSON export only):',...message.attachments.map(file=>'- '+file.filename)]:[]),''])].join('\n');dialog.querySelector('textarea').value=content;dialog.querySelector('.export-scope').textContent=json?'Includes attachment data, message edits, and saved metadata.':'Includes message text and attachment names. Use JSON to retain attached files and edit history.';dialog.querySelector('.conversation-feedback').textContent='';};
 dialog.querySelector('select').onchange=render;dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();dialog.querySelector('[data-copy]').onclick=async()=>{try{await navigator.clipboard.writeText(content);dialog.querySelector('.conversation-feedback').textContent='Copied to clipboard.';}catch{dialog.querySelector('.conversation-feedback').textContent='Could not copy. You can select the preview or download the file.';}};
 dialog.querySelector('[data-download]').onclick=()=>{const url=URL.createObjectURL(new Blob([content],{type:mime}));const link=document.createElement('a');link.href=url;link.download=(thread.title||'conversation').replace(/[^a-z0-9 _-]/gi,'').trim().slice(0,80)+'-'+thread.id+'.'+extension;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};render();document.body.append(dialog);dialog.showModal();
}

async function openConversationMove(thread){
 const dialog=document.createElement('dialog');dialog.className='conversation-dialog';dialog.innerHTML='<h2>Move conversation</h2><p>Keep the full history and attachments. Future AI replies will use the destination project’s instructions.</p><label>Destination<select class="form-control"></select></label><p class="conversation-feedback" role="status"></p><footer><button type="button" class="btn btn-secondary" data-create hidden>Create a project</button><button type="button" class="btn btn-secondary" data-cancel>Cancel</button><button class="btn" data-save disabled>Move conversation</button></footer>';
 dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();document.body.append(dialog);dialog.showModal();
 try{const [projects,channels]=await Promise.all([conversationRequest('/api/projects'),conversationRequest('/api/channels')]);if(!dialog.isConnected)return;const select=dialog.querySelector('select');for(const channel of channels.filter(c=>c.id!==thread.channelId&&!c.archived&&c.visibility==='private'&&['agentforge','web'].includes(c.provider)&&projects.some(p=>p.id===c.spaceId&&!p.archived))){const option=document.createElement('option');option.value=channel.id;option.textContent=projects.find(p=>p.id===channel.spaceId).name+' / '+channel.name;select.append(option);}const save=dialog.querySelector('[data-save]');save.disabled=!select.options.length;if(save.disabled){dialog.querySelector('.conversation-feedback').textContent='Create a project with a private conversation channel to move this thread.';const create=dialog.querySelector('[data-create]');create.hidden=false;create.onclick=()=>{dialog.close();editProject();};}
 save.onclick=async()=>{if(save.disabled||pendingConversationSends.has(thread.id))return;save.disabled=true;try{await conversationRequest('/api/threads/'+thread.id+'/move','POST',{channelId:select.value});conversationState.projectId=channels.find(c=>c.id===select.value).spaceId;conversationState.query='';conversationSearchResults=null;dialog.close();await showConversations();}catch(error){dialog.querySelector('.conversation-feedback').textContent=error.message;save.disabled=false;}};
 }catch(error){dialog.querySelector('.conversation-feedback').textContent=error.message;}
}
`;
