/** Read canonical specification files through the existing documentation API. */
export const documentClient = String.raw`
function renderDocumentLoading(target){
 target.replaceChildren();const skeleton=document.createElement('div');skeleton.className='document-reader-skeleton';skeleton.setAttribute('aria-label','Document is loading');skeleton.innerHTML='<strong></strong><span></span><span></span><span></span><span></span><span></span>';target.append(skeleton);
}
function renderDocumentError(target,error,retry){
 target.replaceChildren();const notice=document.createElement('section');notice.className='document-reader-notice';const heading=document.createElement('strong');heading.textContent='Could not open this document';const copy=document.createElement('p');copy.textContent=error.message||'Try again.';const button=document.createElement('button');button.className='btn btn-sm btn-secondary';button.type='button';button.textContent='Try again';button.onclick=retry;notice.append(heading,copy,button);target.append(notice);
}
async function showDocumentLibrary(){
 const docs=await conversationRequest('/api/docs');if(currentView!=='docs')return;
 const root=document.getElementById('view-content');root.innerHTML='<main class="document-workspace"><header class="project-hero"><div><span class="forge-topline">THE WORKSPACE LIBRARY</span><h1>Specifications & guides</h1><p>Read the requirements, architecture, and operating guidance behind your workspace.</p></div><div class="catalog-art" aria-hidden="true"><span>≡</span><span>◇</span><span>↗</span><span>✳</span></div></header><div class="document-layout"><aside class="document-catalog"><input class="form-control" aria-label="Search document titles" placeholder="Find a title or filename"><select class="form-control" aria-label="Document category"><option value="">All categories</option></select><p role="status"></p><nav aria-label="Documents"></nav></aside><article class="document-reader"><div class="document-reader-toolbar"><div><h2>Select a document</h2><p></p></div><button class="btn btn-secondary" id="document-mode" disabled>View source</button><button class="btn btn-secondary" id="document-copy" disabled>Copy</button></div><details class="document-outline" hidden><summary>On this page</summary><nav></nav></details><div class="document-content conversation-message"></div></article></div></main>';
 const search=root.querySelector('input'),filter=root.querySelector('select'),list=root.querySelector('.document-catalog nav'),body=root.querySelector('.document-content'),outline=root.querySelector('.document-outline'),mode=root.querySelector('#document-mode'),copy=root.querySelector('#document-copy');let selected=null,raw='',source=false,version=0;
 for(const category of [...new Set(docs.map(doc=>doc.category))].sort()){const option=document.createElement('option');option.value=category;option.textContent=category;filter.append(option);}
 function draw(){body.replaceChildren();outline.querySelector('nav').replaceChildren();mode.textContent=source?'Read document':'View source';if(source){const pre=document.createElement('pre');pre.className='document-source';pre.textContent=raw;body.append(pre);outline.hidden=true;return;}appendMessageContent(body,raw);const headings=body.querySelectorAll('h2,h3,h4,h5,h6');outline.hidden=!headings.length;for(const heading of headings){const button=document.createElement('button');button.textContent=heading.textContent;button.onclick=()=>heading.scrollIntoView({block:'start',behavior:'auto'});outline.querySelector('nav').append(button);}}
 async function open(doc){const ticket=++version;selected=doc.name;for(const item of list.children)item.setAttribute('aria-pressed',String(item.dataset.name===selected));root.querySelector('.document-reader h2').textContent=doc.title;root.querySelector('.document-reader-toolbar p').textContent=doc.name;renderDocumentLoading(body);outline.hidden=true;copy.disabled=true;mode.disabled=true;try{const result=await conversationRequest('/api/docs/'+encodeURIComponent(doc.name));if(ticket!==version||!body.isConnected)return;raw=result.content;root.querySelector('.document-reader-toolbar p').textContent=doc.name+' · '+Math.ceil(result.sizeBytes/1024)+' KB · Updated '+new Date(result.modifiedAt).toLocaleDateString();copy.disabled=false;mode.disabled=false;copy.textContent='Copy';draw();}catch(error){if(ticket===version&&body.isConnected)renderDocumentError(body,error,()=>open(doc));}}
 function render(){const query=search.value.toLowerCase().trim();const visible=docs.filter(doc=>(!filter.value||doc.category===filter.value)&&[doc.title,doc.name].join(' ').toLowerCase().includes(query));list.replaceChildren();root.querySelector('.document-catalog [role=status]').textContent=visible.length+' of '+docs.length+' documents';for(const doc of visible){const button=document.createElement('button');button.dataset.name=doc.name;button.setAttribute('aria-pressed',String(selected===doc.name));const title=document.createElement('strong');title.textContent=doc.title;const name=document.createElement('small');name.textContent=doc.name;button.append(title,name);button.onclick=()=>open(doc);list.append(button);}if(!visible.length){const empty=document.createElement('p');empty.className='memory-disclosure';empty.textContent='No matching documents.';list.append(empty);}}
 search.oninput=render;filter.onchange=render;mode.onclick=()=>{source=!source;draw();};copy.onclick=async()=>{try{await navigator.clipboard.writeText(raw);copy.textContent='Copied';}catch{copy.textContent='Copy unavailable';}};render();if(docs.length)await open(docs[0]);else body.textContent='No local specification files are available.';
}
`;
