/** Readable presentation of recorded evidence; never substitutes invented checks. */
export const evidenceClient = String.raw`
function evidenceField(parent,label,value){const row=document.createElement('div');row.className='work-detail-field';const name=document.createElement('span');name.textContent=label;const text=document.createElement('strong');text.textContent=String(value??'Not recorded');row.append(name,text);parent.append(row);}
function renderTaskChanges(body,result){
 body.replaceChildren();const files=Array.isArray(result.filesChanged)?result.filesChanged:[];const heading=document.createElement('p');heading.className='evidence-summary';heading.textContent=files.length+' changed files · +'+(result.diffStat?.insertions??0)+' / −'+(result.diffStat?.deletions??0);body.append(heading);
 evidenceField(body,'Base revision',result.baseSha);evidenceField(body,'Final revision',result.currentSha);
 if(!files.length){const empty=document.createElement('p');empty.textContent='No changed files are recorded in this evidence pack.';body.append(empty);}
 const tools=document.createElement('div');tools.className='evidence-file-tools';const search=document.createElement('input');search.className='form-control';search.placeholder='Find a changed file…';search.setAttribute('aria-label','Find a changed file');const expand=document.createElement('button');expand.className='btn btn-secondary';expand.textContent='Expand all';const collapse=document.createElement('button');collapse.className='btn btn-secondary';collapse.textContent='Collapse all';const count=document.createElement('p');count.className='memory-disclosure';count.setAttribute('role','status');tools.append(search,expand,collapse);if(files.length)body.append(tools,count);const sections=[];
 const filter=()=>{let visible=0;for(const item of sections){item.section.hidden=!item.path.toLowerCase().includes(search.value.toLowerCase().trim());if(!item.section.hidden)visible++;}count.textContent=visible+' of '+files.length+' changed files';};search.oninput=filter;expand.onclick=()=>sections.forEach(item=>{if(!item.section.hidden)item.section.open=true;});collapse.onclick=()=>sections.forEach(item=>item.section.open=false);
 for(const file of files){const section=document.createElement('details');section.className='evidence-file';sections.push({section,path:file.filePath});const summary=document.createElement('summary');const name=document.createElement('strong');name.textContent=file.filePath;const meta=document.createElement('span');meta.textContent=file.status+' · +'+file.linesAdded+' / −'+file.linesDeleted;summary.append(name,meta);section.append(summary);if(typeof file.patch==='string'&&file.patch){const copy=document.createElement('button');copy.className='btn btn-sm btn-secondary';copy.textContent='Copy full patch';copy.onclick=async()=>{try{await navigator.clipboard.writeText(file.patch);copy.textContent='Copied';}catch{copy.textContent='Copy unavailable';}};section.append(copy);const patch=document.createElement('pre');patch.className='evidence-patch';for(const line of file.patch.split('\n').slice(0,3000)){const span=document.createElement('span');span.className=line.startsWith('@@')?'patch-location':line.startsWith('+')&&!line.startsWith('+++')?'patch-added':line.startsWith('-')&&!line.startsWith('---')?'patch-removed':'';span.textContent=line+'\n';patch.append(span);}section.append(patch);if(file.patch.split('\n').length>3000){const note=document.createElement('p');note.textContent='Preview limited to 3,000 lines. The full patch remains in the evidence record.';section.append(note);}}else{const note=document.createElement('p');note.textContent='File metadata was recorded without a line-by-line patch.';section.append(note);}body.append(section);}filter();
}
function renderTaskEvidence(body,result){
 body.replaceChildren();const pack=result.evidencePack;if(!pack){body.textContent='No evidence pack is available.';return;}
 const status=document.createElement('div');status.className='evidence-verdict '+(pack.verifiedPassed?'passed':'failed');status.textContent=pack.verifiedPassed?'Recorded verification passed':'Recorded verification did not pass';body.append(status);
 const objective=document.createElement('p');objective.textContent=pack.objective||result.objective;body.append(objective);evidenceField(body,'Collected',pack.generatedAt?new Date(pack.generatedAt).toLocaleString():'Not recorded');evidenceField(body,'Approved by',pack.approvedBy||'No approval recorded');
 const checks=document.createElement('h3');checks.textContent='Checks';body.append(checks);if(!pack.testResults?.length){const p=document.createElement('p');p.textContent='No check results recorded.';body.append(p);}
 for(const check of pack.testResults||[]){const detail=document.createElement('details');detail.className='evidence-check';const summary=document.createElement('summary');const verdict=document.createElement('span');verdict.className=check.passed?'evidence-pass':'evidence-fail';verdict.textContent=check.passed?'Passed':'Failed';const name=document.createElement('strong');name.textContent=check.checkName;const time=document.createElement('span');time.textContent=(check.durationMs/1000).toFixed(2)+'s · exit '+check.exitCode;summary.append(verdict,name,time);detail.append(summary);const command=document.createElement('pre');command.textContent=check.command;detail.append(command);for(const [label,text] of [['Output',check.stdout],['Errors',check.stderr]]){if(!text)continue;const title=document.createElement('h4');title.textContent=label;const output=document.createElement('pre');output.textContent=text;detail.append(title,output);}body.append(detail);}
 const commands=document.createElement('details');commands.className='evidence-check';const title=document.createElement('summary');title.textContent='Command history · '+(pack.commandsExecuted||[]).length;commands.append(title);for(const command of pack.commandsExecuted||[]){const block=document.createElement('section');evidenceField(block,'Command',command.command);evidenceField(block,'Exit code',command.exitCode);evidenceField(block,'Directory',command.cwd);evidenceField(block,'Started',command.timestamp);commands.append(block);}body.append(commands);
 const artifacts=document.createElement('h3');artifacts.textContent='Artifacts';body.append(artifacts);if(!pack.artifacts?.length){const p=document.createElement('p');p.textContent='No artifacts recorded.';body.append(p);}for(const artifact of pack.artifacts||[]){const block=document.createElement('section');block.className='evidence-artifact';evidenceField(block,'Name',artifact.name);evidenceField(block,'Saved path',artifact.path);evidenceField(block,'Size',artifact.sizeBytes+' bytes');evidenceField(block,'SHA-256',artifact.sha256);body.append(block);}
 const raw=document.createElement('details');raw.className='evidence-check';const label=document.createElement('summary');label.textContent='Full evidence record';const pre=document.createElement('pre');pre.textContent=JSON.stringify(pack,null,2);raw.append(label,pre);body.append(raw);
}
`;
