/** Inspect a saved requirement plan and record explicit, reviewable proof references. */
export const goalClient = String.raw`
function showGoalDetails(session){
 const dialog=document.createElement('dialog');dialog.className='conversation-dialog goal-detail-dialog';dialog.innerHTML='<form method="dialog"><header><div><span class="forge-topline">SAVED GOAL PLAN</span><h2></h2><p class="goal-detail-state"></p></div><button class="btn btn-secondary">Close</button></header></form><nav class="goal-detail-tabs" aria-label="Goal details"></nav><div class="goal-detail-body"></div>';
 dialog.querySelector('h2').textContent=session.prd?.title||'Goal plan';dialog.querySelector('.goal-detail-state').textContent=session.state.replaceAll('_',' ').toLowerCase()+' · '+(session.verifiedByEngine?'Engine verification recorded':'Completion not verified');const tabs=dialog.querySelector('nav'),body=dialog.querySelector('.goal-detail-body');
 const text=(parent,tag,value,className)=>{const node=document.createElement(tag);node.textContent=value;if(className)node.className=className;parent.append(node);return node;};
 const exportButton=document.createElement('button');exportButton.type='button';exportButton.className='btn btn-secondary';exportButton.textContent='Export plan';exportButton.onclick=()=>openGoalExport(session);dialog.querySelector('header').append(exportButton);
 const coverage=document.createElement('section');coverage.className='goal-coverage';coverage.setAttribute('aria-label','Requirement evidence coverage');
 const requirements=session.prd?.requirements||[];const referenced=requirements.filter(requirement=>(session.traceability||[]).some(record=>record.requirementId===requirement.id&&record.evidencePackIds?.length)).length;
 const summary=document.createElement('dl');for(const [label,value] of [['Requirements',requirements.length],['With evidence references',referenced],['Missing evidence references',requirements.length-referenced]]){const cell=document.createElement('div');text(cell,'dt',label);text(cell,'dd',String(value));summary.append(cell);}coverage.append(summary);
 const meter=document.createElement('div');meter.className='goal-coverage-track';meter.setAttribute('aria-hidden','true');const fill=document.createElement('span');fill.style.width=(requirements.length?referenced/requirements.length*100:0)+'%';meter.append(fill);coverage.append(meter);text(coverage,'p','References show where proof is recorded. They do not establish that a requirement passed verification.','memory-disclosure');tabs.before(coverage);const refreshCoverage=()=>{const count=requirements.filter(requirement=>(session.traceability||[]).some(record=>record.requirementId===requirement.id&&record.evidencePackIds?.length)).length;summary.children[1]?.querySelector('dd').replaceChildren(String(count));summary.children[2]?.querySelector('dd').replaceChildren(String(requirements.length-count));fill.style.width=(requirements.length?count/requirements.length*100:0)+'%';};
 const bulletList=(parent,values,empty)=>{if(!values?.length){text(parent,'p',empty,'memory-disclosure');return;}const ul=document.createElement('ul');for(const value of values)text(ul,'li',value);parent.append(ul);};
 function openEvidenceRecorder(record){const trigger=document.activeElement;const editor=document.createElement('dialog');editor.className='conversation-dialog goal-evidence-dialog';editor.setAttribute('aria-label','Add evidence references for '+record.requirementId);editor.innerHTML='<form><header><div><span class="forge-topline">REVIEWABLE PROOF</span><h2>Add references</h2><p>Record paths or identifiers already produced by the work. Saving references never marks this requirement complete.</p></div><button class="btn btn-secondary" type="button" data-close>Close</button></header><label>Work items<textarea class="form-control" name="taskIds" rows="2" placeholder="One task ID per line"></textarea></label><label>Code artifacts<textarea class="form-control" name="codeArtifacts" rows="3" placeholder="One source or artifact path per line"></textarea></label><label>Tests<textarea class="form-control" name="testNames" rows="3" placeholder="One test name or path per line"></textarea></label><label>Evidence packs<textarea class="form-control" name="evidencePackIds" rows="3" placeholder="One evidence identifier or path per line"></textarea></label><p class="memory-disclosure">Existing references stay in place. Only explicit identifiers are recorded.</p><p role="status"></p><footer><button class="btn" type="submit">Save references</button></footer></form>';
 const split=name=>String(new FormData(editor.querySelector('form')).get(name)||'').split(/\\r?\\n/).map(value=>value.trim()).filter(Boolean);const status=editor.querySelector('[role=status]');editor.querySelector('[data-close]').onclick=()=>editor.close();editor.querySelector('form').onsubmit=async event=>{event.preventDefault();const payload={taskIds:split('taskIds'),codeArtifacts:split('codeArtifacts'),testNames:split('testNames'),evidencePackIds:split('evidencePackIds')};const submit=editor.querySelector('[type=submit]');submit.disabled=true;status.textContent='Saving references…';try{const response=await fetch('/api/completion/sessions/'+encodeURIComponent(session.taskId)+'/traceability/'+encodeURIComponent(record.requirementId),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const updated=await response.json();if(!response.ok)throw new Error(updated.error||'Could not save references.');session.traceability=updated.traceability;session.contractDeficits=updated.contractDeficits;refreshCoverage();status.textContent='Saved. This requirement remains unverified until its checks are reviewed.';render('evidence');editor.close();}catch(error){status.textContent=error instanceof Error?error.message:'Could not save references.';}finally{submit.disabled=false;}};editor.onclose=()=>{editor.remove();if(trigger?.isConnected)trigger.focus();};document.body.append(editor);editor.showModal();}
 function render(view){for(const button of tabs.children)button.setAttribute('aria-pressed',String(button.dataset.view===view));body.replaceChildren();
 if(view==='goal'){text(body,'h3','Original request');text(body,'div',session.originalGoal?.rawText||'No original text recorded.','goal-original-text');text(body,'p','Saved '+new Date(session.startedAt).toLocaleString(),'memory-disclosure');text(body,'h3','Plan overview');text(body,'p',session.prd?.overview||'No overview recorded.');text(body,'h3','Release criteria');bulletList(body,session.prd?.releaseCriteria,'No release criteria recorded.');}
 if(view==='requirements'){for(const requirement of session.prd?.requirements||[]){const section=document.createElement('section');section.className='goal-requirement';const trace=(session.traceability||[]).find(item=>item.requirementId===requirement.id);text(section,'span',requirement.id+' · '+requirement.category+' · '+requirement.riskLevel+' risk','forge-topline');text(section,'h3',requirement.title);text(section,'p',requirement.description);text(section,'h4','Acceptance criteria');bulletList(section,requirement.acceptanceCriteria,'No acceptance criteria recorded.');text(section,'h4','Verification approach');text(section,'p',requirement.testStrategy||'No strategy recorded.');text(section,'p','Audit: '+(trace?.auditResultStatus||'Not recorded'),'memory-disclosure');if(trace?.blockerReason)text(section,'p',trace.blockerReason);body.append(section);}if(!body.children.length)text(body,'p','No requirements recorded.');}
 if(view==='dependencies')renderGoalDependencies(body,session.dag||[]);
 if(view==='evidence'){for(const record of session.traceability||[]){const section=document.createElement('section');section.className='goal-requirement';const heading=document.createElement('div');heading.className='goal-evidence-heading';text(heading,'h3',record.requirementId);const addEvidence=document.createElement('button');addEvidence.type='button';addEvidence.className='btn btn-secondary btn-sm';addEvidence.textContent='Add references';addEvidence.onclick=()=>openEvidenceRecorder(record);heading.append(addEvidence);section.append(heading);text(section,'p','Audit: '+(record.auditResultStatus||'Not recorded'),'memory-disclosure');if(record.blockerReason)text(section,'p',record.blockerReason,'goal-dependency-warning');for(const [label,values] of [['Work items',record.taskIds],['Code artifacts',record.codeArtifacts],['Tests',record.testNames],['Evidence packs',record.evidencePackIds]]){text(section,'h4',label);bulletList(section,values,'None recorded.');}body.append(section);}if(!(session.traceability||[]).length)text(body,'p','No evidence references recorded.');if(session.auditResult){const details=document.createElement('details');text(details,'summary','Completion audit record');text(details,'pre',JSON.stringify(session.auditResult,null,2));body.append(details);}}
 if(view==='review'){text(body,'h3',session.criticReview?.critiquePassed?'Source checks passed':'Source checks need review');text(body,'p','These automated checks compare source keywords and required plan fields. They are not a semantic design review or proof that the implementation is complete.','memory-disclosure');for(const [label,key] of [['Omissions from the goal','omissionsFromGoal'],['Missing safety requirements','missingSafetyRequirements'],['Missing tests','missingTestsIdentified'],['Edge cases','edgeCasesIdentified'],['Dependencies added','impliedDependenciesAdded'],['Rollback considerations','rollbackIdentified']]){text(body,'h4',label);bulletList(body,session.criticReview?.[key],'None recorded.');}text(body,'h4','Contract deficits');bulletList(body,session.contractDeficits,'None recorded.');}
 }
 for(const [view,label] of [['goal','Original goal'],['requirements','Requirements'],['dependencies','Dependencies'],['evidence','Evidence'],['review','Review']]){const button=document.createElement('button');button.textContent=label;button.dataset.view=view;button.onclick=()=>render(view);tabs.append(button);}dialog.onclose=()=>dialog.remove();document.body.append(dialog);render('goal');dialog.showModal();
}

function renderGoalDependencies(body,nodes){
 const add=(parent,tag,value,cls)=>{const el=document.createElement(tag);el.textContent=value;if(cls)el.className=cls;parent.append(el);return el;};
 add(body,'p','Read from top to bottom. Items in the same step have no prerequisite between them. These are saved plan states, not a live execution trace.','memory-disclosure');
 if(!nodes.length){add(body,'p','No dependency nodes recorded.');return;}
 const remaining=new Set(nodes),resolved=new Set(),layers=[];
 while(remaining.size){const layer=[...remaining].filter(node=>node.dependencies.every(id=>resolved.has(id)));if(!layer.length)break;layers.push(layer);for(const node of layer){remaining.delete(node);resolved.add(node.requirementId);}}
 const cards=new Map();const diagram=document.createElement('div');diagram.className='goal-dependency-map';body.append(diagram);
 const renderLayer=(items,label)=>{const lane=document.createElement('section');lane.className='goal-dependency-layer';add(lane,'h3',label);const grid=document.createElement('div');grid.className='goal-dependency-grid';lane.append(grid);diagram.append(lane);for(const node of items){const card=document.createElement('article');card.className='goal-dependency-card';card.tabIndex=-1;cards.set(node.requirementId,card);add(card,'span',String(node.status).replaceAll('_',' ').toLowerCase(),'badge badge-muted');add(card,'h4',node.title);add(card,'small',node.requirementId,'memory-disclosure');if(node.blockedReason)add(card,'p',node.blockedReason,'goal-dependency-warning');const links=document.createElement('div');links.className='goal-prerequisites';if(!node.dependencies.length)add(links,'p','No prerequisites');else{add(links,'p','Requires');for(const id of node.dependencies){const target=nodes.find(item=>item.requirementId===id);if(!target){add(links,'span','Missing requirement: '+id,'goal-dependency-warning');continue;}const link=add(links,'button',target.title);link.type='button';link.onclick=()=>{const destination=cards.get(id);destination?.focus();destination?.scrollIntoView({block:'center',behavior:'auto'});};}}card.append(links);grid.append(card);}};
 layers.forEach((layer,index)=>renderLayer(layer,'Step '+(index+1)));
 if(remaining.size){add(diagram,'p','Some prerequisites are missing or circular. Their order cannot be resolved from this saved plan.','goal-dependency-warning');renderLayer([...remaining],'Needs plan repair');}
}

function openGoalExport(session){
 const trigger=document.activeElement;const dialog=document.createElement('dialog');dialog.className='conversation-dialog conversation-export-dialog';dialog.setAttribute('aria-label','Export goal plan');
 dialog.innerHTML='<h2>Export goal plan</h2><p>Includes the original request, requirements, dependencies and saved evidence references. Referenced files are not bundled, and export does not verify completion.</p><label>Format<select class="form-control" aria-label="Goal export format"><option value="markdown">Readable Markdown</option><option value="json">Complete JSON record</option></select></label><textarea readonly aria-label="Goal export preview"></textarea><p role="status"></p><footer><button class="btn btn-secondary" data-copy>Copy</button><button class="btn" data-download>Download</button><button class="btn btn-secondary" data-close>Close</button></footer>';
 let content='',format='markdown';
 const markdown=()=>{const lines=['# '+(session.prd?.title||'Goal plan'),'','Status: '+session.state,'Verification recorded: '+Boolean(session.verifiedByEngine),'','## Original request','',session.originalGoal?.rawText||'Not recorded.','','## Plan overview','',session.prd?.overview||'Not recorded.'];
 for(const req of session.prd?.requirements||[]){lines.push('','## '+req.id+' — '+req.title,'',req.description,'','Acceptance criteria:',...(req.acceptanceCriteria||[]).map(value=>'- '+value),'','Verification approach: '+(req.testStrategy||'Not recorded.'));}
 lines.push('','## Dependencies');for(const node of session.dag||[])lines.push('','- '+node.requirementId+': '+node.title+' ['+node.status+']','  Requires: '+(node.dependencies.join(', ')||'None'),...(node.blockedReason?['  Blocker: '+node.blockedReason]:[]));
 lines.push('','## Evidence references');for(const record of session.traceability||[])lines.push('','### '+record.requirementId,'Audit: '+(record.auditResultStatus||'Not recorded'),...(record.blockerReason?['Blocker: '+record.blockerReason]:[]),'Work items: '+((record.taskIds||[]).join(', ')||'None'),'Evidence packs: '+((record.evidencePackIds||[]).join(', ')||'None'),'Tests: '+((record.testNames||[]).join(', ')||'None'),'Artifacts: '+((record.codeArtifacts||[]).join(', ')||'None'));return lines.join('\n');};
 const render=()=>{format=dialog.querySelector('select').value;content=format==='json'?JSON.stringify({exportedAt:new Date().toISOString(),session},null,2):markdown();dialog.querySelector('textarea').value=content;dialog.querySelector('[role=status]').textContent='';};
 dialog.querySelector('select').onchange=render;dialog.querySelector('[data-copy]').onclick=async()=>{try{await navigator.clipboard.writeText(content);dialog.querySelector('[role=status]').textContent='Copied.';}catch{dialog.querySelector('[role=status]').textContent='Select the preview text to copy manually.';}};
 dialog.querySelector('[data-download]').onclick=()=>{const url=URL.createObjectURL(new Blob([content],{type:format==='json'?'application/json':'text/markdown'}));const a=document.createElement('a');a.href=url;a.download='agentforge-goal-'+String(session.taskId).replace(/[^a-zA-Z0-9_-]/g,'')+(format==='json'?'.json':'.md');a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.onclose=()=>{dialog.remove();if(trigger?.isConnected)trigger.focus();};render();document.body.append(dialog);dialog.showModal();
}
`;
