/** A portable, searchable reader for saved workspace knowledge. */
export const memoryClient = String.raw`
const memoryCategories={general_fact:'General facts',do_not_repeat:'Lessons learned',project_constraint:'Project constraints',task_history:'Task history',test_failure:'Test failures',repo_history:'Repository history',worktree_history:'Worktree history',commit:'Commits',deployment:'Deployments',approval:'Approvals',artifact:'Artifacts'};
const selectedMemoryByCollection=new Map();
function renderMemoryLoading(root){
 root.innerHTML='<main class="memory-workspace memory-loading" aria-busy="true" aria-live="polite"><header class="project-hero"><div><span class="forge-topline">WORKSPACE KNOWLEDGE</span><h1>Keep what matters</h1><p>Checking locally saved decisions, lessons, and project context.</p></div><div class="memory-illustration" aria-hidden="true">◇<span>◇</span><i>✳</i></div></header><div class="memory-toolbar-skeleton"><i></i><i></i><i></i></div><div class="memory-layout"><section class="memory-browser-skeleton"><i></i><i></i><article></article><article></article><article></article></section><article class="memory-reader-skeleton"><strong></strong><span></span><span></span><span></span></article></div></main>';
}
async function showMemoryWorkspace(){
  const namespace=currentMemoryNamespace;
  const root=document.getElementById('view-content');renderMemoryLoading(root);let records,identity,projects;try{[records,identity,projects]=await Promise.all([conversationRequest('/api/memory?namespace='+encodeURIComponent(namespace)+'&includeArchived=true'),conversationRequest('/api/auth/me'),conversationRequest('/api/projects').catch(()=>[])]);}catch(error){if(currentView!=='memory'||namespace!==currentMemoryNamespace||!root.isConnected)return;root.replaceChildren();const notice=document.createElement('section');notice.className='goal-empty';const heading=document.createElement('h2');heading.textContent='Memory could not be checked';const copy=document.createElement('p');copy.textContent=error.message||'No saved memory was changed.';const retry=document.createElement('button');retry.className='btn';retry.textContent='Try again';retry.onclick=showMemoryWorkspace;notice.append(heading,copy,retry);root.append(notice);return;}
  const canWrite=(identity.user?.permissions||[]).some(value=>['*','memory:*','memory:write'].includes(value));
  if(currentView!=='memory'||namespace!==currentMemoryNamespace)return;
  root.innerHTML='<main class="memory-workspace"><header class="project-hero"><div><span class="forge-topline">WORKSPACE KNOWLEDGE</span><h1>Keep what matters</h1><p>Decisions, lessons, and context you can find again.</p></div><div class="memory-illustration" aria-hidden="true">◇<span>◇</span><i>✳</i></div></header><div class="memory-toolbar"><form class="memory-collection"><label>Collection<input class="form-control" name="namespace" required maxlength="120"></label><button class="btn btn-secondary">Open</button></form><button class="btn btn-secondary" id="memory-export">Export collection</button><button class="btn" id="memory-new">New memory</button></div><p class="memory-disclosure">Saved locally and available to export. Project records tagged chat-context can be supplied to chat when the collection is explicitly enabled. Worker retrieval is separate.</p><div class="memory-layout"><section class="memory-browser" aria-label="Memory records"><input class="form-control" id="memory-search" aria-label="Search memories" placeholder="Search titles, details, or tags"><select class="form-control" id="memory-filter" aria-label="Memory category"><option value="">All categories</option></select><label class="memory-archive-filter"><input type="checkbox" id="memory-archived"> Archived memories</label><p id="memory-count" role="status"></p><div id="memory-results"></div></section><article class="memory-reader" aria-label="Selected memory"></article></div></main>';
  const collection=root.querySelector('[name=namespace]');collection.value=namespace;
  root.querySelector('.memory-collection').onsubmit=event=>{event.preventDefault();currentMemoryNamespace=collection.value.trim()||'general';switchView('memory');};
  const filter=root.querySelector('#memory-filter');for(const [value,label] of Object.entries(memoryCategories)){const option=document.createElement('option');option.value=value;option.textContent=label;filter.append(option);}
  const search=root.querySelector('#memory-search'),list=root.querySelector('#memory-results'),reader=root.querySelector('.memory-reader');let selected=selectedMemoryByCollection.get(namespace)||null;
  function read(record){selected=record.id;selectedMemoryByCollection.set(namespace,record.id);for(const button of list.children)button.setAttribute('aria-pressed',String(button.dataset.id===selected));reader.replaceChildren();const category=document.createElement('span');category.className='forge-topline';category.textContent=memoryCategories[record.category]||record.category;const title=document.createElement('h2');title.textContent=record.title;const date=document.createElement('p');date.className='memory-date';date.textContent='Version '+(record.version||1)+' · Saved '+new Date(record.createdAt).toLocaleString()+(record.updatedAt?' · Updated '+new Date(record.updatedAt).toLocaleString():'');const content=document.createElement('div');content.className='memory-body';content.textContent=record.content;const tags=document.createElement('div');tags.className='memory-tags';for(const tag of record.tags||[]){const chip=document.createElement('span');chip.textContent=tag;tags.append(chip);}reader.append(category,title,date,tags,content);mountMemoryActions(reader,record,canWrite);if(record.projectId||record.taskId){const reference=document.createElement('p');reference.className='memory-date';reference.textContent=[record.projectId&&'Project: '+(projects.find(project=>project.id===record.projectId)?.name||record.projectId),record.taskId&&'Task: '+record.taskId].filter(Boolean).join(' · ');reader.append(reference);}}
  function render(){const query=search.value.toLowerCase().trim();const visible=records.filter(record=>Boolean(record.archived)===root.querySelector('#memory-archived').checked&&(!filter.value||record.category===filter.value)&&[record.title,record.content,...(record.tags||[])].join(' ').toLowerCase().includes(query));list.replaceChildren();root.querySelector('#memory-count').textContent=visible.length+' of '+records.length+' memories';for(const record of visible){const button=document.createElement('button');button.dataset.id=record.id;const title=document.createElement('strong');title.textContent=record.title;const preview=document.createElement('span');preview.textContent=record.content;const category=document.createElement('small');category.textContent=memoryCategories[record.category]||record.category;button.append(category,title,preview);button.onclick=()=>read(record);list.append(button);}if(visible.length)read(visible.find(record=>record.id===selected)||visible[0]);else{reader.innerHTML='<div class="memory-empty"><span aria-hidden="true">◇</span><h2></h2><p></p></div>';reader.querySelector('h2').textContent=records.length?'No matching memories':'A place for useful context';reader.querySelector('p').textContent=records.length?'Try another search or category.':'Save a decision, a lesson, or a project constraint to start your collection.';}}
  search.oninput=render;filter.onchange=render;root.querySelector('#memory-archived').onchange=render;render();
  root.querySelector('#memory-new').disabled=!canWrite;
  root.querySelector('#memory-new').onclick=()=>newWorkspaceMemory();
  root.querySelector('#memory-export').disabled=!records.length;
  root.querySelector('#memory-export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({namespace,exportedAt:new Date().toISOString(),records},null,2)],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='agentforge-memory.json';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
}
function newWorkspaceMemory(record){
  const dialog=document.createElement('dialog');dialog.className='conversation-dialog project-dialog';
  dialog.innerHTML='<form><h2>New memory</h2><p>Save context to this collection for future reference.</p><label>Title<input class="form-control" name="title" required maxlength="200"></label><label>Project scope<select class="form-control" name="project" aria-label="Project scope"><option value="">Workspace reference only</option></select></label><p class="memory-disclosure">To make a project record eligible for opted-in chat context, add the chat-context tag. This may share its text with your configured model provider.</p><label>Category<select class="form-control" name="category"></select></label><label>Details<textarea class="form-control" name="content" required maxlength="40000" rows="8"></textarea></label><label>Tags, separated by commas<input class="form-control" name="tags" maxlength="1000" placeholder="design, release, decision"></label><p class="conversation-feedback" role="status"></p><footer><button type="button" class="btn btn-secondary">Cancel</button><button type="submit" class="btn">Save memory</button></footer></form>';
  const projectSelect=dialog.querySelector('[name=project]');projectSelect.disabled=true;conversationRequest('/api/projects').then(projects=>{if(!dialog.isConnected)return;for(const project of projects.filter(p=>!p.archived||p.id===record?.projectId)){const option=document.createElement('option');option.value=project.id;option.textContent=project.name;projectSelect.append(option);}projectSelect.value=record?.projectId||'';projectSelect.disabled=Boolean(record);}).catch(()=>{dialog.querySelector('.conversation-feedback').textContent='Project scopes unavailable. Retry opening this editor to select a project.';});const namespace=record?.namespace||currentMemoryNamespace;const category=dialog.querySelector('[name=category]');for(const [value,label] of Object.entries(memoryCategories)){const option=document.createElement('option');option.value=value;option.textContent=label;category.append(option);}dialog.querySelector('button[type=button]').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();
  if(record){dialog.querySelector('h2').textContent='Edit memory';for(const field of ['title','content'])dialog.querySelector('[name='+field+']').value=record[field];category.value=record.category;dialog.querySelector('[name=tags]').value=record.tags.join(', ');}
  dialog.querySelector('form').onsubmit=async event=>{event.preventDefault();const button=dialog.querySelector('button[type=submit]');button.disabled=true;try{const saved=await conversationRequest('/api/memory',record?'PATCH':'POST',{...(record?{id:record.id,expectedVersion:record.version||1}:{}),namespace,...(!record&&projectSelect.value?{projectId:projectSelect.value}:{}),category:category.value,title:dialog.querySelector('[name=title]').value,content:dialog.querySelector('[name=content]').value,tags:dialog.querySelector('[name=tags]').value.split(',').map(tag=>tag.trim()).filter(Boolean)});selectedMemoryByCollection.set(namespace,saved.id);dialog.close();if(currentView==='memory')await showMemoryWorkspace();}catch(error){dialog.querySelector('.conversation-feedback').textContent=error.message;button.disabled=false;}};
  document.body.append(dialog);dialog.showModal();dialog.querySelector('input').focus();
}

function mountMemoryActions(reader,record,canWrite){
 const actions=document.createElement('div');actions.className='memory-record-actions';const edit=document.createElement('button');edit.className='btn btn-secondary';edit.textContent='Edit memory';edit.disabled=Boolean(record.archived)||!canWrite;edit.onclick=()=>newWorkspaceMemory(record);const archive=document.createElement('button');archive.className='btn btn-secondary';archive.textContent=record.archived?'Restore memory':'Archive memory';archive.disabled=!canWrite;const feedback=document.createElement('p');feedback.className='conversation-feedback';feedback.setAttribute('role','status');archive.onclick=async()=>{archive.disabled=true;try{await conversationRequest('/api/memory','PATCH',{namespace:record.namespace,id:record.id,expectedVersion:record.version||1,archived:!record.archived});if(currentView==='memory')await showMemoryWorkspace();}catch(error){feedback.textContent=error.message;archive.disabled=false;}};actions.append(edit,archive);reader.append(actions,feedback);
 const origin=document.createElement('p');origin.className='memory-date';origin.textContent='Collection: '+record.namespace+' · Record: '+record.id+(record.updatedBy?' · Last edited by '+record.updatedBy:'');reader.append(origin);
 if(record.revisions?.length){const history=document.createElement('details');history.className='memory-revisions';const summary=document.createElement('summary');summary.textContent='Version history · '+record.revisions.length+(record.revisions.length===1?' previous version':' previous versions');history.append(summary);for(const version of [...record.revisions].reverse()){const item=document.createElement('details');const title=document.createElement('summary');title.textContent='Version '+version.version+' · '+new Date(version.savedAt).toLocaleString()+(version.archived?' · archived':'');const heading=document.createElement('h3');heading.textContent=version.title;const body=document.createElement('pre');body.textContent=version.content;const meta=document.createElement('p');meta.className='memory-date';meta.textContent=(memoryCategories[version.category]||version.category)+' · '+version.tags.join(', ')+(version.actorId?' · '+version.actorId:'');item.append(title,heading,meta,body);history.append(item);}reader.append(history);}
}
`;
