/** Guided presentation of the existing, explicitly simulated migration APIs. */
export const migrationClient = String.raw`
function renderMigrationLoading(root){
 root.innerHTML='<main class="catalog-workspace migration-loading" aria-busy="true" aria-live="polite"><header class="project-hero"><div><span class="forge-topline">BRING YOUR WORK WITH YOU</span><h1>Migration lab</h1><p>Checking the local fixture adapters and their migration boundaries.</p></div><div class="migration-art" aria-hidden="true">◇ <span>→</span> ✳</div></header><div class="migration-layout"><nav class="migration-source-skeleton"><i></i><i></i><i></i><i></i></nav><section class="migration-detail"><div class="migration-detail-skeleton"><strong></strong><span></span><span></span><div><i></i><i></i><i></i></div></div></section></div></main>';
}
function renderMigrationResultLoading(target,operation){
 target.replaceChildren();const skeleton=document.createElement('div');skeleton.className='migration-result-skeleton';skeleton.setAttribute('aria-label','Fixture '+operation+' is loading');skeleton.innerHTML='<strong></strong><div><i></i><i></i><i></i></div><span></span><span></span>';target.append(skeleton);
}
function renderMigrationResultError(target,error,retry){
 target.replaceChildren();const notice=document.createElement('section');notice.className='migration-result-notice';const heading=document.createElement('strong');heading.textContent='This fixture result could not be loaded';const copy=document.createElement('p');copy.textContent=error.message||'Try again.';const button=document.createElement('button');button.type='button';button.className='btn btn-sm btn-secondary';button.textContent='Try again';button.onclick=retry;notice.append(heading,copy,button);target.append(notice);
}
async function showMigrationWorkspace(){
 const root=document.getElementById('view-content');renderMigrationLoading(root);let sources;try{sources=await conversationRequest('/api/migration/sources');}catch(error){if(currentView!=='migration'||!root.isConnected)return;root.replaceChildren();const notice=document.createElement('section');notice.className='goal-empty';const heading=document.createElement('h2');heading.textContent='Migration lab is unavailable';const copy=document.createElement('p');copy.textContent=error.message||'No live source was contacted.';const retry=document.createElement('button');retry.className='btn';retry.textContent='Try again';retry.onclick=showMigrationWorkspace;notice.append(heading,copy,retry);root.append(notice);return;}if(currentView!=='migration')return;
 root.innerHTML='<main class="catalog-workspace"><header class="project-hero"><div><span class="forge-topline">BRING YOUR WORK WITH YOU</span><h1>Migration lab</h1><p>Explore how agent definitions map into AgentForge.</p></div><div class="migration-art" aria-hidden="true">◇ <span>→</span> ✳</div></header><p class="memory-disclosure">Fixture adapters only. These examples do not read a live source or change a production system.</p><div class="migration-layout"><nav aria-label="Migration sources"></nav><section class="migration-detail"><h2></h2><p class="migration-description"></p><div class="migration-actions"></div><div id="migration-results" aria-live="polite"><p>Select an action to inspect the example source.</p></div></section></div></main>';
 const nav=root.querySelector('nav'),detail=root.querySelector('.migration-detail');let selection=null,sequence=0;
 function choose(source){selection=source.id;sequence++;for(const button of nav.children)button.setAttribute('aria-pressed',String(button.dataset.id===source.id));detail.querySelector('h2').textContent=source.name;detail.querySelector('.migration-description').textContent=source.description;detail.querySelector('#migration-results').textContent='Choose Inspect, Plan, or Simulate to explore this fixture.';const actions=detail.querySelector('.migration-actions');actions.replaceChildren();for(const [operation,label] of [['inspect','1 · Inspect'],['plan','2 · Plan'],['dry-run','3 · Simulate'],['import','Import fixture']]){const button=document.createElement('button');button.className='btn btn-secondary';button.textContent=label;button.onclick=()=>run(source,operation,actions);actions.append(button);}}
 async function run(source,operation,actions){const ticket=++sequence;const results=detail.querySelector('#migration-results');for(const button of actions.children)button.disabled=true;renderMigrationResultLoading(results,operation);try{const data=await conversationRequest('/api/migration/'+operation,'POST',{source:source.id});if(ticket!==sequence||selection!==source.id||!results.isConnected)return;results.replaceChildren();const heading=document.createElement('h3');heading.textContent=({inspect:'Discovered in example',plan:'Proposed mapping','dry-run':'Simulation result',import:'Local fixture import result'})[operation];results.append(heading);const stats=document.createElement('div');stats.className='migration-stats';const counts=data.discovered||data.summary||(data.dryRun?{simulatedImports:data.dryRun.simulatedImportsCount,simulatedErrors:data.dryRun.simulatedErrorsCount}:data.result?{imported:data.result.importedCount}:{});for(const [key,value] of Object.entries(counts)){const item=document.createElement('div');const number=document.createElement('strong');number.textContent=String(value);const label=document.createElement('span');label.textContent=key.replace(/Count$/,'').replace(/([A-Z])/g,' $1').toLowerCase();item.append(number,label);stats.append(item);}results.append(stats);
 if(data.dryRun){const status=document.createElement('p');status.className='memory-disclosure';status.textContent=data.dryRun.dryRunPassed?'Fixture simulation passed. This does not verify a real migration.':'Fixture simulation reported issues.';results.append(status);for(const warning of data.dryRun.validationWarnings||[])appendMigrationNote(results,warning);}
 for(const item of data.items||[]){const row=document.createElement('section');row.className='migration-item';const title=document.createElement('strong');title.textContent=item.sourceName+' → '+item.targetName;const status=document.createElement('span');status.textContent=item.status.replaceAll('_',' ').toLowerCase();row.append(title,status);if(item.warning||item.transformDetails){const text=document.createElement('p');text.textContent=item.warning||item.transformDetails;row.append(text);}results.append(row);}
 for(const check of data.verification?.checks||[]){appendMigrationNote(results,(check.passed?'Passed: ':'Needs attention: ')+check.name+' — '+check.details);}
 for(const requirement of data.secretRequirements||[]){appendMigrationNote(results,'Reconnect required: '+requirement.provider+' — '+requirement.description);}
 const raw=document.createElement('details');raw.className='migration-raw';const summary=document.createElement('summary');summary.textContent='Technical result';const pre=document.createElement('pre');pre.textContent=JSON.stringify(data,null,2);raw.append(summary,pre);results.append(raw);
 }catch(error){if(ticket===sequence&&results.isConnected)renderMigrationResultError(results,error,()=>run(source,operation,actions));}finally{for(const button of actions.children)button.disabled=false;}}
 for(const source of sources){const button=document.createElement('button');button.dataset.id=source.id;button.textContent=source.name;button.onclick=()=>choose(source);nav.append(button);}if(sources.length)choose(sources[0]);else detail.textContent='No migration adapters are available.';
}
function appendMigrationNote(root,text){const note=document.createElement('p');note.className='migration-note';note.textContent=text;root.append(note);}
`;
