/** Performance UI uses measured records; it never synthesizes benchmarks. */
export const performanceClient = String.raw`
function comparisonActionLabel(action){return ({HEALTHY:'Within thresholds',WARN_CONTAINMENT:'Review recommended',QUARANTINE:'Quarantine recommended',ROLLBACK:'Rollback recommended'})[action]||'Review recorded result';}
function renderPerformanceLoading(root){
 root.innerHTML='<main class="performance-workspace performance-loading" aria-busy="true" aria-live="polite"><header class="project-hero"><div><span class="forge-topline">MEASURE. COMPARE. IMPROVE.</span><h1>Quality you can inspect.</h1><p>Checking saved baselines, comparisons, and quality evidence.</p></div><div class="quality-art quality-art-skeleton" aria-hidden="true"><i></i><i></i><i></i></div></header><div class="quality-metrics quality-metrics-skeleton"><article><strong></strong><span></span><small></small></article><article><strong></strong><span></span><small></small></article><article><strong></strong><span></span><small></small></article></div><section class="quality-signal quality-signal-skeleton"><strong></strong><span></span><span></span></section><div class="quality-layout"><section class="quality-list-skeleton"><i></i><i></i><i></i></section><aside class="quality-entry quality-form-skeleton"><strong></strong><span></span><span></span><i></i></aside></div></main>';
}
function renderComparisonReceipt(root,report,warning){
 root.replaceChildren();const card=document.createElement('section');card.className='quality-receipt';
 const title=document.createElement('strong');title.textContent='Comparison saved';const label=document.createElement('span');label.className='quality-recommendation';label.textContent=comparisonActionLabel(report.action);
 const detail=document.createElement('p');detail.textContent=report.explanation;const facts=document.createElement('dl');
 for(const [name,value] of [['Pass-rate change',Number.isFinite(report.passRateDriftPct)?report.passRateDriftPct+' pp':'Not measured'],['Latency change',Number.isFinite(report.latencyDriftMs)?report.latencyDriftMs+' ms':'Not measured'],['Regressions',report.regressions?.length||0]]){const row=document.createElement('div'),term=document.createElement('dt'),amount=document.createElement('dd');term.textContent=name;amount.textContent=value;row.append(term,amount);facts.append(row);}
 card.append(title,label,detail,facts);if(warning){const note=document.createElement('p');note.textContent=warning;card.append(note);}root.append(card);
}
function renderQualityTrajectory(root,reports){
 root.replaceChildren();const measured=[...reports].filter(report=>Number.isFinite(report.passRateDriftPct)).sort((a,b)=>Date.parse(a.analyzedAt)-Date.parse(b.analyzedAt)).slice(-12);
 const label=document.createElement('span');label.className='quality-art-label';
 if(!measured.length){label.textContent='No measured comparison trend yet';root.append(label);root.setAttribute('aria-label','No recorded pass-rate comparison trend');return;}
 const width=220,height=76,pad=8;const values=measured.map(report=>report.passRateDriftPct);const extent=Math.max(5,...values.map(value=>Math.abs(value)));const x=index=>pad+(width-pad*2)*(measured.length===1?.5:index/(measured.length-1));const y=value=>height/2-(value/extent)*(height/2-pad);
 const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 '+width+' '+height);svg.setAttribute('aria-hidden','true');const baseline=document.createElementNS('http://www.w3.org/2000/svg','line');baseline.setAttribute('x1',String(pad));baseline.setAttribute('x2',String(width-pad));baseline.setAttribute('y1',String(height/2));baseline.setAttribute('y2',String(height/2));baseline.setAttribute('class','quality-art-baseline');svg.append(baseline);const polyline=document.createElementNS('http://www.w3.org/2000/svg','polyline');polyline.setAttribute('points',measured.map((report,index)=>x(index)+','+y(report.passRateDriftPct)).join(' '));polyline.setAttribute('class','quality-art-line');svg.append(polyline);for(const [index,report] of measured.entries()){const point=document.createElementNS('http://www.w3.org/2000/svg','circle');point.setAttribute('cx',String(x(index)));point.setAttribute('cy',String(y(report.passRateDriftPct)));point.setAttribute('r','3');point.setAttribute('class',report.passRateDriftPct<0?'quality-art-point regression':'quality-art-point');svg.append(point);}label.textContent='Pass-rate change · '+measured.length+' recorded comparison'+(measured.length===1?'':'s');root.append(svg,label);root.setAttribute('role','img');root.setAttribute('aria-label','Recorded pass-rate comparison trend: '+values.map(value=>(value>0?'+':'')+value+' percentage points').join(', '));
}
async function showPerformanceWorkspace(){
 const root=document.getElementById('view-content');
 renderPerformanceLoading(root);let baselines,reports,qualityStatus;try{[baselines,reports,qualityStatus]=await Promise.all([conversationRequest('/api/drift/baselines'),conversationRequest('/api/drift/reports'),conversationRequest('/api/drift/status')]);}catch(error){if(currentView!=='benchmarks'||!root.isConnected)return;root.replaceChildren();const notice=document.createElement('section');notice.className='goal-empty';const heading=document.createElement('h2');heading.textContent='Quality records could not be checked';const copy=document.createElement('p');copy.textContent=error.message||'No comparison was recorded.';const retry=document.createElement('button');retry.className='btn';retry.textContent='Try again';retry.onclick=showPerformanceWorkspace;notice.append(heading,copy,retry);root.append(notice);return;}if(currentView!=='benchmarks')return;
 root.innerHTML='<main class="performance-workspace"><header class="project-hero"><div><span class="forge-topline">MEASURE. COMPARE. IMPROVE.</span><h1>Quality you can inspect.</h1><p>Compare recorded evaluations against measured baselines. A saved decision is evidence to review, not proof that a runtime action was executed.</p></div><div class="quality-art" aria-label="Checking recorded comparison trend"></div></header><div class="quality-metrics"></div><section class="quality-evidence-status" aria-label="Quality evidence storage"></section><section class="quality-signal" aria-label="Measured quality snapshot"></section><div class="quality-layout"><section><h2>Measured baselines</h2><div class="quality-baselines"></div><h2>Comparison history</h2><div class="quality-history"></div></section><aside class="quality-entry"><h2>Record a comparison</h2><p>Use results from a completed evaluation. This form records observations; it does not run a model.</p><div class="quality-form"></div></aside></div></main>';
 renderQualityTrajectory(root.querySelector('.quality-art'),reports);
 const storage=root.querySelector('.quality-evidence-status');const durable=qualityStatus?.persistenceMode==='local_json';const storageIcon=document.createElement('span');storageIcon.className='quality-evidence-icon';storageIcon.textContent=durable?'◈':'○';const storageCopy=document.createElement('div');const storageTitle=document.createElement('strong');storageTitle.textContent=durable?'Quality evidence is saved locally':'Quality evidence is temporary';const storageDetail=document.createElement('p');storageDetail.textContent=durable?'Baselines and comparison reports persist in this local workspace and are linked to the audit ledger.':'This workspace is running in memory, so quality records disappear when it stops. Use a local workspace file before relying on a comparison.';storageCopy.append(storageTitle,storageDetail);const storageCount=document.createElement('span');storageCount.className='quality-evidence-count';storageCount.textContent=(qualityStatus?.baselineCount||0)+' baseline'+((qualityStatus?.baselineCount||0)===1?'':'s')+' · '+(qualityStatus?.comparisonCount||0)+' comparison'+((qualityStatus?.comparisonCount||0)===1?'':'s');storage.append(storageIcon,storageCopy,storageCount);
 const decisions=reports.filter(r=>r.action==='QUARANTINE'||r.action==='ROLLBACK');
 for(const [label,value,detail] of [['Baselines',baselines.length,'Recorded reference measurements'],['Comparisons',reports.length,'Saved evaluations'],['Containment decisions',decisions.length,'Review execution separately']]){const card=document.createElement('div');card.className='quality-metric';const name=document.createElement('span'),number=document.createElement('strong'),hint=document.createElement('small');name.textContent=label;number.textContent=value;hint.textContent=detail;card.append(name,number,hint);root.querySelector('.quality-metrics').append(card);}
 const signal=root.querySelector('.quality-signal');const signalHead=document.createElement('div');signalHead.className='quality-signal-head';const signalTitle=document.createElement('div');const signalKicker=document.createElement('span');signalKicker.className='forge-topline';signalKicker.textContent='OBSERVED SIGNALS';const signalHeading=document.createElement('h2');signalHeading.textContent='A readable view of recorded evidence.';const signalCopy=document.createElement('p');signalCopy.textContent=baselines.length?'Every value below is calculated from your saved baseline records.':'Add a measured baseline to populate this view. AgentForge does not invent a quality score.';signalTitle.append(signalKicker,signalHeading,signalCopy);const signalNote=document.createElement('span');signalNote.className='quality-signal-note';signalNote.textContent=baselines.length?'Measured inputs':'No inputs yet';signalHead.append(signalTitle,signalNote);signal.append(signalHead);
 const signalRows=document.createElement('div');signalRows.className='quality-signal-rows';const average=field=>{const values=baselines.map(item=>item[field]).filter(value=>Number.isFinite(value));return values.length?values.reduce((sum,value)=>sum+value,0)/values.length:null;};const passRate=average('passRatePct'),toolAccuracy=average('toolAccuracyPct');for(const [label,value,detail] of [['Average pass rate',passRate,'Across recorded baseline runs'],['Average tool accuracy',toolAccuracy,'Across recorded baseline runs']]){const row=document.createElement('article');row.className='quality-signal-row';const copy=document.createElement('div');const name=document.createElement('strong'),hint=document.createElement('span');name.textContent=label;hint.textContent=detail;copy.append(name,hint);const valueBlock=document.createElement('div');valueBlock.className='quality-signal-value';const amount=document.createElement('strong');amount.textContent=Number.isFinite(value)?Math.round(value*10)/10+'%':'Not measured';valueBlock.append(amount);if(Number.isFinite(value)){const meter=document.createElement('meter');meter.min=0;meter.max=100;meter.value=value;meter.setAttribute('aria-label',label+': '+amount.textContent);valueBlock.append(meter);}row.append(copy,valueBlock);signalRows.append(row);}const latest=reports.at(-1);const latestRow=document.createElement('article');latestRow.className='quality-signal-row';const latestCopy=document.createElement('div');const latestName=document.createElement('strong'),latestHint=document.createElement('span');latestName.textContent='Latest comparison';latestHint.textContent=latest?'Saved '+new Date(latest.analyzedAt).toLocaleString():'No comparison has been recorded';latestCopy.append(latestName,latestHint);const latestValue=document.createElement('strong');latestValue.className='quality-signal-decision';latestValue.textContent=latest?comparisonActionLabel(latest.action):'Waiting for evidence';latestRow.append(latestCopy,latestValue);signalRows.append(latestRow);signal.append(signalRows);
 const list=root.querySelector('.quality-baselines');
 for(const baseline of baselines){const card=document.createElement('article');card.className='quality-baseline';const title=document.createElement('h3');title.textContent=baseline.targetId;const meta=document.createElement('p');meta.textContent=baseline.targetType+' · '+baseline.targetVersion;card.append(title,meta);
 for(const [label,value,unit] of [['Pass rate',baseline.passRatePct,'%'],['Tool accuracy',baseline.toolAccuracyPct,'%'],['Average latency',baseline.avgLatencyMs,' ms']]){const row=document.createElement('div');row.className='quality-measure';const name=document.createElement('span'),amount=document.createElement('strong');name.textContent=label;amount.textContent=typeof value==='number'?value+unit:'Not measured';row.append(name,amount);if(unit==='%'&&Number.isFinite(value)){const meter=document.createElement('meter');meter.min=0;meter.max=100;meter.value=value;meter.setAttribute('aria-label',label);row.append(meter);}card.append(row);}list.append(card);}
 if(!baselines.length)list.innerHTML='<div class="quality-empty"><span aria-hidden="true">◎</span><h3>No measured baseline yet</h3><p>Connect a reviewed evaluation source and record observed results before comparing performance. AgentForge will not fabricate a starting score.</p></div>';
 const history=root.querySelector('.quality-history');for(const report of [...reports].reverse()){const card=document.createElement('article');card.className='quality-decision';const title=document.createElement('h3'),body=document.createElement('p'),change=document.createElement('small');title.textContent=comparisonActionLabel(report.action)+' · '+report.targetId;body.textContent=report.explanation;const delta=report.passRateDriftPct;change.textContent='Pass-rate change: '+(Number.isFinite(delta)?(delta>0?'+':'')+delta+' percentage points':'Not measured')+' · Latency change: '+(Number.isFinite(report.latencyDriftMs)?report.latencyDriftMs+' ms':'Not measured');card.append(title,body,change);const version=document.createElement('p');version.className='quality-version';version.textContent=report.baselineVersion+' → '+report.candidateVersion+' · '+new Date(report.analyzedAt).toLocaleString();card.append(version);
if(Number.isFinite(delta)){const chart=document.createElement('div');chart.className='quality-delta';chart.setAttribute('role','img');chart.setAttribute('aria-label','Pass-rate difference from baseline: '+delta+' percentage points');const axis=document.createElement('span');axis.className='quality-delta-axis';const bar=document.createElement('span');bar.className='quality-delta-bar '+(delta<0?'regression':'improvement');const width=Math.min(100,Math.abs(delta))/2;bar.style.width=width+'%';bar.style.left=(delta<0?50-width:50)+'%';chart.append(axis,bar);card.append(chart);const labels=document.createElement('div');labels.className='quality-delta-labels';for(const text of ['−100 pp','Baseline','+100 pp']){const label=document.createElement('span');label.textContent=text;labels.append(label);}card.append(labels);}
const boundary=document.createElement('p');boundary.className='memory-disclosure';boundary.textContent='Recorded recommendation. Check runtime activity to confirm whether any containment action occurred.';card.append(boundary);history.append(card);}if(!reports.length)history.innerHTML='<p class="quality-empty">No comparisons recorded. Your evaluation decisions will appear here.</p>';
 const form=root.querySelector('.quality-form');if(!baselines.length){form.innerHTML='<p class="memory-disclosure">A measured baseline is required before recording a comparison.</p>';return;}
 form.innerHTML='<label for="drift-target">Baseline</label><select id="drift-target" class="form-control"></select><label for="drift-version">Candidate version</label><input id="drift-version" class="form-control" placeholder="Version evaluated"><label for="drift-passrate">Observed pass rate (%)</label><input id="drift-passrate" class="form-control" type="number" min="0" max="100" step="0.5"><label for="drift-latency">Average latency (ms)</label><input id="drift-latency" class="form-control" type="number" min="0"><label><input id="drift-misuse" type="checkbox"> Observed tool misuse</label><label><input id="drift-hallucination" type="checkbox"> Observed unsupported claim</label><button class="btn">Record comparison</button><div id="drift-eval-result" role="status"></div>';
 for(const baseline of baselines){const option=document.createElement('option');option.value=baseline.targetId+'|'+baseline.targetType;option.textContent=baseline.targetId+' · '+baseline.targetVersion;form.querySelector('select').append(option);}form.querySelector('button').onclick=executeDriftEvaluation;
}
`;
