/** Local presentation preferences and live connection readiness. */
export const preferencesClient = String.raw`
let workspacePreferences={density:'comfortable',text:'standard',motion:'system'};
try{const saved=JSON.parse(localStorage.getItem('agentforge-appearance')||'{}');for(const [key,values] of Object.entries({density:['comfortable','compact'],text:['standard','large'],motion:['system','reduced']})){if(values.includes(saved[key]))workspacePreferences[key]=saved[key];}}catch{}
function applyWorkspacePreferences(){for(const [key,value] of Object.entries(workspacePreferences))document.documentElement.dataset[key]=value;}
applyWorkspacePreferences();
async function showWorkspaceSettings(){
  const root=document.getElementById('view-content');
  root.innerHTML='<main class="preferences-workspace"><header class="project-hero"><div><span class="forge-topline">YOUR WORKSPACE</span><h1>Make it yours</h1><p>A comfortable place to work, with clear control over what is connected.</p></div><div class="preferences-art" aria-hidden="true"><span>✳</span><i></i><i></i><i></i></div></header><div class="preferences-layout"><nav aria-label="Settings sections"><a href="#experience-section">Experience</a><a href="#appearance-section">Appearance</a><a href="#connections-section">Connections</a><a href="#access-section">People & access</a><a href="#storage-section">Storage & history</a><a href="#shortcuts-section">Keyboard shortcuts</a></nav><div class="preferences-sections"><section id="experience-section"><h2>How do you want to work?</h2><p>Choose a home surface for this workspace. Every path uses the same projects, teammates, tasks, and history, so you can change it at any time.</p><div id="experience-options" class="experience-options" aria-live="polite"></div><p id="experience-status" role="status"></p></section><section id="appearance-section"><h2>Appearance</h2><p>Saved in this browser. Changes apply immediately.</p><div id="appearance-options"></div><p id="appearance-status" role="status"></p></section><section id="connections-section"><h2>Connections</h2><p>Each connection is configured separately. Appearance changes never grant agent access.</p><div id="settings-readiness">Checking runtime…</div></section><section id="access-section"><h2>People & access</h2><p>See who can work in this workspace and add teammates with a clear role. Roles are enforced by the local control plane.</p><div id="settings-access">Checking workspace access…</div></section><section id="storage-section"><h2>Storage & history</h2><p>Conversations, projects, edits, and branches are saved in the local workspace. Export a conversation from its toolbar to keep a portable copy.</p><p>Local workspace snapshots stay on this device. Teams that need shared production storage should connect a reviewed storage provider before relying on multi-user access.</p><button class="btn btn-secondary" id="settings-audit">View activity & audit</button></section><section id="shortcuts-section"><h2>Keyboard shortcuts</h2><dl class="shortcut-list"><div><dt>Search workspace</dt><dd><kbd>Ctrl / ⌘</kbd> <kbd>K</kbd></dd></div><div><dt>Send a message</dt><dd><kbd>Enter</kbd></dd></div><div><dt>New line</dt><dd><kbd>Shift</kbd> <kbd>Enter</kbd></dd></div><div><dt>Close dialog</dt><dd><kbd>Esc</kbd></dd></div></dl></section></div></div></main>';
  const shortcuts=root.querySelector('#shortcuts-section');
  const shortcutChoice=document.createElement('label');shortcutChoice.className='send-shortcut-choice';shortcutChoice.textContent='Send messages with';
  const shortcutSelect=document.createElement('select');shortcutSelect.className='form-control';shortcutSelect.setAttribute('aria-label','Send messages with');shortcutSelect.append(new Option('Enter','enter'),new Option('Ctrl / ⌘ + Enter','modifier-enter'));shortcutSelect.value=conversationSendShortcut;
  const shortcutFeedback=document.createElement('p');shortcutFeedback.setAttribute('role','status');
  const updateShortcuts=()=>{const values=shortcuts.querySelectorAll('.shortcut-list dd');values[1].textContent=conversationSendShortcut==='modifier-enter'?'Ctrl / ⌘ + Enter':'Enter';values[2].textContent=conversationSendShortcut==='modifier-enter'?'Enter or Shift + Enter':'Shift + Enter';};
  shortcutSelect.onchange=()=>{conversationSendShortcut=shortcutSelect.value;updateShortcuts();try{localStorage.setItem('agentforge-send-shortcut',conversationSendShortcut);shortcutFeedback.textContent='Send shortcut saved in this browser.';}catch{shortcutFeedback.textContent='Applied for this session; browser storage is unavailable.';}};
  shortcutChoice.append(shortcutSelect);shortcuts.insertBefore(shortcutChoice,shortcuts.querySelector('dl'));shortcuts.append(shortcutFeedback);updateShortcuts();
  const options=root.querySelector('#appearance-options');
  const experienceOptions=root.querySelector('#experience-options');
  const experienceStatus=root.querySelector('#experience-status');
  const experiences=[
    ['command','Run an autonomous team','A decision-first command center for operating agents, reviewing work, and keeping approvals moving.','Command room','home'],
    ['workspace','Work alongside agents','A collaboration-led workspace for conversations, projects, and coordinated team work.','Conversations','messages'],
    ['studio','Build and test agents','A focused builder surface for configuring agents, testing runs, and inspecting evidence.','Agent studio','studio']
  ];
  let selectedExperience='workspace';
  const drawExperiences=()=>{experienceOptions.replaceChildren();for(const [value,title,detail,destination,view] of experiences){const card=document.createElement('button');card.type='button';card.className='experience-choice';card.setAttribute('aria-pressed',String(value===selectedExperience));const label=document.createElement('span');label.className='experience-choice-label';label.textContent=title;const copy=document.createElement('span');copy.className='experience-choice-copy';copy.textContent=detail;const go=document.createElement('span');go.className='experience-choice-go';go.textContent='Open '+destination+' →';card.append(label,copy,go);card.onclick=async()=>{card.disabled=true;experienceStatus.textContent='Saving workspace experience…';try{const response=await fetch('/api/workspaces/ws-default',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({experience:value})});const saved=await response.json();if(!response.ok)throw new Error(saved.error||'Could not save the workspace experience.');selectedExperience=saved.experience;drawExperiences();void refreshWorkspaceExperience();experienceStatus.textContent='Saved. Your projects, people, work, and history are unchanged.';setTimeout(()=>switchView(view),180);}catch(error){experienceStatus.textContent=error.message||'Could not save the workspace experience.';}finally{card.disabled=false;}};experienceOptions.append(card);}};
  try{const workspaceState=await conversationRequest('/api/workspace');selectedExperience=workspaceState.workspace?.experience||'workspace';}catch{experienceStatus.textContent='Workspace experience could not be loaded. You can try again from Settings.';}drawExperiences();
  for(const [key,title,description,choices] of [
    ['density','Layout density','Choose the space between navigation and work items.',[['comfortable','Comfortable'],['compact','Compact']]],
    ['text','Conversation text','Increase the size of messages and the composer.',[['standard','Standard'],['large','Larger']]],
    ['motion','Animation','Reduce motion throughout the workspace.',[['system','Follow system'],['reduced','Reduced']]]
  ]){
    const row=document.createElement('div');row.className='preference-row';const label=document.createElement('div');const name=document.createElement('h3');name.textContent=title;const detail=document.createElement('p');detail.textContent=description;label.append(name,detail);
    const group=document.createElement('div');group.className='preference-choices';group.setAttribute('role','group');group.setAttribute('aria-label',title);
    for(const [value,text] of choices){const button=document.createElement('button');button.textContent=text;button.setAttribute('aria-pressed',String(workspacePreferences[key]===value));button.onclick=()=>{workspacePreferences[key]=value;applyWorkspacePreferences();for(const item of group.children)item.setAttribute('aria-pressed',String(item===button));try{localStorage.setItem('agentforge-appearance',JSON.stringify(workspacePreferences));root.querySelector('#appearance-status').textContent='Appearance saved.';}catch{root.querySelector('#appearance-status').textContent='Applied for this session; browser storage is unavailable.';}};group.appendChild(button);}row.append(label,group);options.appendChild(row);
  }
  root.querySelector('#settings-audit').onclick=()=>switchView('activity');
  const channels=document.createElement('div');channels.className='connection-preference';const channelCopy=document.createElement('div');const channelTitle=document.createElement('strong');channelTitle.textContent='Direct Telegram connection';const channelHelp=document.createElement('p');channelHelp.textContent='AgentForge connects directly through its own transport. The easiest setup uses a BotFather token; an authenticated MTProto user session remains available for advanced deployments.';channelCopy.append(channelTitle,channelHelp);const channelStatus=document.createElement('p');channelStatus.id='native-telegram-status';channelStatus.textContent='Checking Telegram transport…';channelCopy.append(channelStatus);channels.append(channelCopy);root.querySelector('#connections-section').append(channels);
  try{const runtime=await conversationRequest('/api/setup-guide/channel-runtime');const session=runtime.nativeTelegramSession;const bot=runtime.telegramBotApi;const slack=runtime.nativeSlackSocketMode;if(bot?.configured){channelStatus.textContent='Configured · AgentForge-owned BotFather transport is ready.';channelStatus.className='status-good';}else if(session?.configured){channelStatus.textContent='Configured · direct MTProto transport will start at runtime.';channelStatus.className='status-good';}else{channelStatus.textContent='Not configured · add a BotFather token or MTProto session.';}if(slack?.configured){channelStatus.textContent+=' Slack Socket Mode configured.';}}catch{channelStatus.textContent='Telegram transport status unavailable.';}
  const accessTarget=root.querySelector('#settings-access');
  try{
    const [auth,users]=await Promise.all([conversationRequest('/api/auth/me'),conversationRequest('/api/users')]);
    if(!accessTarget.isConnected)return;
    accessTarget.replaceChildren();
    const summary=document.createElement('p');summary.className='form-hint';summary.textContent='Signed in as '+(auth.user?.displayName||auth.user?.username||'local user')+' · '+(auth.user?.role||'member')+'.';accessTarget.append(summary);
    const list=document.createElement('div');list.className='connection-preference';
    const canManageRoles=auth.user?.role==='owner';
    for(const user of users){const row=document.createElement('div');row.className='connection-preference';const copy=document.createElement('div');const name=document.createElement('strong');name.textContent=user.displayName||user.username;const detail=document.createElement('p');detail.textContent='@'+user.username+' · '+user.role+(user.status&&user.status!=='active'?' · '+user.status:'');copy.append(name,detail);row.append(copy);
      if(canManageRoles&&user.id!==auth.user?.id&&user.role!=='owner'){const controls=document.createElement('div');controls.className='settings-access-controls';const select=document.createElement('select');select.setAttribute('aria-label','Role for '+(user.displayName||user.username));for(const value of ['operator','viewer','engineer','admin'])select.append(new Option(value[0].toUpperCase()+value.slice(1),value));select.value=user.role;const save=document.createElement('button');save.type='button';save.className='btn btn-sm btn-secondary';save.textContent='Save role';save.onclick=async()=>{save.disabled=true;try{const response=await fetch('/api/users/'+encodeURIComponent(user.id),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({role:select.value})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not update the role.');await showWorkspaceSettings();}catch(error){save.textContent=error.message||'Could not update';}finally{save.disabled=false;}};const remove=document.createElement('button');remove.type='button';remove.className='btn btn-sm btn-danger';remove.textContent='Remove';remove.onclick=async()=>{if(!confirm('Remove '+(user.displayName||user.username)+' from this workspace?'))return;remove.disabled=true;try{const response=await fetch('/api/users/'+encodeURIComponent(user.id),{method:'DELETE'});const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not remove the teammate.');await showWorkspaceSettings();}catch(error){remove.textContent=error.message||'Could not remove';}finally{remove.disabled=false;}};controls.append(select,save,remove);row.append(controls);}
      list.append(row);}accessTarget.append(list);
    if(auth.user?.role==='owner'||auth.user?.role==='admin'){
      const form=document.createElement('form');form.className='settings-access-form';form.noValidate=true;
      const heading=document.createElement('strong');heading.textContent='Add a teammate';form.append(heading);
      const username=document.createElement('input');username.required=true;username.maxLength=120;username.autocomplete='off';username.placeholder='Username';username.setAttribute('aria-label','Username');
      const displayName=document.createElement('input');displayName.required=true;displayName.maxLength=120;displayName.placeholder='Name';displayName.setAttribute('aria-label','Name');
      const role=document.createElement('select');role.setAttribute('aria-label','Workspace role');for(const value of ['operator','viewer','engineer','admin'])role.append(new Option(value[0].toUpperCase()+value.slice(1),value));
      const submit=document.createElement('button');submit.type='submit';submit.className='btn btn-sm';submit.textContent='Add teammate';const feedback=document.createElement('p');feedback.setAttribute('role','status');form.append(username,displayName,role,submit,feedback);form.onsubmit=async event=>{event.preventDefault();submit.disabled=true;feedback.textContent='Adding teammate…';try{const response=await fetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:username.value.trim(),displayName:displayName.value.trim(),role:role.value})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not add the teammate.');feedback.textContent='Added '+result.displayName+'.';await showWorkspaceSettings();}catch(error){feedback.textContent=error.message||'Could not add the teammate.';}finally{submit.disabled=false;}};accessTarget.append(form);
    }
  }catch(error){if(accessTarget.isConnected)accessTarget.textContent='Workspace access could not be loaded. '+(error.message||'Try again.');}  const target=root.querySelector('#settings-readiness');
  try{const harness=await conversationRequest('/api/harnesses');if(!target.isConnected)return;target.replaceChildren();
    const ready=harness.runtime.readiness?.capabilities||{};
    for(const [name,available,view,description] of [['Model planning',ready.modelPlanning,'models','Review model providers and routing.'],['Isolated execution',ready.isolatedCompute,'compute','Review environments for running work.'],['Verification',ready.realVerification,'harnesses','Review the checks required before completion.'],['Evidence collection',ready.evidenceCollection,'harnesses','Review how results are retained.']]){
      const row=document.createElement('div');row.className='connection-preference';const text=document.createElement('div');const heading=document.createElement('strong');heading.textContent=name;const detail=document.createElement('p');detail.textContent=description;text.append(heading,detail);const button=document.createElement('button');button.className='btn btn-sm btn-secondary';button.textContent=available?'Ready · Review':'Not connected · Review';button.onclick=()=>switchView(view);row.append(text,button);target.appendChild(row);
    }
  }catch(error){if(target.isConnected)target.textContent='Connection status could not be loaded: '+error.message;}
}
let inboxLoadVersion=0;
function renderInboxLoading(){
  const root=document.createElement('main');root.className='action-inbox inbox-loading';root.setAttribute('aria-busy','true');root.setAttribute('aria-live','polite');
  root.innerHTML='<header class="project-hero"><div><span class="forge-topline">YOUR ATTENTION</span><h1>What needs you</h1><p>Checking saved decisions and work that needs attention.</p></div><div class="inbox-count-graphic inbox-count-skeleton" aria-hidden="true"></div></header><section class="inbox-next inbox-next-skeleton" aria-label="Loading recommended next action"><span></span><div><strong></strong><p></p><p></p></div><i></i></section><div class="inbox-filter-skeleton" aria-hidden="true"><span></span><span></span><span></span></div><section class="inbox-record-skeletons" aria-label="Loading inbox records"><article><span></span><div><strong></strong><p></p><small></small></div></article><article><span></span><div><strong></strong><p></p><small></small></div></article></section>';
  return root;
}
async function showActionInbox(){
  const version=++inboxLoadVersion;let items;
  const container=document.getElementById('view-content');
  container.replaceChildren(renderInboxLoading());
  try{items=await conversationRequest('/api/inbox');}catch(error){
    if(version!==inboxLoadVersion||currentView!=='inbox')return;
    container.replaceChildren();const panel=document.createElement('section');panel.className='review-empty';panel.setAttribute('role','alert');
    const title=document.createElement('h2');title.textContent='Your inbox could not be checked';const detail=document.createElement('p');detail.textContent='This does not mean your work is clear. Try again to load decisions and issues.';
    const retry=document.createElement('button');retry.className='btn';retry.textContent='Try again';retry.onclick=showActionInbox;panel.append(title,detail,retry);container.append(panel);return;
  }
  if(version!==inboxLoadVersion||currentView!=='inbox')return;
  const root=document.getElementById('view-content');root.innerHTML='<main class="action-inbox"><header class="project-hero"><div><span class="forge-topline">YOUR ATTENTION</span><h1>What needs you</h1><p>Decisions and issues from your saved work, gathered in one place.</p></div><div class="inbox-count-graphic" aria-hidden="true"></div></header><section class="inbox-next" aria-label="Recommended next action"></section><div class="review-filters" role="group" aria-label="Inbox filter"></div><div class="inbox-records"></div></main>';
  root.querySelector('.inbox-count-graphic').textContent=String(items.length);
  const filters=root.querySelector('.review-filters');const list=root.querySelector('.inbox-records');
  const priority={critical:0,warning:1,info:2};
  const nextItem=[...items].sort((left,right)=>(priority[left.severity]??3)-(priority[right.severity]??3)||new Date(left.timestamp)-new Date(right.timestamp))[0];
  const nextPanel=root.querySelector('.inbox-next');
  if(nextItem){
    const eyebrow=document.createElement('span');eyebrow.className='forge-topline';eyebrow.textContent='START HERE';
    const copy=document.createElement('div');const title=document.createElement('h2');title.textContent=nextItem.title;const detail=document.createElement('p');detail.textContent=nextItem.description;copy.append(title,detail);
    const action=document.createElement('button');action.className='btn';
    const isTask=nextItem.type==='task_failed'||nextItem.type==='task_completed';
    action.textContent=nextItem.type==='approval_needed'?'Review decision':isTask?'Inspect task':'Open activity';
    action.onclick=async()=>{if(nextItem.type==='approval_needed'){requestedApprovalId=nextItem.sourceId;switchView('approvals');return;}if(!isTask){switchView('activity');return;}action.disabled=true;try{const task=await conversationRequest('/api/tasks/'+encodeURIComponent(nextItem.sourceId));if(nextPanel.isConnected)openWorkDetail(task);}catch{detail.textContent='This task could not be loaded. Try again; no task was changed.';}finally{action.disabled=false;}};
    nextPanel.append(eyebrow,copy,action);
  }else nextPanel.innerHTML='<div><span class="forge-topline">ALL CLEAR</span><h2>No saved decisions or issues need attention.</h2><p>New work and review requests will appear here when they are recorded.</p></div>';
  function render(filter){list.replaceChildren();const visible=items.filter(item=>filter==='all'||(filter==='decisions'?item.type==='approval_needed':item.type!=='approval_needed'));
    if(!visible.length){list.innerHTML='<div class="review-empty"><span>✓</span><h2>You’re clear here</h2><p>No matching items need your attention.</p></div>';return;}
    for(const item of visible){const card=document.createElement('article');card.className='inbox-record';const marker=document.createElement('span');marker.className='inbox-marker '+(item.severity==='critical'?'critical':'');marker.textContent=item.type==='approval_needed'?'◇':'!';const body=document.createElement('div');const heading=document.createElement('h2');heading.textContent=item.title;const description=document.createElement('p');description.textContent=item.description;const meta=document.createElement('small');meta.textContent=String(item.severity||'info')+' · '+new Date(item.timestamp).toLocaleString();body.append(heading,description,meta);card.append(marker,body);if(item.actionable||item.type==='task_completed'){
 const action=document.createElement('button');action.className='btn btn-sm btn-secondary';
 const isTask=item.type==='task_failed'||item.type==='task_completed';
 action.textContent=item.type==='approval_needed'?'Review decision':isTask?'Inspect task':'Inspect activity';
 action.onclick=async()=>{if(!isTask){if(item.type==='approval_needed')requestedApprovalId=item.sourceId;switchView(item.type==='approval_needed'?'approvals':'activity');return;}action.disabled=true;
  try{const task=await conversationRequest('/api/tasks/'+encodeURIComponent(item.sourceId));if(!card.isConnected)return;openWorkDetail(task);}
  catch{let warning=card.querySelector('[role=alert]');if(!warning){warning=document.createElement('p');warning.setAttribute('role','alert');body.append(warning);}warning.textContent='This task could not be loaded. Try again; no task was changed.';}
  finally{action.disabled=false;}
 };card.appendChild(action);
}list.appendChild(card);}
  }
  for(const [value,label] of [['all','All items'],['decisions','Decisions'],['issues','Issues & updates']]){const button=document.createElement('button');button.className='btn btn-secondary';const count=items.filter(item=>value==='all'||(value==='decisions'?item.type==='approval_needed':item.type!=='approval_needed')).length;button.textContent=label+' · '+count;button.setAttribute('aria-pressed',String(value==='all'));button.onclick=()=>{for(const child of filters.children)child.setAttribute('aria-pressed',String(child===button));render(value);};filters.appendChild(button);}render('all');
}
`;
