export const projectFilesClient = String.raw`
function renderProjectFileLoading(target,label){
 target.replaceChildren();const skeleton=document.createElement('div');skeleton.className='project-file-skeleton';skeleton.setAttribute('aria-label',label+' is loading');skeleton.innerHTML='<article><i></i><div><strong></strong><span></span><span></span></div></article><article><i></i><div><strong></strong><span></span></div></article><article><i></i><div><strong></strong><span></span><span></span></div></article>';target.append(skeleton);
}
function renderProjectFileError(target,label,error,retry){
 target.replaceChildren();const notice=document.createElement('section');notice.className='project-file-notice';const heading=document.createElement('strong');heading.textContent='Could not load '+label;const copy=document.createElement('p');copy.textContent=error.message||'Try again.';const button=document.createElement('button');button.className='btn btn-sm btn-secondary';button.type='button';button.textContent='Try again';button.onclick=retry;notice.append(heading,copy,button);target.append(notice);
}
function mountProjectFiles(project,root){
 const panel=document.createElement('section');panel.className='connection-panel project-files-panel';panel.innerHTML='<div class="connection-panel-heading"><div><h2>Project files</h2><p class="memory-disclosure">Browse source files in your connected folder.</p></div><button class="btn btn-secondary" data-connect></button></div><div class="project-files-content"></div>';
 root.append(panel);const action=panel.querySelector('[data-connect]'),content=panel.querySelector('.project-files-content');action.textContent=project.repositoryAccess?'Disconnect':'Connect folder';action.disabled=Boolean(project.archived);
 action.onclick=async()=>{if(!project.repositoryAccess){openProjectFolderConnection(project);return;}action.disabled=true;try{await conversationRequest('/api/projects/'+project.id+'/repository','DELETE');await showProjects();}catch(error){content.textContent=error.message;action.disabled=false;}};
 if(!project.repositoryAccess){content.className+=' project-files-empty';content.innerHTML='<div class="project-files-glyph" aria-hidden="true">⌘</div><h3>Your code, close at hand.</h3><p>Connect a project folder to browse its files here. Access is read-only and does not send file contents to a model.</p>';return;}
 content.innerHTML='<div class="project-files-scope"></div><div class="project-files-layout"><nav aria-label="Project folders"><div class="project-files-breadcrumb"></div><input class="form-control" aria-label="Filter this folder" placeholder="Filter this folder…"><div class="project-file-list"></div><p class="project-files-note"></p></nav><section class="project-file-reader"><div class="project-file-reader-head"><strong>Choose a file</strong><button class="btn btn-sm btn-secondary" disabled>Copy</button></div><div class="project-file-content">Select a text or source file to preview it.</div></section></div>';
 content.querySelector('.project-files-scope').textContent='Read-only · '+project.repositoryAccess.rootPath;
 const readerHead=content.querySelector('.project-file-reader-head');
 const wrap=document.createElement('button');wrap.className='btn btn-sm btn-secondary';wrap.type='button';wrap.textContent='Wrap lines';wrap.setAttribute('aria-pressed','false');wrap.disabled=true;
 const stats=document.createElement('span');stats.className='project-file-stats';stats.setAttribute('role','status');readerHead.after(stats);readerHead.append(wrap);
 let wrapped=false;try{wrapped=localStorage.getItem('agentforge-file-wrap')==='true';}catch{}
 const applyWrap=()=>{content.querySelector('.project-file-content').classList.toggle('wrap-lines',wrapped);wrap.setAttribute('aria-pressed',String(wrapped));};applyWrap();
 wrap.onclick=()=>{wrapped=!wrapped;applyWrap();try{localStorage.setItem('agentforge-file-wrap',String(wrapped));}catch{}};
 let entries=[],directory='',loadVersion=0,previewVersion=0;
 const filter=content.querySelector('input'),list=content.querySelector('.project-file-list'),reader=content.querySelector('.project-file-content'),copy=content.querySelector('.project-file-reader-head button');
 const render=()=>{list.replaceChildren();for(const entry of entries.filter(item=>item.name.toLowerCase().includes(filter.value.toLowerCase()))){const button=document.createElement('button');button.type='button';button.className='project-file-entry';const icon=document.createElement('span');icon.textContent=entry.kind==='directory'?'▸':'≡';icon.setAttribute('aria-hidden','true');const name=document.createElement('span');name.textContent=entry.name;button.append(icon,name);button.title=entry.path;button.onclick=()=>entry.kind==='directory'?load(entry.path):preview(entry);list.append(button);}if(!list.children.length)list.textContent=filter.value?'No matching files.':'This folder has no available files.';};
 const preview=async entry=>{const version=++previewVersion;renderProjectFileLoading(reader,'File preview');copy.disabled=true;wrap.disabled=true;stats.textContent='';content.querySelector('.project-file-reader-head strong').textContent=entry.path;try{const file=await conversationRequest('/api/projects/'+project.id+'/file?path='+encodeURIComponent(entry.path));if(version!==previewVersion||!panel.isConnected)return;reader.replaceChildren();const pre=document.createElement('pre');pre.textContent=file.content;reader.append(pre);stats.textContent=(file.content?file.content.split('\n').length:0)+' lines · Read-only';wrap.disabled=false;copy.disabled=false;copy.textContent='Copy';copy.onclick=async()=>{try{await navigator.clipboard.writeText(file.content);copy.textContent='Copied';}catch{copy.textContent='Copy unavailable';}};}catch(error){if(version===previewVersion&&panel.isConnected)renderProjectFileError(reader,'this file',error,()=>preview(entry));}};
 const load=async relative=>{const version=++loadVersion;renderProjectFileLoading(list,'Folder');try{const result=await conversationRequest('/api/projects/'+project.id+'/files?path='+encodeURIComponent(relative));if(version!==loadVersion||!panel.isConnected)return;directory=result.path;entries=result.entries;filter.value='';const crumb=content.querySelector('.project-files-breadcrumb');crumb.replaceChildren();const parts=directory?directory.split('/'):[];for(let i=0;i<=parts.length;i++){const button=document.createElement('button');button.textContent=i===0?'Project':parts[i-1];button.onclick=()=>load(parts.slice(0,i).join('/'));button.disabled=i===parts.length;crumb.append(button);}content.querySelector('.project-files-note').textContent=(result.truncated?'Showing the first 1,000 entries. ':'')+(result.excludedCount?result.excludedCount+' hidden or excluded entries. ':'')+'Previews support UTF-8 text up to 256 KiB.';render();}catch(error){if(version===loadVersion&&panel.isConnected)renderProjectFileError(list,'this folder',error,()=>load(relative));}};
 filter.oninput=render;void load('');
}
function openProjectFolderConnection(project){
 const dialog=document.createElement('dialog');dialog.className='conversation-dialog';dialog.innerHTML='<form><h2>Connect a project folder</h2><p>Give this workspace read-only access to the folder below. File contents stay local; connecting does not grant an agent permission to edit or execute code.</p><label>Local folder path<input class="form-control" required maxlength="2000" placeholder="Absolute path to a project folder"></label><p class="memory-disclosure">Owners and administrators can browse this folder. Linked paths, hidden folders, and common credential files are excluded. Choose only a folder you want available in this workspace.</p><p class="conversation-feedback" role="status"></p><footer><button type="button" class="btn btn-secondary">Cancel</button><button type="submit" class="btn">Connect read-only</button></footer></form>';
 dialog.querySelector('input').value=project.repositoryPath||'';dialog.querySelector('button[type=button]').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();dialog.querySelector('form').onsubmit=async event=>{event.preventDefault();const save=dialog.querySelector('button[type=submit]');if(save.disabled)return;save.disabled=true;try{await conversationRequest('/api/projects/'+project.id+'/repository','POST',{path:dialog.querySelector('input').value.trim(),mode:'read'});dialog.close();await showProjects();}catch(error){dialog.querySelector('.conversation-feedback').textContent=error.message;save.disabled=false;}};document.body.append(dialog);dialog.showModal();dialog.querySelector('input').focus();
}
`;
