export const teamClient = String.raw`
let teamDirectory={agents:[],tasks:[],bindings:[],processes:[],query:''};
let teamRoomMode='room';
function renderTeamDirectoryLoading(root){
 root.innerHTML='<section class="team-directory team-directory-loading" aria-busy="true" aria-live="polite"><div class="project-hero"><div><div class="goal-kicker">People set direction. Agents do the work.</div><h1>Your team, by design.</h1><p>Checking saved teammate profiles, their work, boundaries, and procedures.</p></div><div class="team-relationship-mark" aria-hidden="true"><i></i><i></i><i></i><b></b><b></b></div></div><div class="project-controls team-controls-skeleton" aria-hidden="true"><span></span><i></i></div><div class="team-directory-grid team-directory-skeleton" aria-label="Loading teammate profiles"><article><i></i><strong></strong><span></span><span></span></article><article><i></i><strong></strong><span></span><span></span></article><article><i></i><strong></strong><span></span><span></span></article></div></section>';
}
function renderReviewLoading(root){
 root.innerHTML='<section class="review-center review-center-loading" aria-busy="true" aria-live="polite"><div class="project-hero"><div><div class="goal-kicker">Human judgment, where it matters</div><h1>Your review desk.</h1><p>Checking saved approval requests and linked task evidence.</p></div></div><section class="review-summary review-summary-skeleton"><i></i><div><strong></strong><span></span><span></span></div><b></b></section><div class="review-filters review-filters-skeleton" aria-hidden="true"><i></i><i></i></div><section class="review-records review-records-skeleton" aria-label="Loading review requests"><article><i></i><strong></strong><span></span><span></span></article><article><i></i><strong></strong><span></span><span></span></article></section></section>';
}

async function openWorkspaceAgent(agent,button){
  const view=currentView;
  const contents=button?[...button.childNodes]:[];
  if(button){button.disabled=true;button.textContent='Loading profile…';}
  try{
    const [agents,tasks,bindings,processes]=await Promise.all([conversationRequest('/api/agents'),conversationRequest('/api/tasks'),conversationRequest('/api/process-bindings'),conversationRequest('/api/processes')]);
    if(view!==currentView||button&&!button.isConnected)return;
    Object.assign(teamDirectory,{agents,tasks,bindings,processes});
    const saved=agents.find(item=>item.id===agent.id);
    if(!saved)throw new Error('This agent is no longer in the workspace. Refresh the view.');
    openTeamProfile(saved);
  }catch(error){if(button?.isConnected){const message=document.createElement('p');message.className='conversation-feedback';message.setAttribute('role','alert');message.textContent=error.message;button.after(message);}}
  finally{if(button){button.disabled=false;button.replaceChildren(...contents);}}
}
async function startAgentConversation(agent,button,feedback){
  if(button.disabled)return;
  button.disabled=true;
  feedback.textContent='Creating a saved conversation…';
  try{
    const channels=await conversationRequest('/api/channels');
    const channel=channels.find(item=>agent.assignedChannelIds?.includes(item.id)&&!item.archived)
      || channels.find(item=>!item.archived);
    if(!channel)throw new Error('Create an active workspace channel before starting a conversation.');
    const thread=await conversationRequest('/api/threads','POST',{
      title:'Conversation with '+agent.name,
      channelId:channel.id,
    });
    conversationState.selected=thread.id;
    conversationState.archived=false;
    conversationState.projectId=null;
    feedback.textContent='Opening the saved conversation…';
    button.closest('dialog')?.close();
    switchView('messages');
  }catch(error){
    feedback.textContent=error.message;
    button.disabled=false;
  }
}
function wireWorkspaceRecords(root,agents,tasks){
  root.querySelectorAll('.forge-agent').forEach((row,index)=>{const agent=agents[index];if(!agent)return;const button=document.createElement('button');button.className='btn btn-sm btn-secondary';button.textContent='Open';button.setAttribute('aria-label','Open profile for '+agent.name);button.onclick=()=>openWorkspaceAgent(agent,button);row.appendChild(button);});
  root.querySelectorAll('.forge-task').forEach((row,index)=>{const task=tasks[index];if(!task)return;const button=document.createElement('button');button.className='btn btn-sm btn-secondary';button.textContent='Review';button.setAttribute('aria-label','Review '+task.title);button.onclick=()=>{workboardState.agents=agents;openWorkDetail(task);};row.appendChild(button);});
}
function mountTopologyRecords(root,agents,tasks){
  const panel=document.createElement('section');panel.className='forge-panel topology-records';
  const heading=document.createElement('h2');heading.textContent='Explore workspace records';
  const hint=document.createElement('p');hint.textContent='Search saved teammate profiles and tasks. A profile status is stored metadata; live activity is shown only for a verified running process.';
  const input=document.createElement('input');input.className='form-control';input.placeholder='Search names, roles, tasks or statuses…';input.setAttribute('aria-label','Search topology records');
  const list=document.createElement('div');list.className='topology-record-list';
  function render(){list.replaceChildren();const query=input.value.toLowerCase();for(const [kind,items] of [['agent',agents],['task',tasks]])for(const item of items){const name=item.name||item.title;const owner=agents.find(agent=>agent.id===item.assignedAgentId);const detail=kind==='agent'?item.role:(owner?'Assigned to '+owner.name:'Unassigned');const stateLabel=kind==='agent'?'saved profile status: ':'saved task status: ';if(!(name+' '+detail+' '+item.status).toLowerCase().includes(query))continue;const button=document.createElement('button');button.className='topology-record';const title=document.createElement('strong');title.textContent=name;const subtitle=document.createElement('span');subtitle.textContent=kind+' · '+detail+' · '+stateLabel+String(item.status||'unknown').replaceAll('_',' ');button.append(title,subtitle);button.onclick=()=>{if(kind==='agent')openWorkspaceAgent(item,button);else{workboardState.agents=agents;openWorkDetail(item);}};list.append(button);}if(!list.children.length)list.textContent='No matching records.';}
  input.oninput=render;panel.append(heading,hint,input,list);root.querySelector('main').appendChild(panel);render();
}
async function showTeamDirectory(){
  const root=document.getElementById('view-content');renderTeamDirectoryLoading(root);
  let agents,tasks,bindings,processes;try{[agents,tasks,bindings,processes]=await Promise.all([conversationRequest('/api/agents'),conversationRequest('/api/tasks'),conversationRequest('/api/process-bindings'),conversationRequest('/api/processes')]);}catch(error){if(currentView==='agents'&&root.isConnected){root.innerHTML='<section class="goal-empty"><h2>Could not load the team</h2><p></p><button class="btn">Try again</button></section>';root.querySelector('p').textContent=error.message;root.querySelector('button').onclick=showTeamDirectory;}return;}
  if(currentView!=='agents')return;Object.assign(teamDirectory,{agents,tasks,bindings,processes});
const hasAgents=agents.length>0;
root.innerHTML='<section class="team-directory"><div class="project-hero"><div><div class="goal-kicker">People set direction. Agents do the work.</div><h1>Your team, by design.</h1><p>Define each teammate’s role, inspect their boundaries, and follow assigned work. Profile status is saved metadata; Team Room shows live activity only for a verified running process.</p></div><div class="team-relationship-mark" aria-hidden="true"><i></i><i></i><i></i><b></b><b></b></div></div>'+(hasAgents?'<div class="project-controls"><input class="form-control" id="team-search" aria-label="Search agents" placeholder="Find a teammate or role…"><button class="btn" id="team-add">+ Add teammate</button></div>':'')+'<div class="team-directory-grid" id="team-directory-grid"></div></section>';
  if(hasAgents){document.getElementById('team-add').onclick=openAgentModal;const input=document.getElementById('team-search');input.value=teamDirectory.query;input.oninput=()=>{teamDirectory.query=input.value;renderTeamDirectory();};}renderTeamDirectory();
}
function renderTeamDirectory(){
  const root=document.getElementById('team-directory-grid');root.replaceChildren();
  const agents=teamDirectory.agents.filter(agent=>(agent.name+' '+agent.role).toLowerCase().includes(teamDirectory.query.toLowerCase()));
  for(const agent of agents){const card=document.createElement('button');card.className='team-directory-card';const assigned=teamDirectory.tasks.filter(t=>t.assignedAgentId===agent.id);const avatar=document.createElement('span');avatar.className='team-avatar';avatar.textContent=agent.name.split(' ').map(word=>word[0]).slice(0,2).join('').toUpperCase();const status=document.createElement('span');status.className='team-card-status is-saved';status.textContent='Profile · '+agent.status.replaceAll('_',' ');const top=document.createElement('div');top.className='team-card-top';top.append(avatar,status);const title=document.createElement('h2');title.textContent=agent.name;const role=document.createElement('p');role.className='team-role';role.textContent=agent.role;const description=document.createElement('p');description.className='team-description';description.textContent=agent.description;const signals=document.createElement('div');signals.className='team-card-signals';const workSignal=document.createElement('span');workSignal.textContent=assigned.length?'Current work · '+assigned.length+' open task'+(assigned.length===1?'':'s'):'Current work · Ready for an assignment';const boundarySignal=document.createElement('span');boundarySignal.textContent=agent.permissions?.length?'Boundaries · '+agent.permissions.length+' saved permission'+(agent.permissions.length===1?'':'s'):'Boundaries · Not configured';signals.append(workSignal,boundarySignal);const footer=document.createElement('footer');const count=document.createElement('span');count.textContent=assigned.length+' task'+(assigned.length===1?'':'s');const boundary=document.createElement('span');boundary.textContent=agent.permissions?.length?agent.permissions.length+' permissions':'No permissions';footer.append(count,boundary);card.append(top,title,role,description,signals,footer);card.onclick=()=>openTeamProfile(agent);root.appendChild(card);}
  if(!agents.length){
    const empty=document.createElement('section');empty.className=teamDirectory.agents.length?'goal-empty team-filter-empty':'team-first-run';
    if(teamDirectory.agents.length){empty.textContent='No teammates match your search.';root.appendChild(empty);return;}
    empty.innerHTML='<div class="team-first-run-copy"><div class="goal-kicker">A capable team starts with a clear brief</div><h2>Give your first agent a job.</h2><p>Set its role and boundaries, then choose a model when you are ready. AgentForge will show what is configured and what still needs attention.</p><div class="team-first-run-steps"><span><b>01</b> Define the role</span><span><b>02</b> Set permissions</span><span><b>03</b> Choose a model</span></div><button class="btn" id="team-first-create">Create first teammate <span aria-hidden="true">→</span></button></div><svg class="team-first-run-art" viewBox="0 0 460 300" role="img" aria-labelledby="team-art-title team-art-desc"><title id="team-art-title">A team organized around one coordinating agent</title><desc id="team-art-desc">A central agent connects to research, building, and review roles.</desc><defs><linearGradient id="team-line" x1="0" x2="1"><stop stop-color="#7cd4af" stop-opacity=".68"/><stop offset=".55" stop-color="#c4b5fd" stop-opacity=".72"/><stop offset="1" stop-color="#e9bc77" stop-opacity=".7"/></linearGradient><radialGradient id="team-glow"><stop stop-color="#c4b5fd" stop-opacity=".18"/><stop offset="1" stop-color="#c4b5fd" stop-opacity="0"/></radialGradient></defs><circle cx="235" cy="150" r="132" fill="url(#team-glow)"/><path d="M230 145 115 72M250 143 363 75M240 170 240 248" fill="none" stroke="url(#team-line)" stroke-width="2" stroke-dasharray="4 7"/><rect x="185" y="111" width="110" height="78" rx="20" fill="#222329" stroke="#c4b5fd" stroke-opacity=".65"/><circle cx="240" cy="139" r="12" fill="#c4b5fd" fill-opacity=".18" stroke="#c4b5fd"/><path d="M218 167c5-14 39-14 44 0" fill="none" stroke="#c4b5fd" stroke-width="3" stroke-linecap="round"/><rect x="55" y="37" width="112" height="68" rx="16" fill="#202522" stroke="#7cd4af" stroke-opacity=".6"/><path d="M79 61h30M79 73h48M79 85h36" stroke="#7cd4af" stroke-width="3" stroke-linecap="round"/><rect x="307" y="36" width="112" height="68" rx="16" fill="#26232c" stroke="#c4b5fd" stroke-opacity=".6"/><circle cx="331" cy="61" r="7" fill="#c4b5fd"/><path d="M347 61h49M324 81h70" stroke="#c4b5fd" stroke-width="3" stroke-linecap="round"/><rect x="184" y="221" width="112" height="62" rx="16" fill="#29251f" stroke="#e9bc77" stroke-opacity=".6"/><path d="m211 253 8 8 17-19M248 251h29" fill="none" stroke="#e9bc77" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/><circle cx="115" cy="72" r="4" fill="#7cd4af"/><circle cx="363" cy="75" r="4" fill="#c4b5fd"/><circle cx="240" cy="248" r="4" fill="#e9bc77"/></svg>';
    root.appendChild(empty);document.getElementById('team-first-create').onclick=openAgentModal;
  }
}
function openTeamProfile(agent){
  const dialog=document.createElement('dialog');dialog.className='work-detail';dialog.innerHTML='<header><div><span class="goal-kicker">Teammate profile</span><h2></h2></div><button class="btn btn-secondary" aria-label="Close teammate">×</button></header><p class="work-detail-description"></p><div class="team-profile-fields"></div><h3 class="team-work-heading">Assigned work</h3><div class="team-profile-work"></div>';
  dialog.querySelector('h2').textContent=agent.name;dialog.querySelector('header button').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();dialog.querySelector('p').textContent=agent.description;
  const disclosure=document.createElement('p');disclosure.className='memory-disclosure';disclosure.textContent='These are saved preferences and permissions. They do not confirm that a model or execution service is connected.';dialog.querySelector('.team-profile-fields').before(disclosure);
  const procedures=teamDirectory.bindings.filter(binding=>binding.agentId===agent.id).map(binding=>teamDirectory.processes.find(p=>p.id===binding.processId)?.title||binding.processId);
  const configured=value=>value&&value!=='unconfigured'?value:'Not configured';const fields=[['Role',agent.role],['Saved status',agent.status],['Memory source',agent.memoryNamespace||'No memory namespace'],['Preferred model',configured(agent.modelPolicy.preferredModel)],['Preferred provider',configured(agent.modelPolicy.preferredProvider)],['Preferred harness',agent.harnessPolicy.preferredHarnessId],['Compute preference',agent.computePolicy.environment.replaceAll('_',' ')],['Procedures',procedures.join(', ')||'None assigned'],['Tools',agent.tools.join(', ')||'None granted'],['Permissions',agent.permissions.join(', ')||'None granted']];
  for(const [label,value] of fields){const row=document.createElement('div');row.className='work-detail-field';const name=document.createElement('span');name.textContent=label;const detail=document.createElement('strong');detail.textContent=value;row.append(name,detail);dialog.querySelector('.team-profile-fields').appendChild(row);}
  const work=dialog.querySelector('.team-profile-work');const tasks=teamDirectory.tasks.filter(task=>task.assignedAgentId===agent.id);for(const task of tasks){const button=document.createElement('button');button.className='conversation-row';button.textContent=task.title+' · '+task.status.replaceAll('_',' ');button.onclick=()=>{dialog.close();workboardState.agents=teamDirectory.agents;openWorkDetail(task);};work.appendChild(button);}if(!tasks.length)work.textContent='No tasks assigned yet.';
  const actions=document.createElement('div');actions.className='team-profile-actions';const start=document.createElement('button');start.className='btn';start.textContent='Start conversation';const feedback=document.createElement('p');feedback.className='conversation-feedback';feedback.setAttribute('role','status');start.onclick=()=>startAgentConversation(agent,start,feedback);const edit=document.createElement('button');edit.className='btn btn-secondary';edit.textContent='Edit profile';edit.disabled=true;actions.append(start,edit);dialog.querySelector('.team-profile-fields').before(actions,feedback);conversationRequest('/api/auth/me').then(identity=>{if(dialog.isConnected)edit.disabled=!(identity.user?.permissions||[]).some(permission=>['*','agents:*','agents:update'].includes(permission));}).catch(()=>{});edit.onclick=()=>{dialog.close();editTeamProfile(agent);};
  document.body.appendChild(dialog);dialog.showModal();
}
function editTeamProfile(agent){
 const dialog=document.createElement('dialog');dialog.className='conversation-dialog';dialog.innerHTML='<form><h2>Edit teammate profile</h2><label>Name<input name="name" class="form-control" required maxlength="120"></label><label>Role<input name="role" class="form-control" required maxlength="120"></label><label>Description<textarea name="description" class="form-control" maxlength="4000" rows="5"></textarea></label><p class="conversation-feedback" role="status"></p><footer><button type="button" class="btn btn-secondary" data-cancel>Cancel</button><button type="submit" class="btn">Save profile</button></footer></form>';
 const form=dialog.querySelector('form');for(const key of ['name','role','description'])form.elements.namedItem(key).value=agent[key]||'';dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('[type=submit]');if(button.disabled)return;button.disabled=true;try{const updated=await conversationRequest('/api/agents/'+encodeURIComponent(agent.id),'PATCH',{name:form.elements.namedItem('name').value,role:form.elements.namedItem('role').value,description:form.elements.namedItem('description').value,expectedUpdatedAt:agent.updatedAt});teamDirectory.agents=teamDirectory.agents.map(item=>item.id===updated.id?updated:item);if(!dialog.isConnected)return;dialog.close();if(currentView==='agents')await showTeamDirectory();openTeamProfile(updated);}catch(error){if(dialog.isConnected)form.querySelector('.conversation-feedback').textContent=error.message;}finally{button.disabled=false;}};document.body.append(dialog);dialog.showModal();
}
let requestedApprovalId=null;const approvalNoteDrafts=new Map();const approvalDecisionConfirmations=new Map();
function openApprovalRequest(approvalId){requestedApprovalId=approvalId;switchView('approvals');}
async function showReviewCenter(){
  const root=document.getElementById('view-content');renderReviewLoading(root);
  let approvals,tasks;try{[approvals,tasks]=await Promise.all([conversationRequest('/api/approvals'),conversationRequest('/api/tasks')]);}catch(error){if(currentView==='approvals'&&root.isConnected){root.innerHTML='<section class="goal-empty"><h2>Could not load the review desk</h2><p></p><button class="btn">Try again</button></section>';root.querySelector('p').textContent=error.message;root.querySelector('button').onclick=showReviewCenter;}return;}if(currentView!=='approvals')return;
  const pendingApprovals=approvals.filter(item=>item.status==='pending');const nextApproval=pendingApprovals[0];const nextTask=nextApproval?tasks.find(task=>task.id===nextApproval.taskId):null;
root.innerHTML='<section class="review-center"><div class="project-hero"><div><div class="goal-kicker">Human judgment, where it matters</div><h1>Your review desk.</h1><p>Inspect the request and its evidence before recording a decision. Approval does not bypass execution safeguards.</p></div></div><section class="review-summary"><div class="review-summary-count"><strong>'+pendingApprovals.length+'</strong><span>decision'+(pendingApprovals.length===1?'':'s')+' waiting</span></div><div class="review-summary-next"><span class="goal-kicker">Next decision</span><strong>'+escapeHtml(nextApproval?(nextTask?nextTask.title+' · ':'')+nextApproval.action:'You are caught up')+'</strong><p>'+escapeHtml(nextApproval?(nextApproval.description||'Review the saved request and its evidence.'):'New approval requests will appear here when a task needs human judgment.')+'</p></div><button class="btn btn-secondary" data-review-next '+(nextApproval?'':'disabled')+'>Open next review</button></section><div class="review-filters"><button class="btn btn-secondary" data-filter="pending">Needs review</button><button class="btn btn-secondary" data-filter="resolved">Decision history</button></div><label class="review-search"><span>Find a request</span><input class="form-control" type="search" placeholder="Search requests, tasks, or risk…" aria-label="Search approval requests"></label><p class="review-result-count" role="status"></p><div class="review-records"></div></section>';
  let activeFilter='pending';const search=root.querySelector('.review-search input');
  const render=filter=>{activeFilter=filter;root.querySelectorAll('[data-filter]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.filter===filter)));const list=root.querySelector('.review-records');list.replaceChildren();const candidates=approvals.filter(item=>filter==='pending'?item.status==='pending':item.status!=='pending');const query=search.value.trim().toLowerCase();const records=candidates.filter(item=>[item.action,item.description,item.risk,item.id,tasks.find(task=>task.id===item.taskId)?.title,item.decisionNotes].filter(Boolean).join(' ').toLowerCase().includes(query));root.querySelector('.review-result-count').textContent=records.length+' of '+candidates.length+' '+(filter==='pending'?'requests awaiting review':'recorded decisions');
    for(const item of records){const article=document.createElement('article');article.className='review-record';article.dataset.approvalId=item.id;article.tabIndex=-1;const title=document.createElement('h2');title.textContent=item.action;const meta=document.createElement('div');meta.className='review-record-meta';meta.textContent=(item.risk||'unspecified')+' risk · '+item.status;const text=document.createElement('p');text.textContent=item.description;const task=tasks.find(t=>t.id===item.taskId);const context=document.createElement('p');context.textContent=(task?task.title:'Task unavailable')+' · Requested '+new Date(item.createdAt).toLocaleString();const verificationText=task?.evidencePack?(task.evidencePack.verifiedPassed?'Recorded verification passed':'Recorded verification did not pass'):'No task verification evidence recorded';const verification=document.createElement('p');verification.textContent=verificationText;
      // Put the decision, its scope, and the available proof together before any action control.
      // Every value comes from the saved approval or task record; this is not a readiness score.
      const brief=document.createElement('section');brief.className='review-decision-brief';brief.setAttribute('aria-label','Decision brief');
      const briefTitle=document.createElement('span');briefTitle.className='goal-kicker';briefTitle.textContent='Decision brief';brief.append(briefTitle);
      const fields=[['You are deciding',item.action],['Work in scope',task?task.title:'Task unavailable'],['Evidence',verificationText],['Risk',item.risk||'Unspecified']];
      for(const [label,value] of fields){const field=document.createElement('div');const name=document.createElement('span');name.textContent=label;const detail=document.createElement('strong');detail.textContent=value;field.append(name,detail);brief.append(field);}
      article.append(context,brief,verification);const notes=document.createElement('textarea');notes.className='form-control';notes.maxLength=4000;notes.rows=3;notes.value=approvalNoteDrafts.get(item.id)||'';notes.oninput=()=>approvalNoteDrafts.set(item.id,notes.value);notes.placeholder='Reason or follow-up instructions (optional)';notes.setAttribute('aria-label','Decision notes for '+item.action);if(item.status==='pending')article.append(notes);else if(item.decisionNotes){const decision=document.createElement('p');decision.textContent='Decision notes: '+item.decisionNotes;article.append(decision);}const footer=document.createElement('footer');if(task){const inspect=document.createElement('button');inspect.className='btn btn-secondary';inspect.textContent='Inspect task evidence';inspect.onclick=()=>openWorkDetail(task);footer.appendChild(inspect);}const feedback=document.createElement('p');feedback.className='conversation-feedback';feedback.setAttribute('aria-live','polite');
      if(item.status==='pending'){
        const requestedStatus=approvalDecisionConfirmations.get(item.id);
        if(requestedStatus){
          const confirmation=document.createElement('div');confirmation.className='review-decision-confirm';const prompt=document.createElement('strong');prompt.textContent=requestedStatus==='approved'?'Record approval?':'Record rejection?';const detail=document.createElement('span');detail.textContent='This saves '+(requestedStatus==='approved'?'an approved':'a rejected')+' decision and your notes to the review history.';const confirm=document.createElement('button');confirm.className='btn '+(requestedStatus==='rejected'?'btn-secondary':'');confirm.textContent=requestedStatus==='approved'?'Confirm approval':'Confirm rejection';const cancel=document.createElement('button');cancel.className='btn btn-secondary';cancel.textContent='Back';cancel.onclick=()=>{approvalDecisionConfirmations.delete(item.id);render(activeFilter);};confirm.onclick=async()=>{confirmation.querySelectorAll('button').forEach(button=>button.disabled=true);try{await conversationRequest('/api/approvals/resolve','POST',{approvalId:item.id,status:requestedStatus,decisionNotes:notes.value});approvalNoteDrafts.delete(item.id);approvalDecisionConfirmations.delete(item.id);await showReviewCenter();}catch(error){feedback.textContent=error.message;confirmation.querySelectorAll('button').forEach(button=>button.disabled=false);}};confirmation.append(prompt,detail,confirm,cancel);footer.appendChild(confirmation);
        }else for(const [status,label] of [['rejected','Reject'],['approved','Approve request']]){const button=document.createElement('button');button.className='btn '+(status==='rejected'?'btn-secondary':'');button.textContent=label;button.onclick=()=>{approvalDecisionConfirmations.set(item.id,status);render(activeFilter);};footer.appendChild(button);}
      }
      article.prepend(meta,title,text);article.append(footer,feedback);list.appendChild(article);
    }if(!records.length){const empty=document.createElement('div');empty.className='review-empty';empty.innerHTML='<span aria-hidden="true">✓</span><h2></h2><p></p>';empty.querySelector('span').textContent=query?'⌕':'✓';empty.querySelector('h2').textContent=query?'No matching requests.':filter==='pending'?'You’re all caught up.':'No decisions recorded yet.';empty.querySelector('p').textContent=query?'Try another search or clear the search field.':filter==='pending'?'Requests that need your judgment will appear here.':'Your recorded approvals and rejections will appear here.';list.appendChild(empty);}
  };
  search.oninput=()=>render(activeFilter);
  root.querySelectorAll('[data-filter]').forEach(button=>{const count=approvals.filter(item=>button.dataset.filter==='pending'?item.status==='pending':item.status!=='pending').length;button.textContent+=' · '+count;button.onclick=()=>render(button.dataset.filter);});
  const nextButton=root.querySelector('[data-review-next]');nextButton.onclick=()=>{render('pending');const record=root.querySelector('[data-approval-id="'+nextApproval.id+'"]');record?.scrollIntoView({block:'center'});record?.focus({preventScroll:true});};
  const requested=approvals.find(item=>item.id===requestedApprovalId);render(requested&&requested.status!=='pending'?'resolved':'pending');
  if(requestedApprovalId){const target=Array.from(root.querySelectorAll('.review-record')).find(item=>item.dataset.approvalId===requestedApprovalId);if(target){target.classList.add('review-record-target');target.scrollIntoView({block:'center'});target.focus({preventScroll:true});}else{const missing=document.createElement('p');missing.className='conversation-feedback';missing.setAttribute('role','status');missing.textContent='That request is no longer available. Current requests are shown below.';root.querySelector('.review-filters').after(missing);}requestedApprovalId=null;}
}
`;
