/** Work board reflects stored states; it never promotes a task to verified completion. */
export const workboardClient = String.raw`
const workLanes=[{id:'queued',name:'Queued',statuses:['backlog','ready','approved'],color:'var(--text-muted)'},{id:'active',name:'In progress',statuses:['in_progress','verification_running'],color:'var(--accent)'},{id:'attention',name:'Needs attention',statuses:['waiting_approval','paused','failed'],color:'var(--amber)'},{id:'finished',name:'Closed',statuses:['completed','cancelled'],color:'var(--text-muted)'}];
let workboardState={tasks:[],agents:[],query:'',agent:'',project:'',sort:'priority',projects:[],runtime:null,layout:'board',showEmptyLanes:false};
let showWorkboardVersion=0;
function renderWorkboardLoading(root){
  root.innerHTML='<section class="workboard workboard-loading" aria-busy="true" aria-live="polite"><div class="workboard-intro"><div><div class="goal-kicker">FROM INTENTION TO EVIDENCE</div><h1>Work, in focus.</h1><p>Checking saved tasks, teammates, projects, and execution readiness.</p></div><section class="workboard-rail workboard-rail-skeleton" aria-label="Loading task state"><span class="goal-kicker">SAVED TASK STATE</span><ol><li><i></i><span></span></li><li><i></i><span></span></li><li><i></i><span></span></li><li><i></i><span></span></li></ol></section></div><div class="workboard-controls workboard-controls-skeleton" aria-hidden="true"><span></span><span></span><span></span><span></span><i></i></div><section class="workboard-focus workboard-focus-skeleton" aria-label="Loading recommended task"><div><span></span><strong></strong><p></p></div><i></i></section><div class="workboard-lanes workboard-lanes-skeleton" aria-label="Loading task board"><section><span></span><i></i><article></article><article></article></section><section><span></span><i></i><article></article></section><section><span></span><i></i><article></article></section></div></section>';
}
async function showWorkboard(){
  const version=++showWorkboardVersion;const loadingRoot=document.getElementById('view-content');renderWorkboardLoading(loadingRoot);
  let tasks,agents,runtime,projects;
  try{[tasks,agents,runtime,projects]=await Promise.all([conversationRequest('/api/tasks'),conversationRequest('/api/agents'),conversationRequest('/api/harnesses'),conversationRequest('/api/projects')]);
  }catch(error){if(version!==showWorkboardVersion||currentView!=='tasks')return;loadingRoot.replaceChildren();const panel=document.createElement('section');panel.className='goal-empty';const title=document.createElement('h2');title.textContent='Could not load the task board';const message=document.createElement('p');message.textContent=error.message;const retry=document.createElement('button');retry.className='btn';retry.textContent='Try again';retry.onclick=showWorkboard;panel.append(title,message,retry);loadingRoot.append(panel);return;}
  if(version!==showWorkboardVersion)return;
  if(currentView!=='tasks')return;
  workboardState.tasks=tasks;workboardState.agents=agents;workboardState.projects=projects;workboardState.runtime=runtime.runtime;
  const root=document.getElementById('view-content');
  root.innerHTML='<section class="workboard"><div class="workboard-intro"><div><div class="goal-kicker">From intention to evidence</div><h1>Work, in focus.</h1><p id="workboard-status"></p><button id="workboard-first-create" class="btn" onclick="openTaskModal()" hidden>Create your first task</button></div><section class="workboard-rail" aria-label="Saved task state"><span class="goal-kicker">Saved task state</span><ol id="workboard-rail-stages"></ol></section></div><section id="workboard-focus" class="workboard-focus" aria-live="polite"></section><div class="workboard-controls"><input id="workboard-search" class="form-control" placeholder="Find work…" aria-label="Search tasks"><select id="workboard-agent" class="form-control" aria-label="Filter by agent"><option value="">All teammates</option><option value="unassigned">Unassigned</option></select><select id="workboard-project" class="form-control" aria-label="Filter tasks by project"><option value="">All projects</option></select><select id="workboard-sort" class="form-control" aria-label="Sort tasks"><option value="priority">Priority first</option><option value="recent">Recently updated</option><option value="oldest">Oldest first</option></select><button class="btn btn-secondary" id="workboard-layout"></button><button class="btn" id="workboard-create">+ New task</button></div><p id="workboard-count" class="memory-disclosure" role="status"></p><div id="workboard-lanes"></div></section>';
  document.getElementById('workboard-status').textContent=runtime.runtime.canExecuteTasks?'Connected execution · Select a task to inspect its evidence.':'Execution is offline. You can organize work and inspect saved evidence.';
  const search=document.getElementById('workboard-search');search.value=workboardState.query;search.oninput=()=>{workboardState.query=search.value;renderWorkboard();};
  const select=document.getElementById('workboard-agent');for(const agent of agents){const option=document.createElement('option');option.value=agent.id;option.textContent=agent.name;select.appendChild(option);}select.value=workboardState.agent;select.onchange=()=>{workboardState.agent=select.value;renderWorkboard();};
  const projectSelect=document.getElementById('workboard-project');for(const project of projects){const option=new Option(project.name+(project.archived?' (archived)':''),project.id);projectSelect.append(option);}projectSelect.value=workboardState.project;projectSelect.onchange=()=>{workboardState.project=projectSelect.value;renderWorkboard();};const sort=document.getElementById('workboard-sort');sort.value=workboardState.sort;sort.onchange=()=>{workboardState.sort=sort.value;renderWorkboard();};
  document.getElementById('workboard-create').onclick=openTaskModal;
  document.getElementById('workboard-layout').onclick=()=>{workboardState.layout=workboardState.layout==='board'?'list':'board';renderWorkboard();};renderWorkboard();
}
function renderWorkboard(){
  const root=document.getElementById('workboard-lanes');if(!root)return;root.replaceChildren();root.className='workboard-lanes '+(workboardState.layout==='list'?'as-list':'');
  const board=root.closest('.workboard');const firstRun=workboardState.tasks.length===0;board?.classList.toggle('is-first-run',firstRun);const firstCreate=document.getElementById('workboard-first-create');if(firstCreate)firstCreate.hidden=!firstRun;
  document.getElementById('workboard-layout').textContent=workboardState.layout==='board'?'List view':'Board view';
  const tasks=workboardState.tasks.filter(task=>(task.id+' '+task.title+' '+(task.description||'')).toLowerCase().includes(workboardState.query.toLowerCase())&&(!workboardState.agent||(workboardState.agent==='unassigned'?!task.assignedAgentId:task.assignedAgentId===workboardState.agent))&&(!workboardState.project||task.projectId===workboardState.project));
  const priority={critical:0,high:1,medium:2,low:3};tasks.sort((a,b)=>workboardState.sort==='oldest'?Date.parse(a.createdAt)-Date.parse(b.createdAt):workboardState.sort==='recent'?Date.parse(b.updatedAt)-Date.parse(a.updatedAt):(priority[a.priority]??4)-(priority[b.priority]??4)||Date.parse(a.createdAt)-Date.parse(b.createdAt));document.getElementById('workboard-count').textContent=tasks.length+' of '+workboardState.tasks.length+' tasks';
  const focusRoot=document.getElementById('workboard-focus');focusRoot.replaceChildren();const nextTask=tasks.find(task=>['waiting_approval','paused','failed'].includes(task.status))||tasks.find(task=>['in_progress','verification_running'].includes(task.status))||tasks.find(task=>['backlog','ready','approved'].includes(task.status));if(nextTask){focusRoot.hidden=false;const label=document.createElement('span');label.className='goal-kicker';label.textContent=['waiting_approval','paused','failed'].includes(nextTask.status)?'Needs your attention':'Recommended next task';const copy=document.createElement('div');const title=document.createElement('strong');title.textContent=nextTask.title;const detail=document.createElement('p');const owner=workboardState.agents.find(agent=>agent.id===nextTask.assignedAgentId)?.name||(nextTask.assignedAgentId?'Assigned teammate':'Unassigned');detail.textContent=(nextTask.id==='AF-142'?'Fixture record · ':'')+workboardCardCheckpoint(nextTask)+' · '+owner+' · '+nextTask.priority+' priority';copy.append(label,title,detail);const action=document.createElement('button');action.className='btn btn-secondary';action.textContent='Open task';action.onclick=()=>openWorkDetail(nextTask);focusRoot.append(copy,action);}else{focusRoot.hidden=true;}
  renderWorkboardRail(tasks);
  const laneRecords=workLanes.map(lane=>({lane,records:tasks.filter(task=>lane.statuses.includes(task.status))}));
  if(!tasks.length){
    const empty=document.createElement('section');empty.className='workboard-no-results'+(workboardState.tasks.length?' is-filtered':' is-first-run');
    if(!workboardState.tasks.length){
      const art=document.createElement('div');art.className='workboard-empty-art';art.setAttribute('aria-hidden','true');
      art.innerHTML='<svg viewBox="0 0 420 250" fill="none" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="workGlow" x1="66" y1="30" x2="350" y2="220" gradientUnits="userSpaceOnUse"><stop stop-color="#b5a1ff" stop-opacity=".24"/><stop offset="1" stop-color="#75d5b2" stop-opacity=".06"/></linearGradient><linearGradient id="workLine" x1="86" y1="65" x2="337" y2="188" gradientUnits="userSpaceOnUse"><stop stop-color="#b5a1ff"/><stop offset="1" stop-color="#75d5b2"/></linearGradient></defs><path d="M54 34h312v182H54z" fill="url(#workGlow)"/><path d="M78 185h79M157 185v-48h76M233 137h92" stroke="url(#workLine)" stroke-width="2" stroke-linecap="round" stroke-dasharray="4 7"/><circle cx="157" cy="185" r="5" fill="#b5a1ff"/><circle cx="233" cy="137" r="5" fill="#c5b5ff"/><circle cx="325" cy="137" r="5" fill="#75d5b2"/><rect x="76" y="60" width="116" height="71" rx="12" fill="#202126" stroke="#b5a1ff" stroke-opacity=".46"/><rect x="89" y="74" width="25" height="25" rx="8" fill="#b5a1ff" fill-opacity=".18"/><path d="M97 86h9m-4-4v9" stroke="#cfc2ff" stroke-width="1.6" stroke-linecap="round"/><path d="M123 79h52M123 89h39M89 110h87" stroke="#737584" stroke-linecap="round"/><rect x="202" y="105" width="117" height="67" rx="12" fill="#202126" stroke="#b5a1ff" stroke-opacity=".3"/><circle cx="220" cy="124" r="6" fill="#e9bc77" fill-opacity=".9"/><path d="M236 121h67M215 141h90M215 151h54" stroke="#737584" stroke-linecap="round"/><rect x="283" y="48" width="73" height="52" rx="12" fill="#202126" stroke="#75d5b2" stroke-opacity=".46"/><path d="m302 74 7 7 15-17" stroke="#75d5b2" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><path d="M54 34h312" stroke="#fff" stroke-opacity=".08"/></svg>';
      const copy=document.createElement('div');copy.className='workboard-empty-copy';
      const eyebrow=document.createElement('span');eyebrow.className='goal-kicker';eyebrow.textContent='A CLEAR PLACE TO START';
      const title=document.createElement('h2');title.textContent='Your next piece of work starts here';
      const detail=document.createElement('p');detail.textContent='Create a task with the outcome you want. Keep its owner, project, decisions, and verification together as the work moves forward.';
      copy.append(eyebrow,title,detail);empty.append(art,copy);
    }else{
      const title=document.createElement('h2');title.textContent='No work matches these filters';
      const detail=document.createElement('p');detail.textContent='Clear or change a filter to see saved work.';
      const clear=document.createElement('button');clear.className='btn btn-secondary';clear.textContent='Clear filters';clear.onclick=()=>{Object.assign(workboardState,{query:'',agent:'',project:''});document.getElementById('workboard-search').value='';document.getElementById('workboard-agent').value='';document.getElementById('workboard-project').value='';renderWorkboard();};
      empty.append(title,detail,clear);
    }
    root.append(empty);return;
  }
  const visibleLanes=laneRecords.filter(entry=>entry.records.length||workboardState.showEmptyLanes);const hiddenEmpty=laneRecords.filter(entry=>!entry.records.length&&!workboardState.showEmptyLanes);root.classList.toggle('has-single-lane',visibleLanes.length===1&&!workboardState.showEmptyLanes);
  for(const {lane,records} of visibleLanes){const section=document.createElement('section');section.className='workboard-lane'+(!records.length?' is-empty':'');const header=document.createElement('header');const dot=document.createElement('i');dot.style.background=lane.color;const name=document.createElement('h2');name.textContent=lane.name;const count=document.createElement('span');count.textContent=String(records.length);header.append(dot,name,count);section.appendChild(header);
    for(const task of records){const card=document.createElement('button');card.className='workboard-card';const title=document.createElement('strong');title.textContent=task.title;const description=document.createElement('p');description.textContent=task.description;const meta=document.createElement('footer');const agent=document.createElement('span');agent.textContent=workboardState.agents.find(a=>a.id===task.assignedAgentId)?.name||(task.assignedAgentId?'Assigned teammate':'Unassigned');const badge=document.createElement('span');badge.textContent=task.status.replaceAll('_',' ');badge.className='badge';meta.append(agent,badge);const context=document.createElement('p');context.className='workboard-card-context';context.textContent=workboardProjectLabel(task)+' · '+task.priority+' priority';const proof=document.createElement('div');proof.className='workboard-card-proof';const checkpoint=document.createElement('span');checkpoint.textContent='Next: '+workboardCardCheckpoint(task);const evidence=document.createElement('span');const checks=task.evidencePack?.testResults||[];const passed=checks.filter(check=>check.passed).length;evidence.textContent=task.evidencePack?(checks.length?passed+'/'+checks.length+' checks passed':task.evidencePack.verifiedPassed?'Evidence verified':'Evidence needs review'):'No evidence yet';const updated=document.createElement('time');updated.dateTime=task.updatedAt;updated.textContent='Updated '+new Date(task.updatedAt).toLocaleDateString();proof.append(checkpoint,evidence,updated);card.append(context,title,description,proof,meta);card.onclick=()=>openWorkDetail(task);section.appendChild(card);}
    if(!records.length){const empty=document.createElement('div');empty.className='workboard-empty';empty.textContent='No tasks in this stage';section.appendChild(empty);}root.appendChild(section);
  }
  if(hiddenEmpty.length){const summary=document.createElement('section');summary.className='workboard-empty-summary';const copy=document.createElement('span');copy.textContent=hiddenEmpty.map(entry=>entry.lane.name).join(', ')+' '+(hiddenEmpty.length===1?'is':'are')+' empty';const reveal=document.createElement('button');reveal.className='btn btn-sm btn-secondary';reveal.textContent='Show empty stages';reveal.onclick=()=>{workboardState.showEmptyLanes=true;renderWorkboard();};summary.append(copy,reveal);root.append(summary);}
  else if(workboardState.showEmptyLanes&&laneRecords.some(entry=>!entry.records.length)){const summary=document.createElement('section');summary.className='workboard-empty-summary';const copy=document.createElement('span');copy.textContent='Empty stages are visible';const conceal=document.createElement('button');conceal.className='btn btn-sm btn-secondary';conceal.textContent='Hide empty stages';conceal.onclick=()=>{workboardState.showEmptyLanes=false;renderWorkboard();};summary.append(copy,conceal);root.append(summary);}
}


function renderWorkboardRail(tasks){
 const rail=document.getElementById('workboard-rail-stages');if(!rail)return;rail.replaceChildren();const copy={queued:'Saved and ready for a next step.',active:'Work or checks are in progress.',attention:'A person needs to inspect or decide.',finished:'Saved history remains available.'};
 for(const lane of workLanes){const count=tasks.filter(task=>lane.statuses.includes(task.status)).length;const item=document.createElement('li');item.dataset.state=lane.id;item.dataset.hasTasks=String(count>0);const marker=document.createElement('span');marker.className='workboard-rail-marker';marker.style.background=lane.color;marker.setAttribute('aria-hidden','true');const body=document.createElement('div');const name=document.createElement('strong');name.textContent=lane.name;const detail=document.createElement('small');detail.textContent=copy[lane.id]||'Saved task state.';body.append(name,detail);const value=document.createElement('span');value.className='workboard-rail-count';value.textContent=String(count);value.setAttribute('aria-label',count+' task'+(count===1?'':'s'));item.append(marker,body,value);rail.append(item);}
}

function workboardProjectLabel(task){
 const project=workboardState.projects.find(item=>item.id===task.projectId);
 if(project)return project.name;
 return task.id==='AF-142'?'Fixture record':'No linked project';
}
function workboardCardCheckpoint(task){
 if(task.status==='waiting_approval')return 'Human decision required';
 if(task.status==='verification_running')return 'Verification in progress';
 if(task.status==='in_progress')return 'Work in progress';
 if(task.status==='paused')return 'Review before resuming';
 if(task.status==='failed')return 'Inspect recorded failure';
 if(task.status==='completed')return 'Review completion evidence';
 if(task.status==='cancelled')return 'Saved history remains';
 return workboardState.runtime?.canExecuteTasks?'Ready for an authorized run':'Execution offline · finish Harness setup';
}
function taskOutcomeLabel(task){
 if(task.status==='completed')return 'Complete with saved evidence';
 if(task.status==='failed')return 'Needs attention after a recorded failure';
 if(task.status==='waiting_approval')return 'Ready for human review';
 if(task.status==='paused')return 'Work is paused';
 if(task.status==='verification_running')return 'Verification is in progress';
 if(task.status==='in_progress')return 'Work is in progress';
 if(task.status==='cancelled')return 'Cancelled; saved history remains';
 return 'Saved work awaits its next authorized step';
}
function taskNextStep(task,runtime){
 if(task.status==='completed')return 'Review the recorded checks and changes. Completion does not mean the branch was merged.';
 if(task.status==='cancelled')return 'This task was cancelled. Its saved history remains available below.';
 if(task.status==='failed')return task.error?'Execution failed: '+task.error:'Inspect the evidence and activity to understand the failure before retrying.';
 if(task.status==='waiting_approval')return 'Review changes and verification evidence before deciding whether to approve this work.';
 if(task.status==='paused')return 'Work is paused. Review its latest activity before resuming with a connected worker.';
 if(!runtime)return 'Checking execution readiness. The task status shown above is the saved record.';
 if(!runtime.canExecuteTasks)return 'Execution is offline. This task is saved, but a connected execution service is required to run it.';
 return task.status==='verification_running'?'Checks are running. Completion requires their recorded results.':task.status==='in_progress'?'Work is running. Review the recorded activity and return for verification results.':'This task is saved and ready for an authorized execution request.';
}
function renderTaskSectionLoading(body,name){
 body.replaceChildren();const title=document.createElement('h3');title.textContent=name==='diff'?'Changed files':name==='activity'?'Recorded activity':'Checks and evidence';const note=document.createElement('p');note.className='memory-disclosure';note.textContent='Checking the saved '+(name==='diff'?'change record':name==='activity'?'task history':'verification record')+'…';const list=document.createElement('div');list.className='task-section-skeleton';for(let index=0;index<3;index++){const row=document.createElement('article');const icon=document.createElement('i');const copy=document.createElement('div');const heading=document.createElement('strong');const detail=document.createElement('span');copy.append(heading,detail);row.append(icon,copy);list.append(row);}body.append(title,note,list);
}
function renderTaskSectionError(body,name,error,retry){
 body.replaceChildren();const title=document.createElement('h3');title.textContent=name==='diff'?'Changed files could not be loaded':name==='activity'?'Recorded activity could not be loaded':'Checks and evidence could not be loaded';const detail=document.createElement('p');detail.className='memory-disclosure';detail.textContent=error;const button=document.createElement('button');button.className='btn btn-secondary';button.textContent='Try again';button.onclick=retry;body.append(title,detail,button);
}
function renderTaskSectionEmpty(body,name,message){
 body.replaceChildren();const title=document.createElement('h3');title.textContent=name==='evidence'?'No verification evidence yet':'Nothing recorded yet';const detail=document.createElement('p');detail.className='memory-disclosure';detail.textContent=message;body.append(title,detail);
}
function renderTaskActivity(body,result){
 body.replaceChildren();const intro=document.createElement('p');intro.className='memory-disclosure';intro.textContent='Latest '+result.limit+' retained task events. This is recorded history, not a live terminal.';body.append(intro);
 const entries=[...result.entries].sort((a,b)=>Date.parse(b.timestamp)-Date.parse(a.timestamp));
 if(!entries.length){const empty=document.createElement('p');empty.textContent='No task-specific events have been recorded.';body.append(empty);return;}
 const list=document.createElement('ol');list.className='task-timeline';for(const entry of entries){const item=document.createElement('li');const title=document.createElement('strong');title.textContent=entry.action.replaceAll('_',' ').toLowerCase();const meta=document.createElement('p');meta.textContent=new Date(entry.timestamp).toLocaleString()+' · '+(entry.actorType==='human'?'You':entry.actorType==='agent'?'Teammate':'System')+' · '+entry.origin;item.append(title,meta);if(Object.keys(entry.details||{}).length){const details=document.createElement('details');const summary=document.createElement('summary');summary.textContent='Event details';const pre=document.createElement('pre');pre.textContent=JSON.stringify(entry.details,null,2);details.append(summary,pre);item.append(details);}list.append(item);}body.append(list);
}
const pendingTaskControls=new Map();
function renderTaskMilestones(body,task,openSection){
 const group=document.createElement('section');group.className='task-proof-path';group.setAttribute('aria-label','Recorded execution and review');
 const pack=task.evidencePack;
 const milestones=[
  {name:'Plan',value:task.approvedExecutionPlan?'Commands approved for this task':task.contract?'Boundaries saved · review commands':'No execution boundaries',state:task.approvedExecutionPlan?'recorded':'pending',section:'plan',icon:'□'},
  {name:'Work',value:task.startedAt?'Start recorded':'No start recorded',state:task.startedAt?'recorded':'pending',section:'activity',icon:'↗'},
  {name:'Verify',value:pack?(pack.verifiedPassed?'Recorded checks passed':'Recorded checks failed'):'No evidence recorded',state:pack?(pack.verifiedPassed?'passed':'failed'):'pending',section:'evidence',icon:'◇'},
  {name:'Review',value:pack?.approvedBy?'Approved by '+pack.approvedBy:task.contract?.completion?.requireHumanApproval?'Approval required':'Approval not required',state:pack?.approvedBy?'recorded':'pending',section:'decisions',icon:'◎'}
 ];
 for(const item of milestones){const button=document.createElement('button');button.type='button';button.className='task-proof-step '+item.state;const icon=document.createElement('span');icon.className='task-proof-icon';icon.textContent=item.icon;icon.setAttribute('aria-hidden','true');const name=document.createElement('strong');name.textContent=item.name;const value=document.createElement('small');value.textContent=item.value;button.append(icon,name,value);button.onclick=()=>{const dialog=body.closest("dialog");openSection(item.section);dialog?.querySelector("[data-section="+item.section+"]")?.focus();};group.append(button);}body.append(group);
}
function openWorkDetail(task){
 const dialog=document.createElement('dialog');dialog.className='work-detail';dialog.dataset.kind='task';dialog.setAttribute('aria-label','Task review');
 dialog.innerHTML='<header><div><span class="goal-kicker">Task review</span><h2></h2></div><button class="btn btn-secondary" aria-label="Close task">×</button></header><p class="task-outcome" data-state="pending" aria-live="polite"></p><div class="work-detail-meta"></div><p class="work-detail-description"></p><section class="task-next-step" aria-live="polite"></section><div class="task-review-actions"></div><p class="conversation-feedback" data-control-feedback role="status"></p><div class="task-inspector-tools"><span class="memory-disclosure" data-freshness></span><button class="btn btn-sm btn-secondary" data-refresh>Refresh status</button></div><div class="work-detail-tabs" role="group" aria-label="Task sections"><button class="btn btn-secondary" data-section="overview">Summary</button><button class="btn btn-secondary" data-section="diff">Changed files</button><button class="btn btn-secondary" data-section="evidence">Checks & evidence</button><button class="btn btn-secondary" data-section="decisions">Decisions</button><button class="btn btn-secondary" data-section="activity">Activity</button><button class="btn btn-secondary" data-section="boundaries">Boundaries</button></div><div class="work-detail-body" aria-live="polite"></div>';
 dialog.querySelector('header button').onclick=()=>dialog.close();dialog.onclose=()=>{sectionLoad++;refreshLoad++;clearInterval(poll);dialog.remove();};
 const body=dialog.querySelector('.work-detail-body');let selected='overview',sectionLoad=0,refreshLoad=0,runtime=null,identity=null,poll=null,confirmingCancel=false;
 function heading(){dialog.querySelector('h2').textContent=task.title;const outcome=dialog.querySelector('.task-outcome');outcome.textContent=taskOutcomeLabel(task);outcome.dataset.state=task.status;const owner=workboardState.agents.find(a=>a.id===task.assignedAgentId)?.name||(task.assignedAgentId?'Assigned teammate':'Unassigned');const meta=dialog.querySelector('.work-detail-meta');meta.replaceChildren();for(const [label,value] of [['Status',task.status.replaceAll('_',' ')],['Priority',task.priority],['Owner',owner]]){const chip=document.createElement('span');chip.className='task-meta-chip';const key=document.createElement('small');key.textContent=label;const content=document.createElement('strong');content.textContent=value;chip.append(key,content);meta.append(chip);}dialog.querySelector('.work-detail-description').textContent=task.description;const next=dialog.querySelector('.task-next-step');next.replaceChildren();const label=document.createElement('strong');label.textContent='What happens next';const message=document.createElement('p');message.textContent=taskNextStep(task,runtime);next.append(label,message);renderControls();}

 function permitted(){const permissions=identity?.user?.permissions||[];return permissions.some(value=>['*','tasks:*','tasks:execute'].includes(value));}
 function renderControls(){const root=dialog.querySelector('.task-review-actions');if(confirmingCancel&&permitted()&&!['completed','cancelled'].includes(task.status))return;confirmingCancel=false;root.replaceChildren();const pending=pendingTaskControls.get(task.id)||new Set();if(task.status==='waiting_approval'){const review=document.createElement('button');review.className='btn';review.textContent='Review request';review.onclick=async()=>{review.disabled=true;const feedback=dialog.querySelector('[data-control-feedback]');feedback.textContent='Opening the saved review request…';try{const records=await conversationRequest('/api/approvals');if(!dialog.isConnected)return;const record=records.filter(item=>item.taskId===task.id&&item.status==='pending').sort((a,b)=>Date.parse(b.updatedAt||b.createdAt)-Date.parse(a.updatedAt||a.createdAt))[0];if(!record){feedback.textContent='No pending review request is recorded for this task.';review.disabled=false;return;}dialog.close();openApprovalRequest(record.id);}catch(error){if(dialog.isConnected){feedback.textContent='Could not open the review request: '+error.message;review.disabled=false;}}};root.append(review);}const choices=[];if(['backlog','ready','approved'].includes(task.status))choices.push(['run','Run task',true]);if(['in_progress','verification_running'].includes(task.status))choices.push(['pause','Pause',false]);if(task.status==='paused')choices.push(['resume','Resume',true]);if(['failed','cancelled'].includes(task.status))choices.push(['retry','Retry',true]);if(!['completed','cancelled'].includes(task.status))choices.push(['cancel','Cancel task',false]);for(const [action,label,needsWorker] of choices){const button=document.createElement('button');button.className='btn btn-secondary';button.dataset.action=action;button.textContent=pending.has(action)?label+'…':label;button.disabled=!identity||!permitted()||pending.has(action)||pending.has('pause')||pending.has('cancel')||(needsWorker&&(!runtime?.canExecuteTasks||pending.size>0));button.title=!identity?'Checking permissions':!permitted()?'Your role cannot control task execution':needsWorker&&!runtime?.canExecuteTasks?'Connect execution before running work':'';button.onclick=()=>{if(action==='cancel'){confirmCancel(root);return;}control(action);};root.append(button);}if(runtime&&!runtime.canExecuteTasks&&choices.some(choice=>choice[2])){const setup=document.createElement('button');setup.className='btn btn-secondary';setup.textContent='Review execution setup';setup.onclick=()=>{dialog.close();switchView('harnesses');};root.append(setup);}}
 function confirmCancel(root){confirmingCancel=true;root.replaceChildren();const text=document.createElement('p');text.textContent='Cancel this task? Execution will be stopped and partial work will be kept for review.';const yes=document.createElement('button');yes.className='btn';yes.textContent='Confirm cancellation';yes.onclick=()=>control('cancel');const no=document.createElement('button');no.className='btn btn-secondary';no.textContent='Keep task';no.onclick=()=>{confirmingCancel=false;renderControls();};root.append(text,yes,no);no.focus();}
 async function control(action){const pending=pendingTaskControls.get(task.id)||new Set();if(pending.has(action)||pending.has('pause')||pending.has('cancel'))return;confirmingCancel=false;pending.add(action);pendingTaskControls.set(task.id,pending);const feedback=dialog.querySelector('[data-control-feedback]');feedback.textContent=['pause','cancel'].includes(action)?'Waiting for execution to stop. Partial work will be kept.':'Execution requested. You can pause running work while this request completes.';renderControls();if(!poll)poll=setInterval(()=>{if(dialog.isConnected&&pendingTaskControls.get(task.id)?.size)refresh(false);},2000);try{const response=await conversationRequest('/api/tasks/'+encodeURIComponent(task.id)+'/'+action,'POST',{});if(!dialog.isConnected)return;feedback.textContent=response.message||'Task updated.';await refresh();}catch(error){if(dialog.isConnected){feedback.textContent='Request failed: '+error.message;await refresh();}}finally{pending.delete(action);if(!pending.size){pendingTaskControls.delete(task.id);clearInterval(poll);poll=null;}if(dialog.isConnected)renderControls();}}
 function overview(){body.replaceChildren();renderTaskMilestones(body,task,section);for(const [name,value] of [['Created',new Date(task.createdAt).toLocaleString()],['Last updated',new Date(task.updatedAt).toLocaleString()],['Work started',task.startedAt?new Date(task.startedAt).toLocaleString():'No start recorded'],['Work finished',task.completedAt?new Date(task.completedAt).toLocaleString():'Not recorded'],['Workspace',task.worktree?'An isolated workspace is attached':'No isolated workspace is attached'],['Recorded issue',task.error||'No recorded issue']])evidenceField(body,name,value);const note=document.createElement('p');note.className='memory-disclosure';note.textContent='Technical identifiers and local paths stay out of the normal review. They are retained in the audit record for authorized troubleshooting.';body.append(note);}
 function canEditBoundaries(){const permissions=identity?.user?.permissions||[];return permissions.includes('*')||permissions.includes('tasks:*')||permissions.includes('tasks:create');}
 function openBoundaryEditor(){
  if(!task.contract)return;const contract=task.contract;const editor=document.createElement('dialog');editor.className='conversation-dialog boundary-editor-dialog';editor.setAttribute('aria-label','Edit execution boundaries');
  editor.innerHTML='<form><h2>Edit execution boundaries</h2><p>Changing boundaries invalidates any existing command approval. This still does not run work.</p><label>Starting branch<input class="form-control" name="branch" maxlength="200"></label><label>Starting commit (full Git SHA)<input class="form-control" name="sha" maxlength="64"></label><label>Allowed paths · one per line<textarea class="form-control" name="allowed" rows="3"></textarea></label><label>Protected paths · one per line<textarea class="form-control" name="protected" rows="3"></textarea></label><section class="boundary-check-editor"><div><h3>Required checks</h3><button class="btn btn-sm btn-secondary" type="button" data-add-check>Add check</button></div><div data-checks></div></section><p class="conversation-feedback" role="status"></p><footer><button class="btn btn-secondary" type="button" data-close>Cancel</button><button class="btn" type="submit">Save boundaries</button></footer></form>';
  const form=editor.querySelector('form'),checksRoot=editor.querySelector('[data-checks]'),feedback=editor.querySelector('.conversation-feedback');form.elements.branch.value=contract.repository.baseBranch;form.elements.sha.value=contract.repository.baseSha;form.elements.allowed.value=contract.scope.allowedPaths.join('\n');form.elements.protected.value=contract.scope.protectedPaths.join('\n');
  const checkTypes=['unit_tests','regression_tests','diff_scope','lint','build','security_scan','custom_script'];
  const addCheck=(check={type:'unit_tests',required:true,command:'',timeoutMs:undefined})=>{const row=document.createElement('div');row.className='boundary-check-row';const type=document.createElement('select');type.className='form-control';type.name='type';for(const name of checkTypes){const option=new Option(name.replaceAll('_',' '),name);option.selected=name===check.type;type.append(option);}const command=document.createElement('input');command.className='form-control';command.name='command';command.placeholder='Exact command to run';command.maxLength=5000;command.value=check.command||'';const timeout=document.createElement('input');timeout.className='form-control';timeout.name='timeout';timeout.type='number';timeout.min='1';timeout.max='3600';timeout.placeholder='Seconds (optional)';timeout.value=check.timeoutMs?String(Math.round(check.timeoutMs/1000)):'';const required=document.createElement('label');const toggle=document.createElement('input');toggle.type='checkbox';toggle.name='required';toggle.checked=check.required!==false;required.append(toggle,document.createTextNode(' Required'));const remove=document.createElement('button');remove.type='button';remove.className='btn btn-sm btn-secondary';remove.textContent='Remove';remove.onclick=()=>row.remove();row.append(type,command,timeout,required,remove);checksRoot.append(row);};
  for(const check of contract.requiredChecks)addCheck(check);if(!contract.requiredChecks.length)addCheck();editor.querySelector('[data-add-check]').onclick=()=>addCheck();editor.querySelector('[data-close]').onclick=()=>editor.close();editor.onclose=()=>editor.remove();
  form.onsubmit=async event=>{event.preventDefault();const submit=form.querySelector('[type=submit]');const checks=Array.from(checksRoot.querySelectorAll('.boundary-check-row')).map(row=>{const timeout=Number(row.querySelector('[name=timeout]').value);return {type:row.querySelector('[name=type]').value,required:row.querySelector('[name=required]').checked,command:row.querySelector('[name=command]').value.trim(),...(Number.isFinite(timeout)&&timeout>0?{timeoutMs:timeout*1000}:{})};});submit.disabled=true;feedback.textContent='Saving reviewed boundaries…';try{const result=await conversationRequest('/api/tasks/'+encodeURIComponent(task.id)+'/contract','PUT',{expectedUpdatedAt:task.updatedAt,baseBranch:form.elements.branch.value.trim(),baseSha:form.elements.sha.value.trim(),allowedPaths:form.elements.allowed.value.split(/\\r?\\n/).map(value=>value.trim()).filter(Boolean),protectedPaths:form.elements.protected.value.split(/\\r?\\n/).map(value=>value.trim()).filter(Boolean),checks});task=result.task;editor.close();await refresh();}catch(error){feedback.textContent=error.message;submit.disabled=false;}};
  document.body.append(editor);editor.showModal();form.elements.branch.focus();
 }
 function boundaries(){body.replaceChildren();const contract=task.contract;if(!contract){body.textContent='No execution boundaries are recorded.';return;}for(const [label,value] of [['Allowed paths',contract.scope?.allowedPaths?.join(', ')||'None recorded'],['Protected paths',contract.scope?.protectedPaths?.join(', ')||'None recorded'],['Isolation',contract.workspace?.requireIsolatedWorktree?'Separate worktree required':'Separate worktree not required'],['Human approval',contract.completion?.requireHumanApproval?'Required':'Not required'],['Evidence',contract.completion?.requireEvidencePack?'Required':'Not required']])evidenceField(body,label,value);const title=document.createElement('h3');title.textContent='Required checks';body.append(title);if(!contract.requiredChecks?.length){const empty=document.createElement('p');empty.textContent='No checks are configured in this contract.';body.append(empty);}for(const check of contract.requiredChecks||[])evidenceField(body,check.type.replaceAll('_',' '),(check.required?'Required':'Optional')+(check.command?' · '+check.command:''));const authority=document.createElement('h3');authority.textContent='Authority';body.append(authority);for(const [key,value] of Object.entries(contract.authority||{}))evidenceField(body,key.replace(/([A-Z])/g,' $1'),value?'Allowed by contract':'Not allowed');const edit=document.createElement('button');edit.className='btn btn-secondary';edit.textContent='Edit boundaries';edit.disabled=!canEditBoundaries()||['in_progress','verification_running','completed','cancelled'].includes(task.status);edit.title=!canEditBoundaries()?'Your role cannot change task boundaries':edit.disabled?'Pause active work before changing boundaries':'';edit.onclick=openBoundaryEditor;body.append(edit);}
 function executionPlan(){
  body.replaceChildren();const record=task.approvedExecutionPlan;
  if(!task.contract){const title=document.createElement('h3');title.textContent='Execution plan not available';const detail=document.createElement('p');detail.textContent='This task has no recorded execution boundaries. Define its repository, allowed changes, and required checks before reviewing commands.';body.append(title,detail);return;}
  const commands=record?.plan?.commands||task.executionPlanDraft?.commands||task.contract.requiredChecks.filter(check=>check.command).map(check=>({checkName:check.type,command:check.command}));
  const title=document.createElement('h3');title.textContent='Review execution plan';
  const description=document.createElement('p');description.textContent='These exact commands run inside the task environment. Approval lasts one hour and does not start the task.';body.append(title,description);
  evidenceField(body,'Starting commit',task.contract.repository.baseSha);
  evidenceField(body,'Allowed changes',task.contract.scope.allowedPaths.join(', ')||'No paths allowed');
  evidenceField(body,'Protected paths',task.contract.scope.protectedPaths.join(', ')||'None specified');
  if(record){const current=record.contractDigest===task.executionContractDigest&&Date.parse(record.expiresAt)>Date.now();evidenceField(body,'Approval',current?'Approved until '+new Date(record.expiresAt).toLocaleString():'Expired or task boundaries changed — review again');evidenceField(body,'Approved by',record.approvedBy);}else if(task.executionPlanDraft){evidenceField(body,'Plan source','Model draft · human approval still required');}
  const list=document.createElement('ol');list.className='execution-command-list';for(const [index,command] of commands.entries()){const item=document.createElement('li');const header=document.createElement('div');header.className='execution-command-heading';const label=document.createElement('strong');label.textContent=(index+1)+'. '+command.checkName.replaceAll('_',' ');const copy=document.createElement('button');copy.type='button';copy.className='btn btn-sm btn-secondary';copy.textContent='Copy command';copy.setAttribute('aria-label','Copy command '+(index+1));copy.onclick=async()=>{try{await navigator.clipboard.writeText(command.command);copy.textContent='Copied';}catch{copy.textContent='Copy unavailable';}};header.append(label,copy);const code=document.createElement('pre');code.textContent=command.command;item.append(header,code);if(command.timeoutMs){const timeout=document.createElement('small');timeout.textContent='Time limit: '+Math.round(command.timeoutMs/1000)+' seconds';item.append(timeout);}list.append(item);}body.append(list);
  if(!commands.length){const empty=document.createElement('p');empty.textContent='No executable plan is available. This task needs a plan with explicit commands before it can be approved.';body.append(empty);return;}
  const permissions=identity?.user?.permissions||[];const canApprove=permissions.includes('*')||((permissions.includes('approvals:decide')||permissions.includes('approvals:*'))&&(permissions.includes('tasks:execute')||permissions.includes('tasks:*')));
  const button=document.createElement('button');button.className='btn btn-primary';button.textContent='Approve these commands';button.disabled=!canApprove||!task.executionContractDigest||['in_progress','verification_running','completed','cancelled'].includes(task.status);
  const feedback=document.createElement('p');feedback.setAttribute('role','status');body.append(button,feedback);
  const draft=document.createElement('button');draft.type='button';draft.className='btn btn-secondary';draft.textContent='Draft plan with model';draft.disabled=!task.contract||['in_progress','verification_running','completed','cancelled'].includes(task.status);
  draft.title='Creates a reviewable draft only. It never approves or runs commands.';
  draft.onclick=async()=>{draft.disabled=true;feedback.textContent='Asking the configured model for a bounded draft…';try{const result=await conversationRequest('/api/tasks/'+encodeURIComponent(task.id)+'/draft-plan','POST',{});if(!dialog.isConnected)return;feedback.textContent=result.message||'Draft created. Review the commands before approval.';if(result.draft?.commands){task.executionPlanDraft=result.draft;executionPlan();}}catch(error){feedback.textContent='Draft unavailable: '+error.message;draft.disabled=false;}};
  body.append(draft);
  button.onclick=async()=>{button.disabled=true;try{await conversationRequest('/api/tasks/'+encodeURIComponent(task.id)+'/approve-plan','POST',{expectedUpdatedAt:task.updatedAt,contractDigest:task.executionContractDigest,commands});if(dialog.isConnected)await refresh();}catch(error){feedback.textContent=error.message;button.disabled=false;}};
  if(record){const revoke=document.createElement('button');revoke.className='btn btn-secondary';revoke.textContent='Revoke approval';revoke.disabled=!(permissions.includes('*')||permissions.includes('approvals:*')||permissions.includes('approvals:decide'))||['in_progress','verification_running'].includes(task.status);revoke.title=['in_progress','verification_running'].includes(task.status)?'Pause the task before revoking approval':'';revoke.onclick=async()=>{revoke.disabled=true;try{await conversationRequest('/api/tasks/'+encodeURIComponent(task.id)+'/revoke-plan','POST',{expectedUpdatedAt:task.updatedAt});if(dialog.isConnected)await refresh();}catch(error){feedback.textContent=error.message;revoke.disabled=false;}};body.append(revoke);}
 }
 const planTab=document.createElement('button');planTab.className='btn btn-secondary';planTab.dataset.section='plan';planTab.textContent='Execution plan';dialog.querySelector('.work-detail-tabs').append(planTab);
 function decisions(){
  body.replaceChildren();
  const title=document.createElement('h3');title.textContent='Decision history';
  const intro=document.createElement('p');intro.className='memory-disclosure';intro.textContent='Saved approvals and rejections connected to this task. These records explain what a person decided; they do not claim that work ran.';
  body.append(title,intro);
  const version=++sectionLoad;
  const loading=document.createElement('p');loading.className='memory-disclosure';loading.textContent='Loading saved decisions…';body.append(loading);
  conversationRequest('/api/approvals').then(approvals=>{
    if(version!==sectionLoad||!dialog.isConnected||selected!=='decisions')return;
    loading.remove();const records=approvals.filter(item=>item.taskId===task.id);
    if(!records.length){const empty=document.createElement('p');empty.textContent='No approval or rejection is recorded for this task.';body.append(empty);return;}
    const list=document.createElement('div');list.className='task-decision-list';
    for(const record of records.sort((a,b)=>Date.parse(b.updatedAt||b.createdAt)-Date.parse(a.updatedAt||a.createdAt))){const item=document.createElement('article');item.className='task-decision-record';const state=document.createElement('span');state.className='badge '+(record.status==='approved'?'badge-green':record.status==='rejected'?'badge-red':'badge-muted');state.textContent=record.status;const copy=document.createElement('div');const action=document.createElement('strong');action.textContent=record.action||'Review request';const meta=document.createElement('small');meta.textContent='Requested '+new Date(record.createdAt).toLocaleString()+(record.updatedAt&&record.updatedAt!==record.createdAt?' · Updated '+new Date(record.updatedAt).toLocaleString():'');const description=document.createElement('p');description.textContent=record.description||'No decision description recorded.';copy.append(action,meta,description);if(record.decisionNotes){const notes=document.createElement('p');notes.className='task-decision-notes';notes.textContent='Decision notes: '+record.decisionNotes;copy.append(notes);}item.append(state,copy);if(record.status==='pending'){const consequence=document.createElement('p');consequence.className='memory-disclosure';consequence.textContent='The Review Desk records your decision and notes. It does not start this task.';const decide=document.createElement('button');decide.type='button';decide.className='btn btn-secondary';decide.textContent='Review and decide';decide.onclick=()=>{dialog.close();openApprovalRequest(record.id);};item.append(consequence,decide);}list.append(item);}body.append(list);
  }).catch(error=>{if(version===sectionLoad&&dialog.isConnected&&selected==='decisions')loading.textContent='Could not load saved decisions: '+error.message;});
 }
  async function section(name){selected=name;const version=++sectionLoad;dialog.querySelectorAll('[data-section]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.section===name)));if(name==='overview'){overview();return;}if(name==='boundaries'){boundaries();return;}if(name==='plan'){executionPlan();return;}if(name==='decisions'){decisions();return;}renderTaskSectionLoading(body,name);try{const response=await fetch('/api/tasks/'+encodeURIComponent(task.id)+'/'+name);const result=await response.json();if(version!==sectionLoad||!dialog.isConnected)return;if(!response.ok){const message=result.reason||result.error||'Records unavailable';if(name==='evidence'&&message==='No evidence pack has been generated for this task.')renderTaskSectionEmpty(body,name,message);else renderTaskSectionError(body,name,message,()=>section(name));return;}if(name==='diff')renderTaskChanges(body,result);else if(name==='activity')renderTaskActivity(body,result);else renderTaskEvidence(body,result);}catch(error){if(version===sectionLoad&&dialog.isConnected)renderTaskSectionError(body,name,error.message,()=>section(name));}}
 async function refresh(refreshSection=true){const version=++refreshLoad;const button=dialog.querySelector('[data-refresh]');button.disabled=true;dialog.querySelector('[data-freshness]').textContent='Checking current task status…';try{const [saved,harness,me]=await Promise.all([conversationRequest('/api/tasks/'+encodeURIComponent(task.id)),conversationRequest('/api/harnesses'),conversationRequest('/api/auth/me')]);if(version!==refreshLoad||!dialog.isConnected)return;const changed=task.updatedAt!==saved.updatedAt||task.status!==saved.status;task=saved;runtime=harness.runtime;identity=me;heading();dialog.querySelector('[data-freshness]').textContent='Checked '+new Date().toLocaleTimeString();if(refreshSection||changed)await section(selected);}catch(error){if(version===refreshLoad&&dialog.isConnected)dialog.querySelector('[data-freshness]').textContent='Could not refresh. Showing saved snapshot: '+error.message;}finally{if(version===refreshLoad)button.disabled=false;}}
 for(const button of dialog.querySelectorAll('[data-section]'))button.onclick=()=>section(button.dataset.section);dialog.querySelector('[data-refresh]').onclick=()=>refresh();heading();overview();document.body.appendChild(dialog);dialog.showModal();refresh();
}
`;
